### ISSUE TITLE
PShape, SVG broken on Android

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#1092]
_Original author: allan.be...@gmail.com (April 10, 2012 19:44:23)_

<b>What steps will reproduce the problem?</b>
1. open LoadDisplayShape sketch from the Processing examples (enclosed)
2. switch to Android mode
3. Run sketch (either on emulator or device)

Expected the sketch to display on Android emulator or device.  Instead, the Processing IDE displays the following stack trace:

FATAL EXCEPTION: Animation Thread
java.lang.IllegalArgumentException: http://apache.org/xml/features/nonvalidating/load-external-dtd
    at org.apache.harmony.xml.parsers.DocumentBuilderFactoryImpl.setAttribute(DocumentBuilderFactoryImpl.java:86)
    at processing.core.XML.&lt;init&gt;(XML.java:82)
    at processing.core.XML.&lt;init&gt;(XML.java:62)
    at processing.core.PShapeSVG.&lt;init&gt;(PShapeSVG.java:158)
    at processing.core.PApplet.loadShape(Unknown Source)
    at processing.core.PApplet.loadShape(Unknown Source)
    at processing.test.loaddisplayshape.LoadDisplayShape.setup(LoadDisplayShape.java:30)
    at processing.core.PApplet.handleDraw(Unknown Source)
    at processing.core.PGraphicsAndroid2D.requestDraw(PGraphicsAndroid2D.java:161)
    at processing.core.PApplet.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:1019)

This is consistent with other SVGs I have tried.  I am apparently not alone:
http://forum.processing.org/topic/fatal-exception-animation-thread-error-with-svg-file

<b>What version of the product are you using? On what operating system?</b>
• Processing 2.0a5
• Mac OSX 10.7.3
• Android SDK r17
• Samsung Galaxy Tab 8.9, running Android 3.2

_Original issue: http://code.google.com/p/processing/issues/detail?id=1054_

**Comment by shoaibmirza** [comment]
you need to declare the screen diamention dimension, for Example fullscreen(P2D)/size(width,height,P3D);.
