### ISSUE TITLE
IllegalArgumentException: Cannot use this version of rotate() on a PMatrix2D with PShape.rotateX()

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#1342]
_Original author: tilus...@gmail.com (October 12, 2012 14:33:39)_

<b>If possible, please attach the smallest possible sketch that reproduces</b>
your problem. First make a tiny example, then use Tools -&gt; Archive Sketch
<b>to create a zip file, and then attach it to this bug report.</b>

<b>What steps will reproduce the problem?</b>
1. Grab the example code from http://processing.org/reference/PShape_rotateX_.html:

PShape s;

void setup() {
  size(100, 100, P3D);
  s = loadShape(&quot;ohio.svg&quot;);
}

void draw() {
  background(204);
  shape(s);
}

void mousePressed() {
  // Rotate the shape around the x-axis each time the mouse is pressed
  s.rotateX(0.1);  
}

2. Run it

<b>What is the expected output? What do you see instead?</b>
Expected: Rotate the shape around the x-axis each time the mouse is pressed
What I see: exception thrown - IllegalArgumentException: Cannot use this version of rotate() on a PMatrix2D
Exception in thread &quot;Animation Thread&quot; java.lang.IllegalArgumentException: Cannot use this version of rotate() on a PMatrix2D.
	at processing.core.PMatrix2D.rotate(PMatrix2D.java:173)
	at processing.opengl.PShapeOpenGL.calcTransform(PShapeOpenGL.java:2010)
	at processing.opengl.PShapeOpenGL.transformImpl(PShapeOpenGL.java:1982)
	at processing.opengl.PShapeOpenGL.transform(PShapeOpenGL.java:1976)
	at processing.opengl.PShapeOpenGL.rotate(PShapeOpenGL.java:1899)
	at processing.opengl.PShapeOpenGL.rotateX(PShapeOpenGL.java:1881)
	at geo_test03.mousePressed(geo_test03.java:38)
	at processing.core.PApplet.handleMouseEvent(PApplet.java:2433)
	at processing.core.PApplet.dequeueMouseEvents(PApplet.java:2373)
	at processing.core.PApplet.handleDraw(PApplet.java:2139)
	at processing.opengl.PGL$PGLListener.display(PGL.java:2593)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:189)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:177)
	at javax.media.opengl.awt.GLCanvas$DisplayAction.run(GLCanvas.java:928)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:425)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:364)
	at javax.media.opengl.awt.GLCanvas$DisplayOnEventDispatchThreadAction.run(GLCanvas.java:945)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$000(Unknown Source)
	at java.awt.EventQueue$1.run(Unknown Source)
	at java.awt.EventQueue$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

<b>What version of the product are you using? On what operating system?</b>
Processing 2.0b3 on Ubuntu Linux 12.04 64bit.

<b>Please provide any additional information below.</b>

<b>Note: Please do not link to locations on other sites, such as your own</b>
<b>image site, video site, blog, etc. Include the relevant information here</b>
<b>with the report.</b>

_Original issue: http://code.google.com/p/processing/issues/detail?id=1304_

**Comment by nat45928** [comment]
Has this been looked at at all? It's been a bug for a while now.

**Comment by JakubValtar** [comment]
Works okay in 3.0a11, can be closed.
