### ISSUE TITLE
Processing doesn't work behind authenticated proxy (update checks, library manager...) 

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#1476]
_Original author: eoin.ros...@gmail.com (December 04, 2012 16:47:50)_

Or maybe this is a feature request for a processing.exe flag to use system proxy, I have no idea what I'm doing.

Also would be awesome if the library updater could consider those unfortunate souls behind corporate proxies when it is implemented.

<b>What steps will reproduce the problem?</b>
When behind an auth'd proxy, simply opening a blank sketch and waiting for the built-in delay you get the error below

<b>What is the expected output? What do you see instead?</b>
java.net.ConnectException: Connection timed out: connect
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
    at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
    at java.net.Socket.connect(Socket.java:525)
    at java.net.Socket.connect(Socket.java:475)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:163)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:394)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:529)
    at sun.net.www.http.HttpClient.&lt;init&gt;(HttpClient.java:233)
    at sun.net.www.http.HttpClient.New(HttpClient.java:306)
    at sun.net.www.http.HttpClient.New(HttpClient.java:323)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:860)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:801)
    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:726)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1049)
    at java.net.URL.openStream(URL.java:1010)
    at processing.app.UpdateCheck.readInt(UpdateCheck.java:131)
    at processing.app.UpdateCheck.updateCheck(UpdateCheck.java:93)
    at processing.app.UpdateCheck$1.run(UpdateCheck.java:63)
    at java.lang.Thread.run(Thread.java:619)

<b>What version of the product are you using? On what operating system?</b>
2.0b6

<b>Please provide any additional information below.</b>

<b>Note: Please do not link to locations on other sites, such as your own</b>
<b>image site, video site, blog, etc. Include the relevant information here</b>
<b>with the report.</b>

_Original issue: http://code.google.com/p/processing/issues/detail?id=1438_

**Comment by Fraser1982** [comment]
Hi, apologies for commenting on an old post but its relevant to the issues I am experiencing. 

So a wee bit background, I am a computer technician for a secondary school and one of the teachers wants to teach using Processing 3.4 We have installed this software on 20+ PCs in  suite but it wasn't running as expected (freezing for considerable time when trying to run something).

Anyway, from a wee bit research it was apparent it was a proxy settings issue. If we add the proxy detials to processing.txt it runs fine. My problem however is that we don't allow users access to the C drive so we can't have them make the changes themself, has anyone a solution for us to automate this change? If it was just one user it would be fine, but its multiple classes, all sitting at different desks each time. 

Any help would be great.

**Comment by benfry** [comment]
You'd need to make a custom install of Processing… The `lib/defaults.txt` file is the template for what becomes `preferences.txt`. If you change it in the defaults file, then deploy that version of Processing to the machines, you should be all set. 

If you run into any other issues, please file a new issue so we can get it sorted out for you.
