### ISSUE TITLE
error when using Android 

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#1569]
_Original author: dudea...@yahoo.com (January 03, 2013 18:02:55)_

I have installed the SDK per the wiki but when I attempt to run something as simple as &quot;ellipse (80,80,50,50);&quot;

Here is the console output:

-set-mode-check:

-set-debug-files:

-check-env:
Android SDK Tools Revision 21.0.1
Installed at C:\Program Files\Android\android-sdk

-setup:
     [echo] Project Name: sketch_130103a
Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-build-setup:
     [echo] Resolving Build Target for sketch_130103a...
Project Target:   Android 2.3.3
API level:        10
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\android8290621218921590411sketch\bin
    [mkdir] Created dir: C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\android8290621218921590411sketch\bin\res
    [mkdir] Created dir: C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\android8290621218921590411sketch\gen
    [mkdir] Created dir: C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\android8290621218921590411sketch\bin\classes
    [mkdir] Created dir: C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\android8290621218921590411sketch\bin\dexedLibs
     [echo] ----------
     [echo] Resolving Dependencies for sketch_130103a...
Library dependencies:
No Libraries

---

API&lt;=15: Adding annotations.jar to the classpath.
     [echo] ----------
     [echo] Building Libraries with 'debug'...
   [subant] No sub-builds to iterate on

-pre-build:

-code-gen:
Merging AndroidManifest files into one.
Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
No RenderScript files to compile.
     [echo] ----------
     [echo] Handling Resources...
Generating resource IDs...
     [echo] ----------
     [echo] Handling BuildConfig class...
Generating BuildConfig class.

-pre-compile:

-compile:
    [javac] Since compiler setting isn't classic or modern, ignoring fork setting.
    [javac] Since compiler setting isn't classic or modern, ignoring fork setting.
    [javac] Since compiler setting isn't classic or modern, ignoring fork setting.
    [javac] Compiling 3 source files to C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\android8290621218921590411sketch\bin\classes
    [javac] Since compiler setting isn't classic or modern, ignoring fork setting.

-post-compile:

-obfuscate:

-dex:
input: C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\android8290621218921590411sketch\bin\classes
input: C:\Program Files\Android\android-sdk\tools\support\annotations.jar
input: C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\android8290621218921590411sketch\libs\processing-core.jar
Pre-Dexing C:\Program Files\Android\android-sdk\tools\support\annotations.jar -&gt; annotations-23306d58b89c9a8e6e1479880a70ed77.jar
Pre-Dexing C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\android8290621218921590411sketch\libs\processing-core.jar -&gt; processing-core-6fbe8ebf836b7762b2105d7b4a093cb9.jar
Converting compiled files and external libraries into C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\android8290621218921590411sketch\bin\classes.dex...
       [dx] Merged dex A (6 defs/1.9KiB) with dex B (2 defs/1.1KiB). Result is 8 defs/2.9KiB. Took 0.1s
       [dx] Merged dex A (8 defs/2.9KiB) with dex B (118 defs/523.1KiB). Result is 126 defs/619.6KiB. Took 0.1s

-crunch:
   [crunch] Crunching PNG Files in source dir: C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\android8290621218921590411sketch\res
   [crunch] To destination dir: C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\android8290621218921590411sketch\bin\res
   [crunch] Processing image to cache: C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\android8290621218921590411sketch\res\drawable-hdpi\icon.png =&gt; C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\android8290621218921590411sketch\bin\res\drawable-hdpi\icon.png
   [crunch](processed image to cache entry C:DOCUME~1ADMINI~1LOCALS~1Tempandroid8290621218921590411sketchbinresdrawable-hdpiicon.png: 0% size of source)
   [crunch] Processing image to cache: C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\android8290621218921590411sketch\res\drawable-ldpi\icon.png =&gt; C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\android8290621218921590411sketch\bin\res\drawable-ldpi\icon.png
   [crunch](processed image to cache entry C:DOCUME~1ADMINI~1LOCALS~1Tempandroid82906212189
   [crunch] 21590411sketchbinresdrawable-ldpiicon.png: 0% size of source)
   [crunch] Processing image to cache: C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\android8290621218921590411sketch\res\drawable\icon.png =&gt; C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\android8290621218921590411sketch\bin\res\drawable\icon.png
   [crunch](processed image to cache entry C:DOCUME~1ADMINI~1LOCALS~1Tempandroid8290621218921590411sketchbinresdrawableicon.png: 0% size of source)
   [crunch] Crunched 3 PNG files to update cache

-package-resources:
Creating full resource package...
     [aapt] Warning: AndroidManifest.xml already defines debuggable (in http://schemas.android.com/apk/res/android); using existing value in manifest.

-package:
Current build type is different than previous build: forced apkbuilder run.
Creating sketch_130103a-debug-unaligned.apk and signing it with a debug key...

BUILD FAILED
C:\Program Files\Android\android-sdk\tools\ant\build.xml:951: The following error occurred while executing this line:
C:\Program Files\Android\android-sdk\tools\ant\build.xml:962: The following error occurred while executing this line:
C:\Program Files\Android\android-sdk\tools\ant\build.xml:319: com.android.sdklib.build.ApkCreationException: java.io.IOException: Keystore was tampered with, or password was incorrect
    at com.android.sdklib.build.ApkBuilder.getDebugKey(ApkBuilder.java:308)
    at com.android.sdklib.build.ApkBuilder.&lt;init&gt;(ApkBuilder.java:392)
    at com.android.ant.ApkBuilderTask.execute(ApkBuilderTask.java:334)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
    at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
    at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:398)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
    at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
    at com.android.ant.IfElseTask.execute(IfElseTask.java:124)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
    at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
    at com.android.ant.IfElseTask.execute(IfElseTask.java:124)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
    at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
    at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:398)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
    at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:390)
    at org.apache.tools.ant.Target.performTasks(Target.java:411)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
    at processing.mode.android.AndroidBuild.antBuild(AndroidBuild.java:415)
    at processing.mode.android.AndroidBuild.build(AndroidBuild.java:73)
    at processing.mode.android.AndroidMode.handleRunEmulator(AndroidMode.java:183)
    at processing.mode.android.AndroidEditor$13.run(AndroidEditor.java:345)
Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect
    at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:771)
    at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:38)
    at java.security.KeyStore.load(KeyStore.java:1185)
    at com.android.sdklib.internal.build.DebugKeyProvider.loadKeyEntry(DebugKeyProvider.java:171)
    at com.android.sdklib.internal.build.DebugKeyProvider.&lt;init&gt;(DebugKeyProvider.java:104)
    at com.android.sdklib.build.ApkBuilder.getDebugKey(ApkBuilder.java:272)
    ... 60 more
Caused by: java.security.UnrecoverableKeyException: Password verification failed
    at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:769)
    ... 65 more

Total time: 19 seconds

_Original issue: http://code.google.com/p/processing/issues/detail?id=1531_

**Comment by cabin33** [comment]
my error fixed by delete debug.keystore "rm ~/.android/debug.keystore"
