### ISSUE TITLE
add conditional compilation to support same code w/ different modes

### ISSUE THREAD

**Issue by ericsoco** [processing/processing#1637]
maybe a pipe dream, but when writing for multiple platforms (modes), it would be nice to be able to do C-style conditional compilation to avoid having to, for example, comment out Android imports that don't work in Java mode, or comment out code that only compiles for one platform or another.

or maybe a different way around this problem, like tagging a tab as mode-specific, to keep all code in the same sketch but compile only what's needed per mode...

**Comment by sdaau** [comment]
OK, so let me comment with a concrete example as a question - I need to display .gifs in my Processing application, which I want to run in both Desktop (linux) and Android modes. I search a bit, and I find the https://github.com/01010101/GifAnimation library, with an example Processing sketch file, say, https://github.com/01010101/GifAnimation/blob/master/examples/gifDisplay/gifDisplay.pde - with a decently easy usage interface:

~~~java
Gif loopingGif;
...
public void setup() {
  loopingGif = new Gif(this, "lavalamp.gif");
}
...
void draw() {
  image(loopingGif, 10, height / 2 - loopingGif.height / 2);
}
...
~~~
 
So I do something like this in my code, build for Desktop, all works fine. Then I switch to Android mode, the application `.apk` builds fine, installs on the device fine, and upon run, it crashes with:

~~~plain
FATAL EXCEPTION: Animation Thread
Process: processing.test.mytest, PID: 12371
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/image/BufferedImage;
	at gifAnimation.GifDecoder.readImage(Unknown Source)
	at gifAnimation.GifDecoder.readContents(Unknown Source)
	at gifAnimation.GifDecoder.read(Unknown Source)
~~~

... and indeed, [GifAnimation/GifDecoder.java](https://github.com/01010101/GifAnimation/blob/master/src/gifAnimation/GifDecoder.java) does:

~~~java
		// create new image to receive frame data
		image = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB_PRE);
~~~

Ok, so if I look around a bit, it turns out AWT Java classes are not present in Android, and so, say https://stackoverflow.com/questions/6577738/drawing-a-java-awt-image-bufferedimage-in-an-android-view/6578873#6578873 recommends:

> in android its a little different, instead of having an instance of BufferedImage you have an instance of Drawable. Drawable can draw a BufferedImage

Ok, then, so let's say I want to now do the hacking to gifAnimation so it supports android. Would I have to copy `GifDecoder.java` to `GifDecoderDesktop.java`, and add a new `GifDecoderAndroid.java` - along with changing the corresponding class names? If not at compile-time, how would I choose at runtime which of these classes to instantiate? Or could I conditionally assign classes, as in `GifDecoder = GifDecoderAndroid;`, so in that sense the `.pde` code would run unchanged, regardless if it is in Desktop or Android mode? What would be the recommended approach in this example?

**Comment by ajavamind** [comment]
My feature request for this issue as described in [duplicate issue 6186]{https://github.com/processing/processing/issues/6186}

Feature Request:
Processing does a good job of running a sketch across multiple platforms: Windows, Android, MacOS, and Linux.
However I often run into problems with minor code issues in Android that prevent my sketch from compiling. I am forced to comment out some Java code and replace it with Android code and vice versa depending on the platform. Usually this is a very small part of a sketch. These sketch incompatibilities may eventually be fixed in subsequent updates, but often I can't wait. A library may only exist on one platform so include statements fail.

Often I will develop a sketch first on a Windows PC in Java mode, and then adapt it to Android. I also want to run the sketch on MacOS and Linux.

Would you please consider adding a meta comment in the source code of the first line of a PDE file indicating to include that file in a build only when it matches the mode being compiled. The **code** folder **sketch.properities** file has a mode entry for the code preprocessor.

Something like:
//@java
//@android
//@MacOS
//@Linux

This feature request would allow sketch writers to isolate their platform dependent code in a single PDE file without needing to change or replace any lines to get it to compile.

I think it is worthwhile having seamless code that can run on all Processing platforms. Google added Android apps to Chromebooks used in many educational settings, giving more incentive for artist developers to offer seamless versions of a sketch for Android. Likewise for MacOS versions.

**Comment by benfry** [comment]
Thanks for re-posting. Java has added a lot of new syntax since this was first proposed and I wonder if there's a more elegant way to handle this with newer syntax. i.e. if there's a way to use Java's annotation mechanism to signal ignoring a chunk of code, rather than having to roll our own syntax and pre-preprocessor for it.

Fun fact: Processing itself used this in its own source code for the first few years: the “make” command was a Perl script that implemented something like #ifdef. (Having excised that from the source and the build process, the thought of bringing back something similar for code written in the PDE itself was making me a little wary…)

**Comment by dfkettle** [comment]
Maybe off-topic, but is there a way to query what mode a program is running in? For example, if there were a hypothetical function called 'targetMode()', you could write something like this:

```
if (targetMode() == ANDROID) {
    // do this
} else {
    // do that
}
```

I know this isn't the same as conditional compilation (I've done some programming in C/C++ and Assembly), and it would increase the size of the code generated, but it might be useful in some situations. Maybe such a function already exists, but isn't documented?
