### ISSUE TITLE
“String index out of range” error with bracket handling in the editor

### ISSUE THREAD

**Issue by SableRaf** [processing/processing#1940]
While trying to select a piece of code I got this error:

```Exception in thread "AWT-EventQueue-0" java.lang.StringIndexOutOfBoundsException: String index out of range: 910
	at java.lang.String.charAt(String.java:686)
	at processing.app.syntax.Brackets.findMatchingBracket(Brackets.java:69)
	at processing.app.syntax.JEditTextArea.updateBracketHighlight(JEditTextArea.java:2038)
	at processing.app.syntax.JEditTextArea.select(JEditTextArea.java:1235)
	at processing.app.syntax.JEditTextArea$DragHandler.mouseDragged(JEditTextArea.java:2336)
	at java.awt.AWTEventMulticaster.mouseDragged(AWTEventMulticaster.java:302)
	at java.awt.Component.processMouseMotionEvent(Component.java:6430)
	at javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3293)
	at java.awt.Component.processEvent(Component.java:6151)
	at java.awt.Container.processEvent(Container.java:2083)
	at java.awt.Component.dispatchEventImpl(Component.java:4744)
	at java.awt.Container.dispatchEventImpl(Container.java:2141)
	at java.awt.Component.dispatchEvent(Component.java:4572)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4619)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4297)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4210)
	at java.awt.Container.dispatchEventImpl(Container.java:2127)
	at java.awt.Window.dispatchEventImpl(Window.java:2489)
	at java.awt.Component.dispatchEvent(Component.java:4572)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:704)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:663)
	at java.awt.EventQueue$2.run(EventQueue.java:661)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:677)
	at java.awt.EventQueue$3.run(EventQueue.java:675)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:674)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)```

**Comment by fiawn** [comment]
Same problem is happening here (Windows 10, Processing 3.0.2):

Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at processing.app.syntax.Brackets.findMatchingBracket(Brackets.java:54)
	at processing.app.syntax.JEditTextArea.updateBracketHighlight(JEditTextArea.java:2083)
	at processing.app.syntax.JEditTextArea.select(JEditTextArea.java:1273)
	at processing.app.syntax.JEditTextArea.setCaretPosition(JEditTextArea.java:1209)
	at processing.app.syntax.InputHandler$prev_line.actionPerformed(InputHandler.java:971)
	at processing.app.syntax.InputHandler.executeAction(InputHandler.java:310)
	at processing.app.syntax.DefaultInputHandler.keyPressed(DefaultInputHandler.java:220)
	at processing.app.syntax.PdeInputHandler.keyPressed(PdeInputHandler.java:221)
	at processing.app.syntax.JEditTextArea.processKeyEvent(JEditTextArea.java:1992)
	at processing.mode.java.pdex.JavaTextArea.processKeyEvent(JavaTextArea.java:221)

**Comment by benfry** [comment]
@fiawn That's not the same error or error message. Please file a new bug if you're seeing something like that.
