### ISSUE TITLE
"Buffers have not been created" error for sketches w/o draw()

### ISSUE THREAD

**Issue by mariuswatz** [processing/processing#2469]
On Windows: Sketches w/o draw() that call exit() in setup() gives a "Buffers have not been created" error (full stack trace below.) This is a trivial issue for the most part, but can be confusing for sketches that process data in setup() and then exit. Confirmed for 2.1.2 on Windows.

Possible workaround: Creating a draw() w/ a call to exit(), preferably w/ "if(frameCount>5) exit()").

Example:
```
void setup() {
  exit();
}
```

produces the below:

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Buffers have not been created
	at sun.awt.windows.WComponentPeer.getBackBuffer(Unknown Source)
	at java.awt.Component$FlipBufferStrategy.getBackBuffer(Unknown Source)
	at java.awt.Component$FlipBufferStrategy.updateInternalBuffers(Unknown Source)
	at java.awt.Component$FlipBufferStrategy.createBuffers(Unknown Source)
	at java.awt.Component$FlipBufferStrategy.<init>(Unknown Source)
	at java.awt.Component$FlipSubRegionBufferStrategy.<init>(Unknown Source)
	at java.awt.Component.createBufferStrategy(Unknown Source)
	at java.awt.Window.createBufferStrategy(Unknown Source)
	at javax.swing.BufferStrategyPaintManager$BufferInfo.createBufferStrategy(Unknown Source)
	at javax.swing.BufferStrategyPaintManager$BufferInfo.createBufferStrategy(Unknown Source)
	at javax.swing.BufferStrategyPaintManager$BufferInfo.getBufferStrategy(Unknown Source)
	at javax.swing.BufferStrategyPaintManager.prepare(Unknown Source)
	at javax.swing.BufferStrategyPaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at java.awt.GraphicsCallback$PaintCallback.run(Unknown Source)
	at sun.awt.SunGraphicsCallback.runOneComponent(Unknown Source)
	at sun.awt.SunGraphicsCallback.runComponents(Unknown Source)
	at java.awt.Container.paint(Unknown Source)
	at java.awt.Window.paint(Unknown Source)
	at javax.swing.RepaintManager$3.run(Unknown Source)
	at javax.swing.RepaintManager$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1100(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

Working alternative:

```
void setup() {
}

void draw() {
   if(frameCount>5) exit();
}
```

Apologies, as always.

**Comment by benfry** [comment]
Should be resolved for 3.0a8. A version of this showed up on Linux while testing something else, and it was part of a batch of code that's now been rewritten to avoid threading quirks like this.
