### ISSUE TITLE
processing.opengl.PJOGL.syncBackTexture(PJOGL.java:597)

### ISSUE THREAD

**Issue by nkint** [processing/processing#2928]
Hi!
I'm doing  project with multiple PApplet instance wit Eclipse and Processing 2.1.1. Each PApplet instance has a PeasyCam and a ControlP5 instances.

I didn't manage to reproduce a minimum working example that throws this exception but I'm working on it. (I'm trying to isolate the PApplet and the JFrame creation and do not include any of my application things).

Sometimes, only sometimes, I get this error with this stacktrace:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at processing.opengl.PJOGL.syncBackTexture(PJOGL.java:597)
	at processing.opengl.PGraphicsOpenGL.beginPixelsOp(PGraphicsOpenGL.java:1829)
	at processing.opengl.PGraphicsOpenGL.readPixels(PGraphicsOpenGL.java:5438)
	at processing.opengl.PGraphicsOpenGL.saveSurfaceToPixels(PGraphicsOpenGL.java:5428)
	at processing.opengl.PGraphicsOpenGL.endDraw(PGraphicsOpenGL.java:1693)
	at processing.core.PApplet.handleDraw(PApplet.java:2326)
	at processing.opengl.PJOGL$PGLListener.display(PJOGL.java:862)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:652)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:636)
	at javax.media.opengl.awt.GLCanvas$10.run(GLCanvas.java:1284)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1106)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:981)
	at javax.media.opengl.awt.GLCanvas$11.run(GLCanvas.java:1295)
	at javax.media.opengl.Threading.invoke(Threading.java:193)
	at javax.media.opengl.awt.GLCanvas.display(GLCanvas.java:541)
	at javax.media.opengl.awt.GLCanvas.paint(GLCanvas.java:595)
	at sun.awt.RepaintArea.paintComponent(RepaintArea.java:264)
	at sun.lwawt.LWRepaintArea.paintComponent(LWRepaintArea.java:59)
	at sun.awt.RepaintArea.paint(RepaintArea.java:240)
	at sun.lwawt.LWComponentPeer.handleJavaPaintEvent(LWComponentPeer.java:1312)
	at sun.lwawt.LWComponentPeer.handleEvent(LWComponentPeer.java:1196)
	at java.awt.Component.dispatchEventImpl(Component.java:4959)
	at java.awt.Component.dispatchEvent(Component.java:4705)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I don't know how to do with it because I don't know where to handle this exception (I don't see any file that I wrote) - so running in debug mode does not help at all.

I suppose that it involves some kind of static creation of opengl context.

What can I do? How can I debug it? Can importing the source from github and not the precompiled core.jar v.2.1.1 help for debugging it? Sorry but even if I know to program in java and I can use Eclipse I'm not very much into how Processing and Awt works behind the hoods.

Any kind of idea could be very useful. Right now, even if this happens only sometimes, makes the application useless.

Thanks in advance.

**Comment by codeanticode** [comment]
no updates, seems fixed from my own tests (Demos|Tests|EmbedFrameTest needs to be updated to use the latest API change in PApplet though). Closing.
