### ISSUE TITLE
Building Processing fails on Windows due to "Unexpected end of ZLIB input stream"

### ISSUE THREAD

**Issue by joelmoniz** [processing/processing#2960]
The following is the error message obtained when trying to run `ant run` (or `ant build`) on a Windows 8.1 system:

```
BUILD FAILED
C:\Users\Joel\Documents\Code\p5\processing\build\build.xml:215: The following error occurred while executing this line:
C:\Users\Joel\Documents\Code\p5\processing\build\build.xml:850: Error while expanding C:\Users\Joel\Documents\Code\p5\processing\build\windows\jre.tgz
java.io.EOFException: Unexpected end of ZLIB input stream
        at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
        at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:116)
        at org.apache.tools.tar.TarBuffer.readBlock(TarBuffer.java:253)
        at org.apache.tools.tar.TarBuffer.readRecord(TarBuffer.java:220)
        at org.apache.tools.tar.TarInputStream.read(TarInputStream.java:593)
        at org.apache.tools.tar.TarInputStream.skip(TarInputStream.java:206)
        at org.apache.tools.tar.TarInputStream.getNextEntry(TarInputStream.java:271)
        at org.apache.tools.ant.taskdefs.Untar.expandStream(Untar.java:165)
        at org.apache.tools.ant.taskdefs.Untar.expandFile(Untar.java:114)
        at org.apache.tools.ant.taskdefs.Expand.execute(Expand.java:132)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)

        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.Main.runBuild(Main.java:851)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
```

**Comment by benfry** [comment]
Finished the Ant task for 3.0a6.

**Comment by joelmoniz** [comment]
Thanks!

**Comment by benfry** [comment]
And just added code to have it write a temporary file in case errors happen along the way. https://github.com/processing/processing/commit/eab82bb899baba2560208a6710e1275b80875179
