### ISSUE TITLE
open() not working when building w/processing-java on OS X

### ISSUE THREAD

**Issue by rozling** [processing/processing#3030]
Yosemite 10.10.1
Processing 3.0a5 / 3.0a4

The following works when running in the IDE

```Processing
void setup(){
}

void draw(){
}

void mousePressed( ){
 open("/Applications/TextEdit.app"); 
}
```

However when building via processing-java (I am using Sublime Text) we get the following error (note the two 'opens' on the last line):

``` Java
Listening for transport dt_socket at address: 8919
java.io.IOException: Cannot run program "open": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1041)
	at java.lang.Runtime.exec(Runtime.java:617)
	at java.lang.Runtime.exec(Runtime.java:485)
	at processing.core.PApplet.exec(PApplet.java:4041)
	at processing.core.PApplet.open(PApplet.java:4031)
	at processing.core.PApplet.open(PApplet.java:3968)
	at Open_an_application.mousePressed(Open_an_application.java:26)
	at processing.core.PApplet.mousePressed(PApplet.java:3085)
	at processing.core.PApplet.handleMouseEvent(PApplet.java:2831)
	at processing.core.PApplet.dequeueEvents(PApplet.java:2725)
	at processing.core.PApplet.handleDraw(PApplet.java:2397)
	at processing.core.PGraphicsJava2D.requestDraw(PGraphicsJava2D.java:240)
	at processing.core.PApplet.run(PApplet.java:2256)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:184)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1022)
	... 13 more
Open_an_application.pde:10:0:10:0: RuntimeException: Could not open open /Applications/TextEdit.app
```

processing-java was reinstalled for both versions

**Comment by benfry** [comment]
What happens when you type `java -version` into the Terminal? 

Wonder if this is a Java 8 bug...

**Comment by rozling** [comment]
`java -version` gives me 
> java version "1.7.0_45"
> Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
> Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)

However I've just tried this in Terminal and it works.

Maybe this is a Sublime Text thing; it's just I use ST almost exclusively & haven't come across this issue with any other Processing method.

Will rule out ST and close this for now.
