### ISSUE TITLE
Build fails on Windows at [launch4j]: undefined reference to `__mingw_glob'

### ISSUE THREAD

**Issue by JakubValtar** [processing/processing#3062]
I'm on Windows 8.1 x64.
```
E:\>java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

E:\>ant -version
Apache Ant(TM) version 1.9.4 compiled on April 29 2014
```

I'm getting this error when running `ant run`:
```
[launch4j] E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\w32api\crt2.o:crt1.c:(.text+0x376):
undefined reference to `__mingw_glob'
[launch4j] E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\w32api\crt2.o:crt1.c:(.text+0x47d):
undefined reference to `__mingw_glob'
```
In context:
```
assemble:
     [copy] Copying 66 files to E:\Projekty\GitHub\processing\build\windows\work\tools
     [copy] Copying 448 files to E:\Projekty\GitHub\processing\build\windows\work\modes\java
     [copy] Copied 119 empty directories to 1 empty directory under E:\Projekty\GitHub\processing\build\windows\work\modes\java
     [copy] Copying 527 files to E:\Projekty\GitHub\processing\build\windows\work\modes\java\examples
      [get] Getting: http://download.processing.org/reference.zip
      [get] To: E:\Projekty\GitHub\processing\java\reference.zip
    [unzip] Expanding: E:\Projekty\GitHub\processing\java\reference.zip into E:\Projekty\GitHub\processing\build\windows\work\modes\java
     [move] Moving 1 file to E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\bin
     [move] Moving 1 file to E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\bin
 [launch4j] Compiling resources
 [launch4j] Linking
 [launch4j] E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\w32api\crt2.o:crt1.c:(.text+0x376): undefined reference to `__mingw_glob'
 [launch4j] E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\w32api\crt2.o:crt1.c:(.text+0x47d): undefined reference to `__mingw_glob'

BUILD FAILED
E:\Projekty\GitHub\processing\build\build.xml:239: The following error occurred while executing this line:
E:\Projekty\GitHub\processing\build\build.xml:934: net.sf.launch4j.BuilderException: net.sf.launch4j.ExecException: Exec failed (1): E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\bin\ld.exe -mi386pe --oformat pei-i386 --dynamicbase --nxcompat --no-seh --subsystem windows -s E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\w32api\crt2.o E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\head\guihead.o E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\head\head.o C:\Users\Kuba\AppData\Local\Temp\launch4j6716652191915669635o E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\w32api\libmingw32.a E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\w32api\libgcc.a E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\w32api\libmsvcrt.a E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\w32api\libkernel32.a E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\w32api\libuser32.a E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\w32api\libadvapi32.a E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\w32api\libshell32.a -o E:\Projekty\GitHub\processing\build\windows\work\processing.exe
        at net.sf.launch4j.Builder.build(Builder.java:146)
        at net.sf.launch4j.ant.Launch4jTask.execute(Launch4jTask.java:111)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.Main.runBuild(Main.java:851)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: net.sf.launch4j.ExecException: Exec failed (1): E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\bin\ld.exe -mi386pe --oformat pei-i386 --dynamicbase --nxcompat --no-seh --subsystem windows -s E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\w32api\crt2.o E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\head\guihead.o E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\head\head.o C:\Users\Kuba\AppData\Local\Temp\launch4j6716652191915669635o E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\w32api\libmingw32.a E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\w32api\libgcc.a E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\w32api\libmsvcrt.a E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\w32api\libkernel32.a E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\w32api\libuser32.a E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\w32api\libadvapi32.a E:\Projekty\GitHub\processing\build\windows\work\modes\java\application\launch4j\w32api\libshell32.a -o E:\Projekty\GitHub\processing\build\windows\work\processing.exe
        at net.sf.launch4j.Util.exec(Util.java:156)
        at net.sf.launch4j.Cmd.exec(Builder.java:212)
        at net.sf.launch4j.Builder.build(Builder.java:114)
        ... 30 more
```
I've tried deleting everything and cloning the repository again. Am I doing something wrong?

**Comment by benfry** [comment]
No, something is wrong with the new launch4j release I dropped in there, and I haven't had a chance to debug it. It may be that one of the new files isn't being copied (the previous release had fewer libs) in the dist, or it may be that it was a bad release. Just haven't had time to track it down. Fighting through things on OS X and blowing up the GUI, then gonna come back to these other build/dist issues.

**Comment by JakubValtar** [comment]
Alright, now I know where the problem can be since you changed launch4j version. I will try to fix it in the meantime.

**Comment by JakubValtar** [comment]
@benfry Should be fixed in #3066, please review when you have time.

**Comment by benfry** [comment]
What jar is this? An old version or was the .jar itself not updated properly for 3.6?

**Comment by benfry** [comment]
I'll update those other files as well once I get the GUI building again.

**Comment by JakubValtar** [comment]
Which files do you mean? I checked all files in launch4j folder and they all seem to be 3.6.

**Comment by benfry** [comment]
These fellas:
https://github.com/processing/processing/tree/master/java/application/launch4j/bin
https://github.com/processing/processing/tree/master/java/application/launch4j/lib

Or maybe they haven't changed in 3.6, so nothing was checked in... I coulda sworn I replaced them...

**Comment by JakubValtar** [comment]
I checked all of them and they are all 3.6, so you don't have to worry about this anymore. They probably haven't changed.

**Comment by benfry** [comment]
Cool, thanks for checking.
