### ISSUE TITLE
Video library is incompatible with 0233

### ISSUE THREAD

**Issue by REAS** [processing/processing#3114]
Basic video examples aren't working in 0233. The error message reports, "You may be using a library that's incompatible with this new version of Processing."

Another example reports this into the console:

```
error, disabling movieEvent() for transit.mov
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at processing.video.Movie.fireMovieEvent(Movie.java:845)
	at processing.video.Movie.invokeEvent(Movie.java:820)
	at processing.video.Movie$2.rgbFrame(Movie.java:771)
	at org.gstreamer.elements.RGBDataAppSink$AppSinkNewBufferListener.newBuffer(RGBDataAppSink.java:162)
	at org.gstreamer.elements.AppSink$2.callback(AppSink.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:455)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:485)
Caused by: java.lang.NoSuchMethodError: processing.core.PImage.init(III)V
	at processing.video.Movie.read(Movie.java:559)
	at Loop.movieEvent(Loop.java:39)
	... 15 more
```

**Comment by benfry** [comment]
Hm, this might be my fault if an image constructor has been removed, though I'm surprised this is something that was being used.

**Comment by benfry** [comment]
It was a change to support retina... Should be back to working again. 

@codeanticode please double-check
