### ISSUE TITLE
ControlP5 (ArrayIndexOutOfBoundsException:304)

### ISSUE THREAD

**Issue by DIYman** [processing/processing#3121]
Hey Guys,

I've been trying to create a drawing application with processing using ControlP5 but I had some issues. 
When I tried to create Sliders there was a error I thought it could happen because of my code but even the slider example that comes with the library is having the same issue

I would be really glad if you can help me.

Error:

ArrayIndexOutOfBoundsException:304

ControlP5 2.0.4 infos, comments, questions at http://www.sojamo.de/libraries/controlP5
a slider event. setting background to 0.0
a slider event. setting background to 0.0
a slider event. setting background to 0.0
a slider event. setting background to 128.0
java.lang.ArrayIndexOutOfBoundsException: 304
	at controlP5.BitFont.getGlyph(Unknown Source)
	at processing.core.PGraphics.textCharImpl(PGraphics.java:4681)
	at processing.core.PGraphics.textLineImpl(PGraphics.java:4669)
	at processing.core.PGraphicsJava2D.textLineImpl(PGraphicsJava2D.java:1787)
	at processing.core.PGraphics.textLineAlignImpl(PGraphics.java:4659)
	at processing.core.PGraphics.text(PGraphics.java:4356)
	at processing.core.PGraphics.text(PGraphics.java:4307)
	at processing.core.PApplet.text(PApplet.java:13183)
	at controlP5.ControlFont.draw(Unknown Source)
	at controlP5.Label.draw(Unknown Source)
	at controlP5.Label$SinglelineLabel.draw(Unknown Source)
	at controlP5.Label.draw(Unknown Source)
	at controlP5.Slider$SliderViewH.display(Unknown Source)
	at controlP5.Slider$SliderViewH.display(Unknown Source)
	at controlP5.Controller.draw(Unknown Source)
	at controlP5.ControllerGroup.drawControllers(Unknown Source)
	at controlP5.ControllerGroup.draw(Unknown Source)
	at controlP5.ControlWindow.draw(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1236)
	at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1229)
	at processing.core.PApplet.handleMethods(PApplet.java:1423)
	at processing.core.PApplet.handleDraw(PApplet.java:2401)
	at processing.core.PGraphicsJava2D.requestDraw(PGraphicsJava2D.java:240)
	at processing.core.PApplet.run(PApplet.java:2256)
	at java.lang.Thread.run(Unknown Source)
![untitled-1](https://cloud.githubusercontent.com/assets/11150791/6320555/5c5fe70e-bae9-11e4-8f8c-811668f9ff89.jpg)

**Comment by REAS** [comment]
We don't develop the ControlP5 library. As the error message mentions, please go here for questions about it: http://www.sojamo.de/libraries/controlP5

**Comment by DIYman** [comment]
Sorry for my wrong directions. :) 

Also I could fix it this morning by luck I kinda feel I gotta write my issue here sorry if I am doing something wrong

When I had the problem I was adding libraries manually, than I used Processing's built in tool for adding libraries it is now all working fine.
