### ISSUE TITLE
Copy as HTML eventually stops working

### ISSUE THREAD

**Issue by isohedral** [processing/processing#3159]
I'm teaching a course using Processing, and so I frequently copy HTML-formatted text out of the sketchbook in order to paste it into lecture notes, slides, etc. However, the "Copy as HTML" feature of the IDE is somewhat inconsistent. Frequently, after editing a given sketch for a long time, it'll start generating exceptions like this one:

```
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 15
	at processing.app.syntax.JEditTextArea.emitAsHTML(JEditTextArea.java:1783)
	at processing.app.syntax.JEditTextArea.copyAsHTML(JEditTextArea.java:1730)
	at processing.app.Editor.handleCopyAsHTML(Editor.java:1642)
	at processing.app.Editor$19.actionPerformed(Editor.java:728)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
	at javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:802)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1662)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2878)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:689)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:697)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:697)
	at javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:668)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:293)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2970)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2962)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2841)
	at processing.app.syntax.JEditTextArea.processKeyEvent(JEditTextArea.java:1934)
	at java.awt.Component.processEvent(Component.java:6282)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4861)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1895)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:762)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1027)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:899)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:727)
	at java.awt.Component.dispatchEventImpl(Component.java:4731)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

Once that happens, the sketch window is "dead" to me -- copying as HTML will no longer work. I can usually solve the problem by copying the code I want (as plain text) to a fresh sketch window and then HTML-copying it from there, or by closing and re-opening the sketch.  Sorry I don't have a more reliable way to reproduce the bug -- it just seems to start misbehaving after working with a given sketch enough.

**Comment by benfry** [comment]
What version?

**Comment by isohedral** [comment]
I'm using 2.2.1 at the moment.

**Comment by benfry** [comment]
Hm, 3.0a5 should give you better results. Not sure if this is something that's been fixed since 2.2.1.

**Comment by isohedral** [comment]
Fair enough. I haven't been able to try 3.0 yet -- I'm teaching a course and need to stick with a stable platform. Because this bug is intermittent, I'd need to open up 3.0 and fiddle around for a while hoping to reproduce it.  I'll see if I can find time to do so.  Thanks.

p.s. Do you have a favourite place for feature suggestions? I have a few that arose from my experience teaching.

**Comment by benfry** [comment]
For what it's worth, in spite of the alpha designation, 3.0a5 is in pretty good shape. (3.0a6 will be much more unstable, however.)

Feature suggestions should go here in the issues; I'll just mark them as feature requests. Just enter separate items for each, since they'll be considered, included, marked as duplicates, or closed independently from one another. Thanks!

**Comment by isohedral** [comment]
I finally had a chance to try this in 3.0a5, and I couldn't reproduce the bug. Not perfect evidence that the bug is gone (it was intermittent to begin with), but reasonably convincing.
