### ISSUE TITLE
Contributions Manager broken

### ISSUE THREAD

**Issue by joelmoniz** [processing/processing#3168]
Sorry about this. My bad. Here's the error thrown at present when trying to use the Contribution Manager, due to a teensy mistake I made when adding in feature #3155 :  
  
```
Exception in thread "Contribution List Downloader" java.lang.Error: Unresolved compilation problem: 
	The method replace(String, Contribution) is undefined for the type Map<String,Contribution>

	at processing.app.contrib.ContributionListing.replaceContribution(ContributionListing.java:126)
	at processing.app.contrib.ContributionListing.updateInstalledList(ContributionListing.java:101)
	at processing.app.contrib.ContributionManagerDialog.updateContributionListing(ContributionManagerDialog.java:456)
	at processing.app.contrib.ContributionManagerDialog$8.finished(ContributionManagerDialog.java:476)
	at processing.app.contrib.ContributionManager.download(ContributionManager.java:114)
	at processing.app.contrib.ContributionListing$2.run(ContributionListing.java:409)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by benfry** [comment]
I saw this earlier—looks like a Java 1.8 method? Thanks for fixing.

**Comment by joelmoniz** [comment]
Hmm... It is a [Java method](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#replace-K-V-). And I'm fairly certain that things were fine when I submitted my PR, and I was neither getting an error nor the red underline in Eclipse (though just before this fix, both appeared, for some reason). Ah well...

**Comment by benfry** [comment]
You probably have both 1.7 and 1.8 JVMs on your machine. I also added code today so that the JRE downloaded by `build.xml` will include a version. It's possible that the old 1.7 VM was still in use in your repo, but no longer.

**Comment by joelmoniz** [comment]
Ah yes, thanks. I do think that might have been the error, although I'm not sure how ant ended up using the 1.7 JVM to build instead of the 1.8 one. Oh well...
