### ISSUE TITLE
Can't open preferences in 3.0a6

### ISSUE THREAD

**Issue by hey2daein** [processing/processing#3215]
very excited to play with 3.0a6!
The first error I encountered is that when I try to open up preferences, it gives me an error.

Mac OSX Yosemite 10.10.3, MacbookPro Retina 15inch

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Component must be non-null
	at javax.swing.GroupLayout$ComponentSpring.<init>(GroupLayout.java:2953)
	at javax.swing.GroupLayout$ComponentSpring.<init>(GroupLayout.java:2933)
	at javax.swing.GroupLayout$Group.addComponent(GroupLayout.java:1524)
	at javax.swing.GroupLayout$ParallelGroup.addComponent(GroupLayout.java:2484)
	at javax.swing.GroupLayout$ParallelGroup.addComponent(GroupLayout.java:2454)
	at javax.swing.GroupLayout$Group.addComponent(GroupLayout.java:1505)
	at javax.swing.GroupLayout$ParallelGroup.addComponent(GroupLayout.java:2476)
	at processing.app.PreferencesFrame.<init>(PreferencesFrame.java:622)
	at processing.app.Base.handlePrefs(Base.java:1375)
	at processing.app.platform.ThinkDifferent$2.handlePreferences(ThinkDifferent.java:75)
	at com.apple.eawt._AppEventHandler$_PreferencesDispatcher.performUsing(_AppEventHandler.java:263)
	at com.apple.eawt._AppEventHandler$_PreferencesDispatcher.performUsing(_AppEventHandler.java:254)
	at com.apple.eawt._AppEventHandler$_AppEventDispatcher$1.run(_AppEventHandler.java:516)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: javax.swing.JCheckBox[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.5,border=com.apple.laf.AquaButtonBorder$Named@4118d9e,flags=288,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=javax.swing.plaf.InsetsUIResource[top=1,left=1,bottom=0,right=1],paintBorder=false,paintFocus=true,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=Increase maximum available memory to: ] is not attached to a horizontal group
	at javax.swing.GroupLayout.checkComponents(GroupLayout.java:1086)
	at javax.swing.GroupLayout.prepare(GroupLayout.java:1040)
	at javax.swing.GroupLayout.layoutContainer(GroupLayout.java:910)
	at java.awt.Container.layout(Container.java:1508)
	at java.awt.Container.doLayout(Container.java:1497)
	at java.awt.Container.validateTree(Container.java:1693)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validate(Container.java:1628)
	at java.awt.Window.dispatchEventImpl(Window.java:2748)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by benfry** [comment]
Ouch, that's unfortunate. I removed an unused preference late in the release process, but didn't remove it all the way.

Fixed for 3.0a7, which may need to happen really soon.

**Comment by hey2daein** [comment]
Thanks.
Meanwhile, I could still adjust the preferences(such as font size) through
Processing 2.2.1 installed on the same machine.

**Comment by benfry** [comment]
Ha!
