### ISSUE TITLE
save() and saveFrame() with 2X renderers fails

### ISSUE THREAD

**Issue by shiffman** [processing/processing#3255]
@benfry I'm not sure if I'm too early in the development process to report this.  The following error occurs in `JAVA2D_2X` and `P2D_2X` with `save()` and `saveFrame()`.  My desired behavior is to get a 2X PNG out for high-res screenshots.

```
Error while saving image.
java.io.IOException: image save failed.
	at processing.core.PImage.saveImageIO(PImage.java:3208)
	at processing.core.PImage.save(PImage.java:3341)
	at processing.core.PApplet.save(PApplet.java:3136)
	at exercise_7_10_spaceship.draw(exercise_7_10_spaceship.java:38)
	at processing.core.PApplet.handleDraw(PApplet.java:1858)
	at processing.core.PSurfaceAWT$14.render(PSurfaceAWT.java:1388)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:246)
java.lang.ArrayIndexOutOfBoundsException: 230400
	at java.awt.image.BufferedImage.setRGB(BufferedImage.java:1059)
	at processing.core.PImage.saveImageIO(PImage.java:3162)
	at processing.core.PImage.save(PImage.java:3341)
	at processing.core.PApplet.save(PApplet.java:3136)
	at exercise_7_10_spaceship.draw(exercise_7_10_spaceship.java:38)
	at processing.core.PApplet.handleDraw(PApplet.java:1858)
	at processing.core.PSurfaceAWT$14.render(PSurfaceAWT.java:1388)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:246)
```

**Comment by REAS** [comment]
Saving screens with P2D and P3D also fails, but it doesn't throw an error. The files appear to be the correct size in KB but the OS and image applications can't recognize them.

**Comment by REAS** [comment]
JAVA2D_2X works for saving frames in 3.0a9, but not with all of the OpenGL renderers.

**Comment by benfry** [comment]
@codeanticode is this the same as https://github.com/processing/processing/issues/3334?

**Comment by codeanticode** [comment]
It seems a different issue, with P2D/P3D the problem was that pixelWidth/pixelHeight were not initialized and stayed at 0 (irrespective of 2X). With JAVA2D, save() works, but don't have a retina machine to test JAVA2D_2X

**Comment by benfry** [comment]
@codeanticode but it's working with P2D_2X and P3D_2X with that fix?

**Comment by codeanticode** [comment]
I cannot test 2X right now, but expect that the fix solves the issue on both retina and non-retina modes. I will just reopen it and test again tomorrow on retina.

**Comment by benfry** [comment]
Working with the current version of the source.
