### ISSUE TITLE
Can't run sketches with offscreen PGraphics

### ISSUE THREAD

**Issue by JakubValtar** [processing/processing#3259]
OpenGL (broken in 9e3fb329be30f357a5662f84a029956acc2ec5d4):

Window appears and freezes, PDE just displays NullPointerException in the status bar and highlights beginDraw(), Eclipse shows this stack:
```
Exception in thread "Animation Thread" java.lang.NullPointerException
	at processing.opengl.PGraphicsOpenGL.initOffscreen(PGraphicsOpenGL.java:6526)
	at processing.opengl.PGraphicsOpenGL.beginOffscreenDraw(PGraphicsOpenGL.java:6556)
	at processing.opengl.PGraphicsOpenGL.beginDraw(PGraphicsOpenGL.java:1724)
	at tests.SortTest.draw(SortTest.java:33)
	at processing.core.PApplet.handleDraw(PApplet.java:1872)
	at processing.opengl.PSurfaceLWJGL$AnimationThread.run(PSurfaceLWJGL.java:555)
```
```processing
PGraphics buffer;

void setup() {
  size(1280, 720, P3D);
  buffer = createGraphics(width, height, P3D);
}

void draw() {
  buffer.beginDraw();
  buffer.endDraw();
}
```

JAVA2D (broken before 3.0a6 tag, don't have time to find exact commit):

No window appears, `GraphicsConfiguration null in initImage()` prints into the console
```processing
PGraphics buffer;

void setup() {
  size(1280, 720);
  buffer = createGraphics(width, height);
}

void draw() {
  buffer.beginDraw();
  buffer.endDraw();
}
```

**Comment by codeanticode** [comment]
solved after https://github.com/processing/processing/commit/56e67c99977f207c07037086665ab92b13a08370

**Comment by madsrune** [comment]
When running this sketch on 3.0a8:
```Processing
PGraphics buffer;

void setup() {
  size(1280, 720, P3D);
  buffer = createGraphics(width, height, P3D);
}

void draw() {
  buffer.beginDraw();
  buffer.endDraw();
}
```

I get:
```
Exception in thread "Thread-2" java.lang.NullPointerException
	at processing.opengl.PGraphicsOpenGL.getPixelScale(PGraphicsOpenGL.java:703)
	at processing.opengl.PJOGL.viewport(PJOGL.java:1895)
	at processing.opengl.PGraphicsOpenGL.setViewport(PGraphicsOpenGL.java:6627)
	at processing.opengl.PGraphicsOpenGL.beginDraw(PGraphicsOpenGL.java:1728)
	at sketch_150518b.draw(sketch_150518b.java:25)
	at processing.core.PApplet.handleDraw(PApplet.java:1969)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:518)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:691)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:673)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:442)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1277)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1131)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:680)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:77)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:451)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by codeanticode** [comment]
It was a regression in 3.0a8, will be fixed in a9 https://github.com/processing/processing/issues/3292
