### ISSUE TITLE
"Access is denied" for native library in temp folder when running processing-java.exe

### ISSUE THREAD

**Issue by foong** [processing/processing#3300]
hey guys, i've encountered this problem when i try to run processing-java.exe in command prompt. 

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\FOONG\AppDat
a\Local\Temp\jna-FOONG\jna664711399102231270.dll: Access is denied
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary1(Unknown Source)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at com.sun.jna.Native.loadNativeLibraryFromJar(Native.java:752)
        at com.sun.jna.Native.loadNativeLibrary(Native.java:737)
        at com.sun.jna.Native.<clinit>(Native.java:129)
        at processing.app.platform.WindowsPlatform.<clinit>(WindowsPlatform.java
:503)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at processing.app.Base.initPlatform(Base.java:239)
        at processing.mode.java.Commander.main(Commander.java:74)
```
any suggestions to fix this?

**Comment by benfry** [comment]
Doesn't look like a Processing bug, it looks like permissions are screwed up with your temp folder on Windows, or you have access restrictions that prevent you from running arbitrary code?

**Comment by foong** [comment]
Oh, do you have a suggestion to fix it? Please describe it in babysteps please, im very new.

**Comment by benfry** [comment]
That's a better question to ask on forum.processing.org. If it turns out to be a bug, we can re-open this here.
