### ISSUE TITLE
Implement CMD+Q handler on Mac OSX

### ISSUE THREAD

**Issue by codeanticode** [processing/processing#3301]
On the OpenGL renderer, quitting the running sketch using CMD+Q on Mac (sometimes) gives:

```
java.lang.ThreadDeath
	at java.lang.Thread.stop(Thread.java:850)
	at com.jogamp.newt.opengl.GLWindow$GLLifecycleHook$1.run(GLWindow.java:645)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.newt.opengl.GLWindow$GLLifecycleHook.shutdownRenderingAction(GLWindow.java:640)
	at jogamp.newt.WindowImpl.shutdown(WindowImpl.java:334)
	at jogamp.newt.WindowImpl.shutdownAll(WindowImpl.java:121)
	at jogamp.newt.DisplayImpl$1.run(DisplayImpl.java:73)
	at com.jogamp.nativewindow.NativeWindowFactory.shutdown(NativeWindowFactory.java:269)
	at com.jogamp.nativewindow.NativeWindowFactory$2$1.run(NativeWindowFactory.java:187)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by benfry** [comment]
Fixed for 3.0a9.
