### ISSUE TITLE
Using PImage.width or height in size() causes Exception

### ISSUE THREAD

**Issue by ciaron** [processing/processing#3311]
The following sketch causes an exception:
```
PImage img;

void setup() {

  img = loadImage("F4-50.jpg");
  size(img.width, img.height); // java.lang.NullPointerException
  //size(600, 797);            // OK
  
} 
```
The exception is:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at sketch_309a_bug.settings(sketch_309a_bug.java:32)
	at processing.core.PApplet.handleSettings(PApplet.java:840)
	at processing.core.PApplet.runSketchEDT(PApplet.java:9630)
	at processing.core.PApplet$4.run(PApplet.java:9500)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

This is a regression since 3.0a5. Tested with .jpg and .png PImages.

**Comment by ciaron** [comment]
As per #3312 - I misunderstood the requirements for using size(). Closing.
