### ISSUE TITLE
using variables in size() causes exception (3.0a9)

### ISSUE THREAD

**Issue by ciaron** [processing/processing#3312]
Perhaps related to #3311 ?

The following sketch causes an exception:

```
int w;
int h;
void setup() {
  w=800;
  h=800;
  size(w, h);
}
```

The exception is:

```
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.awt.GraphicsConfiguration.createCompatibleImage(GraphicsConfiguration.java:150)
	at processing.core.PGraphicsJava2D.checkImage(PGraphicsJava2D.java:305)
	at processing.core.PGraphicsJava2D.beginDraw(PGraphicsJava2D.java:315)
	at processing.core.PApplet.handleDraw(PApplet.java:1945)
	at processing.core.PSurfaceAWT$13.render(PSurfaceAWT.java:1365)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:294)

```

This sketch runs however:
```
int w=800;
int h=800;
void setup() {
  size(w, h);
}
```

**Comment by StanLepunK** [comment]
Now size must be a first method if I understand the new design https://processing.org/reference/size_.html

**Comment by ciaron** [comment]
Thanks... It looks like I've been relying on an undocumented feature until now!

It was a nice feature though... I've been using it to set the sketch window size to the size of a PImage (see #3311). Looks like I'll have to re-write sketches, unless there's a way to change the behaviour? (asking hopefully ;)

**Comment by StanLepunK** [comment]
Now, you can change your size like that :+1: Now 
`````````
void setup() {
  size(100,100) ;
}


void draw() {
  surface.setResizable(false);
  surface.setResizable(true);
  surface.setSize(400,400) ;
}
`````
You'r bug is dead you can close this forum discussion :)

**Comment by ciaron** [comment]
Thanks, StanLepunk for the tip. Closing.

**Comment by benfry** [comment]
Not a new design, just more strictly enforced in 3.0a9. The reference has said that for many years.
