### ISSUE TITLE
NullPointerException when clicking on menus in Linux

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#3313]
This is the stack trace of the error i get when clicking on the Edit Menu in the menubar

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at sun.font.FontDesignMetrics$MetricsKey.init(FontDesignMetrics.java:217)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:286)
	at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1113)
	at javax.swing.JComponent.getFontMetrics(JComponent.java:1626)
	at sun.swing.MenuItemLayoutHelper.reset(MenuItemLayoutHelper.java:126)
	at javax.swing.plaf.synth.SynthMenuItemLayoutHelper.<init>(SynthMenuItemLayoutHelper.java:119)
	at javax.swing.plaf.synth.SynthGraphicsUtils.getPreferredMenuItemSize(SynthGraphicsUtils.java:437)
	at javax.swing.plaf.synth.SynthMenuItemUI.getPreferredMenuItemSize(SynthMenuItemUI.java:216)
	at javax.swing.plaf.basic.BasicMenuItemUI.getPreferredSize(BasicMenuItemUI.java:367)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.BoxLayout.checkRequests(BoxLayout.java:484)
	at javax.swing.BoxLayout.preferredLayoutSize(BoxLayout.java:301)
	at javax.swing.plaf.basic.DefaultMenuLayout.preferredLayoutSize(DefaultMenuLayout.java:60)
	at javax.swing.plaf.synth.SynthMenuLayout.preferredLayoutSize(SynthMenuLayout.java:51)
	at java.awt.Container.preferredSize(Container.java:1794)
	at java.awt.Container.getPreferredSize(Container.java:1778)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at javax.swing.JMenu.getPopupMenuOrigin(JMenu.java:377)
	at javax.swing.JMenu.setPopupMenuVisible(JMenu.java:343)
	at javax.swing.JPopupMenu.menuSelectionChanged(JPopupMenu.java:1478)
	at javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:125)
	at javax.swing.plaf.basic.BasicMenuUI.appendPath(BasicMenuUI.java:222)
	at javax.swing.plaf.basic.BasicMenuUI.access$200(BasicMenuUI.java:49)
	at javax.swing.plaf.basic.BasicMenuUI$Handler.mousePressed(BasicMenuUI.java:461)
	at java.awt.Component.processMouseEvent(Component.java:6522)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4530)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
And if @benfry could help me when importing the code of Processing in Eclipse i am getting error in the ThinkDifferent.java, more specifically it is not able to find the com.apple.* libs. This error can cause some unexpected behavior while developing. As a fix i added the AppleJavaExtensions,jar to the class path but even this doesn't contain the `com.apple.eawt.AppEvent.*` package. Any help would be much appreciated

**Comment by alignedleft** [comment]
FWIW, @Akarshit reports this error is occuring in 3.0a9 (processing 235 - 3.0a9).

**Comment by Manindra29** [comment]
Which version of Linux was this observed on? I couldn't reproduce this on Ubuntu 14.04 (JDK 1.8u45), latest master.

**Comment by Akarshit** [comment]
I am not sure about this issue, it stopped happening automatically.
It might have been there because of some unclean state i guess because i even observed it in 2.2.1 on my system, but everything is working fine now so i think it would be safe to close this
