### ISSUE TITLE
signer information errors in org.eclipse.jdt classes

### ISSUE THREAD

**Issue by joelmoniz** [processing/processing#3325]
A sketch with only a setup() method in it does not seem to be displaying properly. The sketch used is:

```
void setup() {
  size(320, 240);
  rect(20,20,50,50);
}
```
The sketch throws the following error stack trace repeatedly:

```
java.lang.SecurityException: class "org.eclipse.jdt.core.compiler.IScanner"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteFormatter.formatString(ASTRewriteFormatter.java:246)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteFormatter.formatNode(ASTRewriteFormatter.java:376)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteFormatter.getFormattedResult(ASTRewriteFormatter.java:187)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doTextInsert(ASTRewriteAnalyzer.java:1339)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer$ListRewriter.rewriteList(ASTRewriteAnalyzer.java:631)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer$ListRewriter.rewriteList(ASTRewriteAnalyzer.java:550)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.rewriteModifiers2(ASTRewriteAnalyzer.java:1539)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:1992)
	at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:611)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisit(ASTRewriteAnalyzer.java:405)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisitList(ASTRewriteAnalyzer.java:443)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:437)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisitUnchangedChildren(ASTRewriteAnalyzer.java:450)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:1675)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:453)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisit(ASTRewriteAnalyzer.java:405)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisitList(ASTRewriteAnalyzer.java:443)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:437)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisitUnchangedChildren(ASTRewriteAnalyzer.java:450)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:1655)
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:207)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
	at org.eclipse.jdt.core.dom.InternalASTRewrite.rewriteAST(InternalASTRewrite.java:101)
	at org.eclipse.jdt.core.dom.AST.rewrite(AST.java:3077)
	at org.eclipse.jdt.core.dom.CompilationUnit.rewrite(CompilationUnit.java:929)
	at processing.mode.java.pdex.XQPreprocessor.doYourThing(XQPreprocessor.java:96)
	at processing.mode.java.pdex.ErrorCheckerService.checkCode(ErrorCheckerService.java:513)
	at processing.mode.java.pdex.ErrorCheckerService.run(ErrorCheckerService.java:369)
	at java.lang.Thread.run(Thread.java:745)
java.lang.SecurityException: class "org.eclipse.jdt.core.compiler.IScanner"'s signer information does not match signer information of other classes in the same package
(etc.)
```
The present output with the sketch is as follows:

![image](https://cloud.githubusercontent.com/assets/4526417/7831088/4cf3807c-0464-11e5-9a0f-7d879dff5ebf.png)

However, the following sketch works fine, but still throws the above mentioned error stack trace continuously, :

```
void setup() {
  size(320, 240);
}

void draw() {
  rect(20,20,50,50);
}
```

And its output is as expected:

![image](https://cloud.githubusercontent.com/assets/4526417/7831008/7c2f0ec0-0463-11e5-9c40-8f934aa09b89.png)

**Comment by aengelke** [comment]
I think that the AST exception is another issue. The setup issue is likely the same as #3315.

**Comment by benfry** [comment]
@joelmoniz That looks like you have Eclipse JARs somewhere in your CLASSPATH (or you're using a bad mode) that are conflicting. 

The other part is indeed #3315.

**Comment by joelmoniz** [comment]
Thank you. Indeed, there was something wrong with the JAR files somewhere, and an `ant clean` followed by a fresh build fixed the `java.lang.SecurityException`. I've added the rest of the information to #3315 in [this](https://github.com/processing/processing/issues/3315#issuecomment-107357495) comment before closing this issue.
