### ISSUE TITLE
Exceptions thrown when AndroidMode is added

### ISSUE THREAD

**Issue by mmayo888** [processing/processing#3386]
Platform: Mac OS X 10.10.3
Processing version: latest build from github 

If I choose "Add Mode..." and select "Android Mode 3.0.1" from the menu, the AndroidMode files download but they fail to install. Instead, the following exception is thrown:
````
java.lang.NoClassDefFoundError: processing/mode/java/JavaMode
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at processing.app.contrib.ModeContribution.<init>(ModeContribution.java:79)
	at processing.app.contrib.ModeContribution.load(ModeContribution.java:46)
	at processing.app.contrib.ModeContribution.load(ModeContribution.java:39)
	at processing.app.contrib.ContributionType.load(ContributionType.java:198)
	at processing.app.contrib.AvailableContribution.install(AvailableContribution.java:153)
	at processing.app.contrib.ContributionManager$1.run(ContributionManager.java:152)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: processing.mode.java.JavaMode
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
````
If anyone has a solution for this problem, that would be great thanks
Mike

**Comment by mmayo888** [comment]
apologies this is a duplicate of:
https://github.com/processing/processing-android/issues/108

Mike

**Comment by benfry** [comment]
It's actually [this one](https://github.com/processing/processing/issues/3080), but thanks for the report. I've changed things up so that we can get better error messages about what's going on here.
