### ISSUE TITLE
PDE not opening with latest build

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#3439]
Getting
```
java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at processing.app.ui.Editor.<init>(Editor.java:159)
	at processing.mode.java.JavaEditor.<init>(JavaEditor.java:106)
	at processing.mode.java.JavaMode.createEditor(JavaMode.java:44)
	at processing.app.Base.handleOpen(Base.java:829)
	at processing.app.Base.handleOpen(Base.java:780)
	at processing.app.Base.handleNew(Base.java:659)
	at processing.app.Base.<init>(Base.java:425)
	at processing.app.Base.createAndShowGUI(Base.java:225)
	at processing.app.Base.access$0(Base.java:165)
	at processing.app.Base$1.run(Base.java:154)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at processing.app.Preferences.getInteger(Preferences.java:316)
	at processing.app.ui.Toolkit.<clinit>(Toolkit.java:93)
```

**Comment by omerjerk** [comment]
I'm also getting this error.
This is hindering my work on the android mode. Please fix it asap.
Thanks.

**Comment by benfry** [comment]
Now fixed.

@omerjerk demanding that I fix “asap” is a little too much.

**Comment by omerjerk** [comment]
I myself tried to fix it but couldn't figure out the problem.

**Comment by Akarshit** [comment]
@benfry 
Haha +1 to you, couldn't stop myself from commenting.
