### ISSUE TITLE
Current version of Android Mode not compatible with Processing 2.2.1

### ISSUE THREAD

**Issue by sci4me** [processing/processing#3466]
I am using Processing 2.2.1 and I am trying to install the Android Mode. At the bottom of the mode manager, it says "Error during download and install." in red. Here is the stacktrace: 

```
java.lang.NoClassDefFoundError: processing/app/ui/Editor
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.getConstructor(Unknown Source)
	at processing.app.contrib.ModeContribution.<init>(ModeContribution.java:78)
	at processing.app.contrib.ModeContribution.load(ModeContribution.java:44)
	at processing.app.contrib.ModeContribution.load(ModeContribution.java:37)
	at processing.app.contrib.ContributionType.load(ContributionType.java:183)
	at processing.app.contrib.AvailableContribution.install(AvailableContribution.java:125)
	at processing.app.contrib.ContributionManager$1.run(ContributionManager.java:128)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: processing.app.ui.Editor
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 11 more
java.lang.NullPointerException
	at processing.app.contrib.AvailableContribution.install(AvailableContribution.java:128)
	at processing.app.contrib.ContributionManager$1.run(ContributionManager.java:128)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by codeanticode** [comment]
What version of the android mode did you try to install?

The latest version of the mode that would work with 2.2.1 is [232](https://github.com/processing/processing-android/releases/tag/android-232), which you can download manually and unzip inside your sketchbook/modes folder.

@prisonerjohn the mode manager in 2.2.1 simply tries to download the latest available mode, even though if it is not compatible with it, right?

**Comment by benfry** [comment]
Yes, it'll use the latest version—the thing to do would be to have a different link if you were maintaining the 2.x version. But 3.0 alpha 11 has been posted, so let's get Android Mode updated (again) for 3 and have folks move to that. (Let's not waste time we don't have updating the 2.x version.)

**Comment by sci4me** [comment]
It seems that the version I was trying to get was 238. Sure enough, 232 works a treat.

**Comment by codeanticode** [comment]
@sci4me great, thanks for let us know

@benfry Of course, I agree with not updating the 2.x version. Perhaps we can simply add a note somewhere in the processing-android wiki saying that users wishing to use the android mode on 2.x should manually download and install 232. The [latest mode available](https://github.com/processing/processing-android/releases/tag/latest) is the one for 3.0 alpha 11
