### ISSUE TITLE
Welcome screen does not display when building from latest source on Windows

### ISSUE THREAD

**Issue by joelmoniz** [processing/processing#3474]
When building on latest source, the Welcome screen does not display. However, an exception is thrown with the following stack trace:

```
Could not createInput() for C:\Users\Joel\Documents\Code\p5\processing\build\windows\work\..\..\..\..\..\shared\lib\welcome\sketchbook.html
java.io.FileNotFoundException: C:\Users\Joel\Documents\Code\p5\processing\build\windows\work\..\..\..\..\..\shared\lib\welcome\sketchbook.html (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at processing.core.PApplet.createInput(PApplet.java:6804)
	at processing.core.PApplet.loadStrings(PApplet.java:6898)
	at processing.app.ui.WebFrame.<init>(WebFrame.java:46)
	at processing.app.ui.Welcome.<init>(Welcome.java:39)
	at processing.app.Base$2.run(Base.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at processing.core.PApplet.join(PApplet.java:8409)
	at processing.app.ui.WebFrame.<init>(WebFrame.java:47)
	at processing.app.ui.Welcome.<init>(Welcome.java:39)
	at processing.app.Base$2.run(Base.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

OS: Windows 8.1

**Comment by benfry** [comment]
Have you done an `ant clean`?

**Comment by benfry** [comment]
Oh, crap—that's a debug problem. !@#$
