### ISSUE TITLE
Could not createInput() for ... sketchbook.html

### ISSUE THREAD

**Issue by Corrado972** [processing/processing#3488]
Hello,
when I run Processing v3.0a11 under Windows 7 64 bit, before load a sketch, the following error appear:

Could not createInput() for C:\Program Files\processing-3.0a11\..\..\..\..\..\shared\lib\welcome\sketchbook.html
java.io.FileNotFoundException: C:\Program Files\processing-3.0a11\..\..\..\..\..\shared\lib\welcome\sketchbook.html (Impossibile trovare il percorso specificato)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at processing.core.PApplet.createInput(PApplet.java:6804)
	at processing.core.PApplet.loadStrings(PApplet.java:6898)
...
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at processing.core.PApplet.join(PApplet.java:8409)
	at processing.app.ui.WebFrame.<init>(WebFrame.java:47)
	at processing.app.ui.Welcome.<init>(Welcome.java:39)

In the previous release the execution is without errors.

Bye

**Comment by benfry** [comment]
Already fixed for the next release: https://github.com/processing/processing/issues/3474
