### ISSUE TITLE
Unable to open PDE on linux

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#3490]
When i try to run Processing, first i get a error message saying that java mode is not compatible and needs to be updated, then another message that it is unable to switch modes hence needs to be closed. Here is the stack trace after the second message.  
`ava.lang.NoSuchMethodError: processing.app.ui.EditorFooter.addPanel(Ljava/lang/String;Ljava/awt/Component;)V
	at processing.mode.java.JavaEditor.createFooter(JavaEditor.java:266)
	at processing.app.ui.Editor.<init>(Editor.java:263)
	at processing.mode.java.JavaEditor.<init>(JavaEditor.java:106)
	at processing.mode.java.JavaMode.createEditor(JavaMode.java:44)
	at processing.app.Base.handleOpen(Base.java:854)
	at processing.app.Base.handleOpen(Base.java:805)
	at processing.app.Base.handleNew(Base.java:684)
	at processing.app.Base.<init>(Base.java:450)
	at processing.app.Base.createAndShowGUI(Base.java:235)
	at processing.app.Base.access$0(Base.java:159)
	at processing.app.Base$1.run(Base.java:148)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by benfry** [comment]
Have you tried `ant clean`?

**Comment by Akarshit** [comment]
No, forgot that. 
It is working fine now.
