### ISSUE TITLE
PixelDensity(2) problem with P2D

### ISSUE THREAD

**Issue by radeise** [processing/processing#3568]
```processing
void setup(){

    size(500,700,P2D);
    pixelDensity(2);
}
```

>java.lang.IndexOutOfBoundsException: Required 5600000 remaining bytes in buffer, only had 2800000

:rooster: :metal:

**Comment by codeanticode** [comment]
What is the OS?

Also, could you add the entire error message that shows up in the console?

**Comment by Lachie9383** [comment]
I have the same issue, on OS X 10.10.4. Here is the console error message in full:  

java.lang.IndexOutOfBoundsException: Required 2560000 remaining bytes in buffer, only had 1280000
	at com.jogamp.common.nio.Buffers.rangeCheckBytes(Buffers.java:1056)
	at jogamp.opengl.gl4.GL4bcImpl.glTexSubImage2D(GL4bcImpl.java:29089)
	at processing.opengl.PJOGL.texSubImage2D(PJOGL.java:2043)
	at processing.opengl.PGL.copyToTexture(PGL.java:1017)
	at processing.opengl.PGraphicsOpenGL.drawPixels(PGraphicsOpenGL.java:6041)
	at processing.opengl.PGraphicsOpenGL.restoreSurfaceFromPixels(PGraphicsOpenGL.java:5964)
	at processing.opengl.PGraphicsOpenGL.setDrawDefaults(PGraphicsOpenGL.java:7111)
	at processing.opengl.PGraphicsOpenGL.beginDraw(PGraphicsOpenGL.java:2047)
	at processing.core.PApplet.handleDraw(PApplet.java:2358)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:654)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:691)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:673)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:442)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1277)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1131)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:680)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:77)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:451)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by Lachie9383** [comment]
I also get a similar error with the P3D render mode.

```
void setup() {
    size(400, 400, P3D);    
    pixelDensity(2);    
}
```

java.lang.IndexOutOfBoundsException: Required 2560000 remaining bytes in buffer, only had 1280000
	at com.jogamp.common.nio.Buffers.rangeCheckBytes(Buffers.java:1056)
	at jogamp.opengl.gl4.GL4bcImpl.glTexSubImage2D(GL4bcImpl.java:29089)
	at processing.opengl.PJOGL.texSubImage2D(PJOGL.java:2043)
	at processing.opengl.PGL.copyToTexture(PGL.java:1017)
	at processing.opengl.PGraphicsOpenGL.drawPixels(PGraphicsOpenGL.java:6041)
	at processing.opengl.PGraphicsOpenGL.restoreSurfaceFromPixels(PGraphicsOpenGL.java:5964)
	at processing.opengl.PGraphicsOpenGL.setDrawDefaults(PGraphicsOpenGL.java:7111)
	at processing.opengl.PGraphicsOpenGL.beginDraw(PGraphicsOpenGL.java:2047)
	at processing.core.PApplet.handleDraw(PApplet.java:2358)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:654)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:691)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:673)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:442)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1277)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1131)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:680)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:77)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:451)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by radeise** [comment]
Sorry, i'm on OS X 10.10. too, with the same error message.

**Comment by codeanticode** [comment]
Thanks for all the info!
Solved with https://github.com/processing/processing/commit/6b85d2581fc9873fbfc3e591c0c34d7a5a7cd7bd, beta 3 will incorporate this fix.
