### ISSUE TITLE
PDEX error in Android mode

### ISSUE THREAD

**Issue by omerjerk** [processing/processing#3581]
```
import android.view.MotionEvent;
void mouseDragged() {
 MotionEvent me = (MotionEvent) mouseEvent.getNative();
 // code here, like me.getHistorySize() and other Android-y things
}
```

Whenever I open the above sketch, I get the following error :

```
Cannot find "android.view" library. Line 1 in tab test
java.lang.NullPointerException
	at processing.mode.java.pdex.ASTGenerator.getSuggestImports(ASTGenerator.java:3309)
	at processing.mode.java.pdex.ErrorCheckerService.updateErrorTable(ErrorCheckerService.java:982)
	at processing.mode.java.pdex.ErrorCheckerService.checkCode(ErrorCheckerService.java:534)
	at processing.mode.java.pdex.ErrorCheckerService.run(ErrorCheckerService.java:332)
	at java.lang.Thread.run(Thread.java:745)

```

Any idea what does it mean ?
Is there a problem with Android mode ?

**Comment by benfry** [comment]
Yes, and this should be handled in the Android repo.

**Comment by omerjerk** [comment]
"android.view" package is bundled inside android.jar, so it is in classpath already.
Any idea what could be the reason ?

**Comment by benfry** [comment]
Again, this discussion belongs in the Android repo.
