### ISSUE TITLE
NullPointerException with some sketches that have no size() command

### ISSUE THREAD

**Issue by benfry** [processing/processing#3585]
```
java.lang.NullPointerException
	at processing.mode.java.preproc.SurfaceInfo.addStatements(SurfaceInfo.java:130)
	at processing.mode.java.preproc.PdePreprocessor.parseSketchSize(PdePreprocessor.java:432)
	at processing.mode.java.preproc.PdePreprocessor.initSketchSize(PdePreprocessor.java:206)
	at processing.mode.java.JavaBuild.preprocess(JavaBuild.java:254)
	at processing.mode.java.JavaBuild.preprocess(JavaBuild.java:193)
	at processing.mode.java.JavaBuild.build(JavaBuild.java:152)
	at processing.mode.java.JavaBuild.build(JavaBuild.java:131)
	at processing.mode.java.JavaMode.handleLaunch(JavaMode.java:154)
	at processing.mode.java.JavaMode.handleRun(JavaMode.java:131)
	at processing.mode.java.JavaEditor$35.run(JavaEditor.java:1152)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by benfry** [comment]
Fixed for 3.0 beta 4.
