### ISSUE TITLE
P2D/P3D broken after recent profile changes

### ISSUE THREAD

**Issue by codeanticode** [processing/processing#3617]
On Mac OSX 10.9.5 and building latest revision from repo, any P2D/P3D sketch fails with the following error:

```
java.lang.RuntimeException: Cannot compile vertex shader:
ERROR: 0:21: '' :  #version required and missing.
ERROR: 0:36: 'attribute' : syntax error syntax error

	at processing.core.PGraphics.showException(PGraphics.java:8068)
	at processing.opengl.PShader.compileVertexShader(PShader.java:1002)
	at processing.opengl.PShader.compile(PShader.java:933)
	at processing.opengl.PShader.init(PShader.java:906)
	at processing.opengl.PShader.getAttributeLoc(PShader.java:607)
	at processing.opengl.PShader.loadAttributes(PShader.java:1153)
	at processing.opengl.PGraphicsOpenGL.getPolyShader(PGraphicsOpenGL.java:7364)
	at processing.opengl.PGraphicsOpenGL.flushPolys(PGraphicsOpenGL.java:2951)
	at processing.opengl.PGraphicsOpenGL.flush(PGraphicsOpenGL.java:2889)
	at processing.opengl.PGraphicsOpenGL.endDraw(PGraphicsOpenGL.java:2058)
	at processing.core.PApplet.handleDraw(PApplet.java:2414)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:658)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:691)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:673)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:442)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1277)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1131)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:680)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:77)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:451)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by benfry** [comment]
Was looking at this with @JakubValtar last night, but isn't it fixed in the most current version of the source?

**Comment by codeanticode** [comment]
The shaders are preprocessed only on windows right now, I think it should be the other way around.

**Comment by JakubValtar** [comment]
Fixed in https://github.com/processing/processing/pull/3606, try to pull

**Comment by codeanticode** [comment]
Now getting:



java.lang.RuntimeException: Cannot compile vertex shader:
ERROR: 0:1: '' :  version '130' is not supported
ERROR: 0:2: '' :  #version required and missing.

	at processing.core.PGraphics.showException(PGraphics.java:8068)
	at processing.opengl.PShader.compileVertexShader(PShader.java:1002)
	at processing.opengl.PShader.compile(PShader.java:933)
	at processing.opengl.PShader.init(PShader.java:906)
	at processing.opengl.PShader.getAttributeLoc(PShader.java:607)
	at processing.opengl.PShader.loadAttributes(PShader.java:1153)
	at processing.opengl.PGraphicsOpenGL.getPolyShader(PGraphicsOpenGL.java:7364)
	at processing.opengl.PGraphicsOpenGL.flushPolys(PGraphicsOpenGL.java:2951)
	at processing.opengl.PGraphicsOpenGL.flush(PGraphicsOpenGL.java:2889)
	at processing.opengl.PGraphicsOpenGL.endDraw(PGraphicsOpenGL.java:2058)
	at processing.core.PApplet.handleDraw(PApplet.java:2414)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:658)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:691)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:673)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:442)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1277)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1131)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:680)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:77)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:451)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

The right version seems to be 150.

**Comment by JakubValtar** [comment]
Can you print for me which Context is selected?

https://github.com/JakubValtar/processing/commit/46d213ea96491d1b8b496b4658fe6f049d0dc673

**Comment by JakubValtar** [comment]
I did a small update, now I detect GLSL version and proprocess to that, so it should be able to deal with any version the graphics card decides to throw at us.

I'm gonna test it today in the office and then fill a PR. You are welcome to test on your machines.

Changes: https://github.com/JakubValtar/processing/commit/0c185124a219e9cb6257b6db090a29c18156f549
Branch: https://github.com/JakubValtar/processing/tree/remove-fixed-func

**Comment by JakubValtar** [comment]
Should be fixed, please let me know if there are any problems.
