### ISSUE TITLE
Errors in the console when switching to main tab

### ISSUE THREAD

**Issue by kasperkamperman** [processing/processing#3876]
Processing 3.0b7. OSX 10.10.5.

I noticed when switching tabs the editor throws sometimes an error in the console. I was recording a tutorial, so I put a snippet in my Dropbox so you can see what happens:
https://dl.dropboxusercontent.com/u/1147392/error-switching-tab-location.mov

It might be coincidence but look at the the location service icon in my menu bar. That suddenly pops up at the time I switch the tab (and when the error is thrown). Is there any data location send when going to the main tab?

The error:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at processing.mode.java.pdex.ASTGenerator.findDeclaration(ASTGenerator.java:2796)
	at processing.mode.java.pdex.ASTGenerator.getASTNodeAt(ASTGenerator.java:1767)
	at processing.mode.java.pdex.ASTGenerator.getLabelForASTNode(ASTGenerator.java:1616)
	at processing.mode.java.pdex.JavaTextAreaPainter.getToolTipText(JavaTextAreaPainter.java:515)
	at javax.swing.ToolTipManager$insideTimerAction.actionPerformed(ToolTipManager.java:663)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by benfry** [comment]
Nah, we have no interest in your location—we're definitely not sending location information anywhere. Just a weird coincidence, or even a threading hiccup caused by the location service kicking in. 

@JakubValtar can you take a look at the cause of this NPE?

**Comment by JakubValtar** [comment]
On it.
