### ISSUE TITLE
Exception in thread "Contribution List Downloader"

### ISSUE THREAD

**Issue by hamoid** [processing/processing#3882]
In b7, I just got this when clicking Add Library. Yesterday it was working, but this time it got stuck with the spinning circle.

```
Exception in thread "Contribution List Downloader" java.lang.IndexOutOfBoundsException: Invalid range
	at javax.swing.DefaultRowSorter.rowsInserted(DefaultRowSorter.java:864)
	at javax.swing.JTable.notifySorter(JTable.java:4270)
	at javax.swing.JTable.sortedTableChanged(JTable.java:4118)
	at javax.swing.JTable.tableChanged(JTable.java:4395)
	at javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:296)
	at javax.swing.table.AbstractTableModel.fireTableRowsInserted(AbstractTableModel.java:231)
	at javax.swing.table.DefaultTableModel.insertRow(DefaultTableModel.java:376)
	at javax.swing.table.DefaultTableModel.addRow(DefaultTableModel.java:350)
	at javax.swing.table.DefaultTableModel.addRow(DefaultTableModel.java:361)
	at processing.app.contrib.ListPanel.updatePanelOrdering(ListPanel.java:435)
	at processing.app.contrib.ListPanel.filterLibraries(ListPanel.java:515)
	at processing.app.contrib.ContributionTab.filterLibraries(ContributionTab.java:290)
	at processing.app.contrib.ContributionTab$2.itemStateChanged(ContributionTab.java:197)
	at javax.swing.JComboBox.fireItemStateChanged(JComboBox.java:1223)
	at javax.swing.JComboBox.selectedItemChanged(JComboBox.java:1280)
	at javax.swing.JComboBox.contentsChanged(JComboBox.java:1330)
	at javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:118)
	at javax.swing.DefaultComboBoxModel.setSelectedItem(DefaultComboBoxModel.java:93)
	at javax.swing.DefaultComboBoxModel.addElement(DefaultComboBoxModel.java:131)
	at javax.swing.JComboBox.addItem(JComboBox.java:716)
	at processing.app.contrib.ContributionTab.updateCategoryChooser(ContributionTab.java:275)
	at processing.app.contrib.ManagerFrame$4.finishedAction(ManagerFrame.java:383)
	at processing.app.contrib.ContribProgressBar.finished(ContribProgressBar.java:53)
	at processing.app.contrib.ContributionManager.download(ContributionManager.java:125)
	at processing.app.contrib.ContributionListing$2.run(ContributionListing.java:421)
	at java.lang.Thread.run(Thread.java:745)
```

After two minutes it was working again (server side glitch?). The Sound library refuses to show up as installed though.

**Comment by JakubValtar** [comment]
There was a threading problem which should be fixed in my PR.

I'm not sure what is happening with the sound library though.

**Comment by benfry** [comment]
Closing as fixed; @JakubValtar can you open something new for the Sound issue if you can confirm it?

**Comment by JakubValtar** [comment]
@benfry No problems with the Sound libarary on my end.
