### ISSUE TITLE
CM: WindowsLookAndFeel cannot be cast to NimbusLookAndFeel

### ISSUE THREAD

**Issue by JakubValtar** [processing/processing#3894]
Got this one today when installing TabManager tool. Also getting it when uninstalling Git Manager tool.
```
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: com.sun.java.swing.plaf.windows.WindowsLookAndFeel cannot be cast to javax.swing.plaf.nimbus.NimbusLookAndFeel
	at javax.swing.plaf.nimbus.NimbusStyle.validate(NimbusStyle.java:250)
	at javax.swing.plaf.nimbus.NimbusStyle.getValues(NimbusStyle.java:806)
	at javax.swing.plaf.nimbus.NimbusStyle.getInsets(NimbusStyle.java:485)
	at javax.swing.plaf.synth.SynthStyle.installDefaults(SynthStyle.java:913)
	at javax.swing.plaf.synth.SynthLookAndFeel.updateStyle(SynthLookAndFeel.java:265)
	at javax.swing.plaf.synth.SynthLabelUI.updateStyle(SynthLabelUI.java:69)
	at javax.swing.plaf.synth.SynthLabelUI.installDefaults(SynthLabelUI.java:64)
	at javax.swing.plaf.basic.BasicLabelUI.installUI(BasicLabelUI.java:324)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.JLabel.setUI(JLabel.java:261)
	at javax.swing.JLabel.updateUI(JLabel.java:275)
	at javax.swing.JLabel.<init>(JLabel.java:164)
	at javax.swing.JLabel.<init>(JLabel.java:235)
	at processing.app.contrib.ListPanel$ContribStatusRenderer.getTableCellRendererComponent(ListPanel.java:300)
	at javax.swing.JTable.prepareRenderer(JTable.java:5723)
	at processing.app.contrib.ListPanel$1.prepareRenderer(ListPanel.java:97)
	at javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2114)
	at javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2016)
	at javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1812)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by JakubValtar** [comment]
It looks like the TabManager constructor is setting the Nimbus L&F. I have to investigate if this is a problem on it's own, or if the problem arises from concurrent execution of TabManager constructor and our UI code (both create AWT components).

**Comment by benfry** [comment]
This is a bug in the Tool, causing Processing to break. No way should it be calling `setLookAndFeel()`.
