### ISSUE TITLE
CM: Problems with installing tools

### ISSUE THREAD

**Issue by JakubValtar** [processing/processing#3895]
I tried to install some tools today. This is how my manager looks:
![err](https://cloud.githubusercontent.com/assets/3177098/10145918/076017d6-65f4-11e5-840d-c27b4d5ac7fa.png)
Problems:
- [x] Installing SketchOutline just say "Could not find a tool in the downloaded file."
- [x] Tools which are grayed out say "&lt;version nr.&gt; installed" between install and update button
- [x] I get these in the console and they also print various ugly messages into console when I try to run them from the Tools menu.
```
"Color Selector Plus" is not compatible with this version of Processing
"GUI builder" is not compatible with this version of Processing
"Speed Tool" is not compatible with this version of Processing
"TabManager" is not compatible with this version of Processing
```
- [x] Getting this one sometimes when installing/uninstalling
```
Exception in thread "Contribution Uninstaller" java.lang.NullPointerException
	at processing.app.contrib.DetailPanel$12.cancelAction(DetailPanel.java:933)
	at processing.app.contrib.ContribProgressBar$2.run(ContribProgressBar.java:84)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
- [x] when installing or uninstalling, sometimes I get
```
Could not delete E:\Projekty\Processing3\modes\mode2519908654842808608tmp\AndroidMode\mode\AndroidMode.jar
Could not delete E:\Projekty\Processing3\modes\mode2519908654842808608tmp\AndroidMode\mode
Could not delete E:\Projekty\Processing3\modes\mode2519908654842808608tmp\AndroidMode
Could not delete E:\Projekty\Processing3\modes\mode2519908654842808608tmp\AndroidMode\mode\AndroidMode.jar
Could not delete E:\Projekty\Processing3\modes\mode2519908654842808608tmp\AndroidMode\mode
Could not delete E:\Projekty\Processing3\modes\mode2519908654842808608tmp\AndroidMode
Could not delete E:\Projekty\Processing3\modes\mode2519908654842808608tmp

```

**Comment by REAS** [comment]
I think all of the Tools should be grayed out for the 3.0 launch -- none of them are compatible. I wrote to @prisonerjohn about this earlier today. That doesn't solve all of the problems, but it's some data for you.

**Comment by JakubValtar** [comment]
I fixed what I could here (installed message, NPE).

**Comment by JakubValtar** [comment]
Looks like the contributions refresh made all Tools incompatible, which solved it for now.

As for the cache folder deleting, this looks like something we can't affect for now (@benfry?).

**Comment by benfry** [comment]
Correct re: cache folder... I think the code is set up to delete those the next time that Processing starts.

**Comment by JakubValtar** [comment]
If the file is locked Moving to bin won't work either.

How about using the system `temp` folder or make the folder hidden in the first place? I don't think a message about auto-created temp folder is useful to anybody.

That reminds me, Processing creates a new folder in `temp` every time you run a sketch and never deletes it, maybe we should start deleting them too. I also found a lot of ImageIO temporary files in my `temp`, which may be caused by ["improper shutdown of the JVM"](https://www.java.net/node/679985).

**Comment by benfry** [comment]
You can't use temp because it may be on another drive or file system. This was a problem with earlier releases. 

re: temp folders, please don't mix unrelated issues, that one is already here: https://github.com/processing/processing/issues/1896

**Comment by JakubValtar** [comment]
Let's talk about it in person.

**Comment by JakubValtar** [comment]
Temp folders are deleted on the startup, so I just suppressed the messages printed into console.

@benfry good to go?

**Comment by benfry** [comment]
All set.
