### ISSUE TITLE
.vlw font size limit (40MB)

### ISSUE THREAD

**Issue by mileu32** [processing/processing#3959]
when I tried to make new font with tool in processing, I can't create more then 40MB size of font (.vlw) file.. ( i tried to make font file including hangul(Korea language)) 

processing 3.0, OS X 10.11

//error message
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
	at processing.core.PImage.init(PImage.java:266)
	at processing.core.PImage.<init>(PImage.java:234)
	at processing.core.PFont$Glyph.<init>(PFont.java:1079)
	at processing.core.PFont.<init>(PFont.java:268)
	at processing.app.tools.CreateFont.build(CreateFont.java:354)
	at processing.app.tools.CreateFont$6.actionPerformed(CreateFont.java:261)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)

**Comment by benfry** [comment]
Change the memory setting in Preferences. This is covered here:
https://github.com/processing/processing/wiki/Troubleshooting#out-of-memory-errors-javalangoutofmemoryerror

**Comment by mileu32** [comment]
<img width="740" alt="2015-10-07 4 17 24" src="https://cloud.githubusercontent.com/assets/13388715/10331264/f45e2070-6d0e-11e5-8201-6272f7b68d2a.png">

I tried memory setting for 8192, 4096, 3072, 2048, 1024..but still I cloud'nt fix this issue

processing 3.0, OS X 10.11
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
