### ISSUE TITLE
curveVertex() does not work with FX2D renderer

### ISSUE THREAD

**Issue by zhekapol** [processing/processing#3960]
```java
void setup(){
  size(400, 400, FX2D);
}


void draw(){
  beginShape();
  curveVertex(100, 100);
  curveVertex(200, 150);
  curveVertex(300, 400);
  endShape();
}
```

```java
java.lang.NullPointerException
	at processing.core.PGraphics.curveVertex(PGraphics.java:2246)
	at processing.core.PApplet.curveVertex(PApplet.java:11270)
	at sketch_151005a.draw(sketch_151005a.java:24)
	at processing.core.PApplet.handleDraw(PApplet.java:2398)
	at processing.javafx.PSurfaceFX$1.handle(PSurfaceFX.java:75)
	at processing.javafx.PSurfaceFX$1.handle(PSurfaceFX.java:1)
	at com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(TimelineClipCore.java:226)
	at com.sun.scenario.animation.shared.TimelineClipCore.playTo(TimelineClipCore.java:184)
	at javafx.animation.Timeline.impl_playTo(Timeline.java:176)
	at javafx.animation.AnimationAccessorImpl.playTo(AnimationAccessorImpl.java:39)
	at com.sun.scenario.animation.shared.InfiniteClipEnvelope.timePulse(InfiniteClipEnvelope.java:110)
	at javafx.animation.Animation.impl_timePulse(Animation.java:1102)
	at javafx.animation.Animation$1.lambda$timePulse$26(Animation.java:186)
	at javafx.animation.Animation$1$$Lambda$98/1243101475.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.animation.Animation$1.timePulse(Animation.java:185)
	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:521)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:505)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$400(QuantumToolkit.java:334)
	at com.sun.javafx.tk.quantum.QuantumToolkit$$Lambda$56/563489136.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
handleDraw() called before finishing
Could not run the sketch (Target VM failed to initialize).
Make sure that you haven't set the maximum available memory too high.
For more information, read revisions.txt and Help → Troubleshooting.
```

**Comment by benfry** [comment]
Fixed for 3.0.1, thanks for the report.
