### ISSUE TITLE
Regressions wrt GLES2 support between b4 and b7

### ISSUE THREAD

**Issue by gohai** [processing/processing#3976]
Testing beta 7 on true GLES 2 part, I am seeing runtime exceptions in more example sketches that I haven't on beta 4. (Note: this is with a newer release of the Raspberry Pi distribution - which might or might not have touched the driver or the GPU firmware - and a more recent JOGL as well)

At least the following example now throw an exception about glReadBuffer() not being present (which is expected on GLES2) - they used to work before:

Basics/Form/Primitives3D
Demos/Graphics/LowLevelGLVboInterleaved
Demos/Graphics/LowLevelGLVboSeparate
Demos/Tests/NoBackgroundTest
Demos/Tests/SpecsTest
Topics/Shaders/Monjori
Topics/Shaders/Nebula

@JakubValtar @codeanticode Any ideas?

Will try 3.0 next.

**Comment by gohai** [comment]
Sometimes I do get a stack trace, it's always the same - as seen here coming from Demos/Tests/SpecsTest:

    java.lang.RuntimeException: GL function glReadBuffer() is not available on this hardware (or driver) Read http://wiki.processing.org/w/OpenGL_Issues for help.
	at processing.opengl.PJOGL.readBuffer(PJOGL.java:1898)
	at processing.opengl.PJOGL.initFBOLayer(PJOGL.java:298)
	at processing.opengl.PGL.createFBOLayer(PGL.java:952)
	at processing.opengl.PGL.beginRender(PGL.java:721)
	at processing.opengl.PGraphicsOpenGL.beginOnscreenDraw(PGraphicsOpenGL.java:6571)
	at processing.opengl.PGraphicsOpenGL.beginDraw(PGraphicsOpenGL.java:1550)
	at processing.core.PApplet.handleDraw(PApplet.java:2360)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:761)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1291)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1145)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by codeanticode** [comment]
we could remove the exception from PJOGL.readBuffer() and PJOGL.drawBuffer() since are common operations, @JakubValtar what do you think?

**Comment by JakubValtar** [comment]
@codeanticode This seems to be caused by forced FBO. Does Pi support FBOs?

I think solution should be not calling the function if it's not supported, not hiding the exception and leaving it broken.

**Comment by codeanticode** [comment]
I think RPi supports FBOs. What its version of GL does not support are the read/drawBuffer functions, which are used in several places in the renderer's code, such as [beginPixelsOp](https://github.com/processing/processing/blob/master/core/src/processing/opengl/PGraphicsOpenGL.java#L1760), [endPixelsOp](https://github.com/processing/processing/blob/master/core/src/processing/opengl/PGraphicsOpenGL.java#L1777), [initFBOLayer](https://github.com/processing/processing/blob/master/core/src/processing/opengl/PJOGL.java#L309), [restoreGL](https://github.com/processing/processing/blob/master/core/src/processing/opengl/PGraphicsOpenGL.java#L1685). Since you cannot change the default draw and read buffers in the RPi anyways, I guess that doing nothing when the user calls these functions should not have any effect.

**Comment by JakubValtar** [comment]
Why do we call these functions again if they have no effect? To reset if
user changed it directly through PGL?

If that's the case:
It's supported everywhere except ES2. I'd put there hasReadDrawBuffer() in
the same fashion as hasSynchronization(), query it on startup into boolean,
then use the boolean to check if we should call readBuffer() and
drawBuffer() each time.

I don't think we should have silently failing methods, you can't rely on
the outcome once you really need it to work.

**Comment by gohai** [comment]
Could glReadPixels somehow be used in lieu. This one exists on GLES2. (I really don't know anything about graphics programming, I should point out.) Thanks for looking into this!

**Comment by gohai** [comment]
This be great to have for people giving Processing on ARM a try - please remove milestone if you think otherwise!

**Comment by codeanticode** [comment]
How to you like this:

https://github.com/processing/processing/commit/ab1fd3371329ccac6fd6cd079a6f52c48acf9bd4
https://github.com/processing/processing/commit/a993804576b0afa8ccd7474a65943e5649629794

glDraw/ReadBuffer() are available on GL2+ on desktop, not on GL2 but will be on GL3:

https://www.opengl.org/sdk/docs/man/html/glDrawBuffer.xhtml
https://www.opengl.org/sdk/docs/man/html/glReadBuffer.xhtml
https://www.khronos.org/opengles/sdk/docs/man3/html/glDrawBuffers.xhtml
https://www.khronos.org/opengles/sdk/docs/man3/html/glReadBuffer.xhtml

**Comment by gohai** [comment]
Super. I'll go test this in a couple of minutes!

**Comment by JakubValtar** [comment]
Looks good @codeanticode :)

**Comment by gohai** [comment]
Now we trip over [glBlitFramebuffer](https://www.khronos.org/opengles/sdk/docs/man3/html/glBlitFramebuffer.xhtml) on GLES2.

    at processing.opengl.PJOGL.blitFramebuffer(PJOGL.java:1876)
    at processing.opengl.PJOGL.initFBOLayer(PJOGL.java:310)
    at processing.opengl.PGL.createFBOLayer(PGL.java:952)
    at processing.opengl.PGL.beginRender(PGL.java:721)
    at processing.opengl.PGraphicsOpenGL.beginOnscreenDraw(PGraphicsOpenGL.java:6573)

**Comment by codeanticode** [comment]
try this https://github.com/processing/processing/commit/9dee44e81f6bef33f3ddacea5c7df4a170dc5119

**Comment by gohai** [comment]
Now getting a GL error 0x500. First frame renders fine, but it falls apart on the second.

With JOGL debugging turned on:

    com.jogamp.opengl.GLException: Thread[main-FPSAWTAnimator#00-Timer0,5,main] glGetError() returned the following error codes after a call to glGetIntegerv(<int> 0x8D57, <java.nio.IntBuffer> java.nio.DirectIntBufferU[pos=0 lim=2 cap=2]): GL_INVALID_ENUM ( 1280 0x500), 
	at com.jogamp.opengl.DebugGLES3.writeGLError(DebugGLES3.java:8241)
	at com.jogamp.opengl.DebugGLES3.glGetIntegerv(DebugGLES3.java:3476)
	at processing.opengl.PJOGL.getIntegerv(PJOGL.java:1057)
	at processing.opengl.PGL.maxSamples(PGL.java:2211)
	at processing.opengl.PGL.createFBOLayer(PGL.java:881)
	at processing.opengl.PGL.beginRender(PGL.java:721)
	at processing.opengl.PGraphicsOpenGL.beginOnscreenDraw(PGraphicsOpenGL.java:6573)
	at processing.opengl.PGraphicsOpenGL.beginDraw(PGraphicsOpenGL.java:1552)

**Comment by codeanticode** [comment]
we shouldn't query the maximum number of samples if multisampling is not supported in the first place, see https://github.com/processing/processing/commit/9d6fc00a4cfe0bf7f9eacea8d385b6be0131cf97. Does this change solves the problem?

**Comment by gohai** [comment]
9d6fc00 fixes the regression, thanks @codeanticode!

Basics/Form/Primitives3D: display window is now all white after the first frame
Demos/Graphics/LowLevelGLVboInterleaved: works well (prints harmless glGetError 0x500 messages, will look into it)
Demos/Graphics/LowLevelGLVboSeparate: works well (glGetError 0x500)
Demos/Tests/NoBackgroundTest: works, except the background is white instead of red (as on OS X)
Demos/Tests/SpecsTest: works
Topics/Shaders/Monjori: works well
Topics/Shaders/Nebula: works

**Comment by gohai** [comment]
(think this can be closed now, will continue to track the overall 3D situation on the Pi - thanks guys)
