### ISSUE TITLE
error when I call loadPixels() after CreateGraphics(w,h) version 3.0

### ISSUE THREAD

**Issue by jacbouzada** [processing/processing#3978]
In Processing 3.0 I get an error when I call loadPixels() after CreateGraphics(w,h).

Some code like this works fine in v2.2.1.

```
PGraphics pg;
 
public void setup() {
  size(800, 600);
  pg = createGraphics(width, height); 
 
  pg.loadPixels();
  for (int i=0; i < pg.width*pg.height; i++) 
    pg.pixels[i] = i % 255;
  pg.updatePixels();
 
  background(pg);
}
```
But in version 3.0 returns me that:

```
Exception in thread "Animation Thread" java.lang.NullPointerException
    at processing.awt.PGraphicsJava2D.getRaster(PGraphicsJava2D.java:2710)
    at processing.awt.PGraphicsJava2D.loadPixels(PGraphicsJava2D.java:2734)
    at myTemplate.setup(myTemplate.java:23)
    at processing.core.PApplet.handleDraw(PApplet.java:2373)
    at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1523)
    at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)
```
I don't understand why my P3 version is calling any AWT code:  processing.awt.PGraphicsJava2D.loadPixels

Any idea?

**Comment by benfry** [comment]
You cannot do anything on a `PGraphics` outside of `beginDraw()` and `endDraw()`. 
https://processing.org/reference/createGraphics_.html
