### ISSUE TITLE
Error checker keeps silently running even when disabled in Preferences

### ISSUE THREAD

**Issue by RudnikNelson** [processing/processing#4115]
I have a large sketch project I'm working on bringing into Processing 3. PDE Files are about 1.5MB in size, not including libraries it uses, spread over 100+ pde files, for organizational purposes. 

Without even trying to run the sketch, it brings up the following error: (just upon opening the sketch in the editor)

Exception in thread "Thread-43" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:2752)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:635)
	at org.eclipse.jdt.core.dom.ASTConverter.buildBodyDeclarations(ASTConverter.java:195)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:2958)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:1374)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.convert(CompilationUnitResolver.java:292)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1209)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:809)
	at processing.mode.java.pdex.XQPreprocessor.handle(XQPreprocessor.java:78)
	at processing.mode.java.pdex.ErrorCheckerService.checkCode(ErrorCheckerService.java:413)
	at processing.mode.java.pdex.ErrorCheckerService$1.run(ErrorCheckerService.java:231)
	at java.lang.Thread.run(Thread.java:745)

I've turned off error checking, warnings, import suggestion, and code completion. Even so, this happens infrequently. Additionally, I've seen the editor freeze after doing a "Find" across tabs at other times without this warning-- it opens the tab, is operational for a moment, then freezes without unlocking after any given amount of time. Again, this is all without even attempting to run the sketch. Based on the error's reference to ErrorCheckerService, I wonder if the error checker is attempting something, even with it turned off in my settings? Seems the editor is attempting to do something--- and choking because of the amount of code. I don't see these errors with smaller sketches.

The sketch itself runs successfully when the editor doesn't freeze or present these GC overhead limit errors. 

Windows 7 HP 64Bit 
16GB Ram
3.60 GHz PRocessor

**Comment by JakubValtar** [comment]
Hi @RudnikNelson. Firstly, you should just bring your code over to Eclipse or IntelliJ IDEA, it will be much more comfortable to work with. It is not a good idea to use Processing IDE for projects of this size. Just export the app and you will get a java file which will work in any Java IDE.

Currently error checker toggle only hides errors in the interface, but it keeps running in the background, because several other features depend on it. This part of code is still in active development and I will be updating it when I have more time.

**Comment by RudnikNelson** [comment]
Thank you for the helpful suggestion about Eclipse, @JakubValtar -- it certainly is time I go through that growing pain. I appreciate learning that the errorchecker runs in the background regardless of the setting... precisely what I guessed must be going on. Many thanks for your work on the project and your quick reply.

**Comment by JakubValtar** [comment]
You are welcome! Maybe try Intellij IDEA first, it's much better than what Eclipse is offering right now. Anyway, good luck with your project.

**Comment by benfry** [comment]
Closing this since the error checker has to run because it's tied to the preprocessor.
