### ISSUE TITLE
P2D and P3D crashes. Can't load library gluegen-rt.dll

### ISSUE THREAD

**Issue by s6joui** [processing/processing#4148]
Hi! With Processing 3 on Windows 10, whenever I try to use P2D or P3D the sketch crashes.

It mentions it can't load a dll file in "C:\processing-3.0.1\natives\windows-amd64\\gluegen-rt.dll" 
I don't have a "natives" folder in my processing folder

 Here is the log:

````
Warning: Caught Exception while retrieving executable temp base directory:
java.io.IOException: Could not determine a temporary executable directory
	at com.jogamp.common.util.IOUtil.getTempDir(IOUtil.java:1287)
	at com.jogamp.common.util.cache.TempFileCache.<clinit>(TempFileCache.java:81)
	at com.jogamp.common.util.cache.TempJarCache.initSingleton(TempJarCache.java:88)
	at com.jogamp.common.os.Platform$1.run(Platform.java:309)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.common.os.Platform.<clinit>(Platform.java:287)
	at com.jogamp.nativewindow.NativeWindowFactory$2.run(NativeWindowFactory.java:183)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.nativewindow.NativeWindowFactory.<clinit>(NativeWindowFactory.java:180)
	at com.jogamp.newt.NewtFactory$1.run(NewtFactory.java:68)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.newt.NewtFactory.<clinit>(NewtFactory.java:65)
	at processing.opengl.PSurfaceJOGL.initIcons(PSurfaceJOGL.java:510)
	at processing.opengl.PSurfaceJOGL.initFrame(PSurfaceJOGL.java:129)
	at processing.core.PApplet.initSurface(PApplet.java:10379)
	at processing.core.PApplet.runSketch(PApplet.java:10266)
	at processing.core.PApplet.main(PApplet.java:10001)
java.lang.UnsatisfiedLinkError: Can't load library: C:\processing-3.0.1\natives\windows-amd64\\gluegen-rt.dll
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1825)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:624)
	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:63)
	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:106)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:487)
	at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:421)
	at com.jogamp.common.os.Platform$1.run(Platform.java:317)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.common.os.Platform.<clinit>(Platform.java:287)
	at com.jogamp.nativewindow.NativeWindowFactory$2.run(NativeWindowFactory.java:183)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.nativewindow.NativeWindowFactory.<clinit>(NativeWindowFactory.java:180)
	at com.jogamp.newt.NewtFactory$1.run(NewtFactory.java:68)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.newt.NewtFactory.<clinit>(NewtFactory.java:65)
	at processing.opengl.PSurfaceJOGL.initIcons(PSurfaceJOGL.java:510)
	at processing.opengl.PSurfaceJOGL.initFrame(PSurfaceJOGL.java:129)
A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit application.
	at processing.core.PApplet.initSurface(PApplet.java:10379)
	at processing.core.PApplet.runSketch(PApplet.java:10266)
	at processing.core.PApplet.main(PApplet.java:10001)
```
Currently I'm using FX2D as a workaround and it works. Is FX2D a good alternative to P2D?

**Comment by codeanticode** [comment]
Sounds like JOGL (the underlying OpenGL-Java bindings) is trying to create a temporary folder to unpack the dll files, but cannot create it. Do you still get the error if you move the entire Processing folder into your home directory?

**Comment by codeanticode** [comment]
@s6joui did you have a chance to try my suggestion (moving the processing folder into your home folder)?

**Comment by s6joui** [comment]
Hi, when you say home folder do you mean "C:/Users/<MyUser>/" ?
I have copied it there and it is still not working.

Thank you

**Comment by codeanticode** [comment]
Strange, did this happen with earlier versions of Processing?

**Comment by profanek** [comment]
I had the same issue. It don't exist in early version 3.0b5.
After some research in google I find this:
https://jogamp.org/bugzilla/show_bug.cgi?id=1219

For me this was the same problem with Avira, which "blocked" processing functionality.

**Comment by codeanticode** [comment]
Ok I see, thanks for keep looking into this! This is not a Processing issue then, I will go ahead and close it. But feel free to add other relevant info to this thread.
