### ISSUE TITLE
java.io.FileNotFoundException after importing library 

### ISSUE THREAD

**Issue by tjohn93** [processing/processing#4153]
I'm having a similar problem even when I drag the .jar files to the sketch. 

java.io.FileNotFoundException: /Users/macuser/libraries/voce-0.9.1/lib/voce.config.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1038)
	at edu.cmu.sphinx.util.props.SaxLoader.load(SaxLoader.java:64)
	at edu.cmu.sphinx.util.props.ConfigurationManager.loader(ConfigurationManager.java:383)

The file, "voce.config.xml" is under the 'lib' folder. Only the sketch cannot find the file. I've tried moving the voce.config.xml file to the 'libraries' folder and replacing the location in the sketch; same thing.

Here's the piece of code in the sketch where I have the problem:

void setup(){
  //the following initiates the voce library
  voce.SpeechInterface.init("libraries/voce-0.9.1/lib", true, true,"libraries/voce-0.9.1/lib/gram","digits");

**Comment by benfry** [comment]
That's a problem for the library authors, or an error in your code. Not a Processing bug.
