### ISSUE TITLE
Processing 3.0.1 tries to build with included java after it has been deleted

### ISSUE THREAD

**Issue by kk6axq** [processing/processing#4202]
I am running Ubuntu 14.04. When I run "java - version", I get this:
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) Server VM (build 24.80-b11, mixed mode)
From what I understand, this is the real java not openjdk. I downloaded processing 3.0.1 from the website, put it in my home directory and moved the fonts to my java fonts folder. Then I deleted the java folder in the processing directory. Processing starts without any errors but when I try to run a sketch, I get this error:
```
lukas@lukas-desktop:~/Desktop/Science Fair/processing-3.0.1$ ./processing-java --sketch=test --run
java.io.IOException: Cannot run program "/home/lukas/Desktop/Science Fair/processing-3.0.1/java/bin/java": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at java.lang.Runtime.exec(Runtime.java:617)
	at java.lang.Runtime.exec(Runtime.java:485)
	at processing.core.PApplet.exec(PApplet.java:3478)
	at processing.mode.java.runner.Runner$1.run(Runner.java:421)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 5 more
Exception in thread "Thread-1" java.lang.RuntimeException: Could not open /home/lukas/Desktop/Science Fair/processing-3.0.1/java/bin/java -agentlib:jdwp=transport=dt_socket,address=8294,server=y,suspend=y -Djava.library.path=:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library:/home/lukas/catkin_ws/devel/lib:/home/lukas/catkin_ws/devel/lib/i386-linux-gnu:/opt/ros/indigo/lib/i386-linux-gnu:/opt/ros/indigo/lib:/usr/java/packages/lib/i386:/lib:/usr/lib -cp /tmp/test8448203602914095085temp:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/gluegen-rt-natives-linux-amd64.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/jogl-all-natives-linux-amd64.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/jogl-all-natives-linux-i586.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/core.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/jogl-all.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/gluegen-rt-natives-macosx-universal.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/jogl-all-natives-windows-i586.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/jogl-all-natives-linux-armv6hf.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/jogl-all-natives-windows-amd64.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/gluegen-rt.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/gluegen-rt-natives-linux-armv6hf.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/gluegen-rt-natives-linux-i586.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/gluegen-rt-natives-windows-amd64.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/jogl-all-natives-macosx-universal.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/gluegen-java-src.zip:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/jogl-java-src.zip:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/gluegen-rt-natives-windows-i586.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/gluegen-rt-natives-linux-amd64.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/jogl-all-natives-linux-amd64.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/jogl-all-natives-linux-i586.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/core.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/jogl-all.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/gluegen-rt-natives-macosx-universal.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/jogl-all-natives-windows-i586.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/jogl-all-natives-linux-armv6hf.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/jogl-all-natives-windows-amd64.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/gluegen-rt.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/gluegen-rt-natives-linux-armv6hf.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/gluegen-rt-natives-linux-i586.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/gluegen-rt-natives-windows-amd64.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/jogl-all-natives-macosx-universal.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/gluegen-java-src.zip:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/jogl-java-src.zip:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/gluegen-rt-natives-windows-i586.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/lib/ant-launcher.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/lib/ant.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/lib/jna.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/lib/pde.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/core.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/gluegen-rt-natives-linux-amd64.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/gluegen-rt-natives-linux-armv6hf.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/gluegen-rt-natives-linux-i586.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/gluegen-rt-natives-macosx-universal.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/gluegen-rt-natives-windows-amd64.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/gluegen-rt-natives-windows-i586.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/gluegen-rt.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/jogl-all-natives-linux-amd64.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/jogl-all-natives-linux-armv6hf.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/jogl-all-natives-linux-i586.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/jogl-all-natives-macosx-universal.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/jogl-all-natives-windows-amd64.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/jogl-all-natives-windows-i586.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/core/library/jogl-all.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/modes/java/mode/JavaMode.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/modes/java/mode/antlr.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/modes/java/mode/classpath-explorer-1.0.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/modes/java/mode/com.ibm.icu.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/modes/java/mode/jdi.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/modes/java/mode/jdimodel.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/modes/java/mode/jdtCompilerAdapter.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/modes/java/mode/jsoup-1.7.1.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/modes/java/mode/org.eclipse.core.contenttype.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/modes/java/mode/org.eclipse.core.jobs.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/modes/java/mode/org.eclipse.core.resources.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/modes/java/mode/org.eclipse.core.runtime.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/modes/java/mode/org.eclipse.equinox.common.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/modes/java/mode/org.eclipse.equinox.preferences.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/modes/java/mode/org.eclipse.jdt.core.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/modes/java/mode/org.eclipse.osgi.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/modes/java/mode/org.eclipse.text.jar:/home/lukas/Desktop/Science Fair/processing-3.0.1/modes/java/mode/org.netbeans.swing.outline.jar -ea processing.core.PApplet --display=0 --sketch-path=/home/lukas/Desktop/Science Fair/processing-3.0.1/test test
	at processing.core.PApplet.exec(PApplet.java:3481)
	at processing.mode.java.runner.Runner$1.run(Runner.java:421)
	at java.lang.Thread.run(Thread.java:745)
```

Any idea on how to fix this?

**Comment by benfry** [comment]
Don't do that? You deleted necessary files from the download, and you're complaining that it's broken.
