### ISSUE TITLE
cam.read() ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by hype** [processing/processing#4226]
I'm working with Stefano Baldan author of IPCapture (https://github.com/singintime/ipcapture)

and when using the Axis IP Cam... if you leave it running for several hours eventually you get an... ```ArrayIndexOutOfBoundsException -1``` on ```cam.read();```

sample code :
```
void draw() {
	if (cam.isAvailable()) {
		try {
			cam.read();
		}
		catch (Exception e) {
			e.printStackTrace();
		}
		image(cam,0,0);
	}
}
```
catch output : 

```
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.checkTablesOnly(JPEGImageReader.java:378)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.gotoImage(JPEGImageReader.java:481)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readHeader(JPEGImageReader.java:602)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1059)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1039)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1352)
	at ipcapture.JavaFrameBuffer.<init>(Unknown Source)
	at ipcapture.IPCapture.read(Unknown Source)
	at IPCaptureTest.draw(IPCaptureTest.java:33)
	at processing.core.PApplet.handleDraw(PApplet.java:2399)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:731)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```
Stefano was maybe under the assumption that it was maybe a "bug in the JPEG reader of the standard library" or "a problem with the garbage collector, or maybe some data corruption in the network connection, God knows what..."

he's going to add a "try/catch around that ImageIO.read(), which simply does nothing if something bad occurs during the JPEG frame acquisition"

sent an e-mail to @shiffman who suggested reaching out to @codeanticode ... any thoughts?

**Comment by codeanticode** [comment]
Hi, I re-opened this issue in the procesing-video repo https://github.com/processing/processing/issues/4226

**Comment by hype** [comment]
cheers... thank you.
