### ISSUE TITLE
Error while running a program in Processing(built from its source code)

### ISSUE THREAD

**Issue by PARAG00991** [processing/processing#4295]
When I run a program in Processing(which I built using its source code), I'm getting the following error in the console of Processing - 
```
java.io.IOException: Cannot run program "/home/parag00991/Desktop/processing_project/processing/build/linux/work/java/bin/java": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at processing.core.PApplet.exec(PApplet.java:3478)
	at processing.mode.java.runner.Runner$1.run(Runner.java:421)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 5 more
Exception in thread "Thread-13" java.lang.RuntimeException: Could not open /home/parag00991/Desktop/processing_project/processing/build/linux/work/java/bin/java -agentlib:jdwp=transport=dt_socket,address=8731,server=y,suspend=y -Djava.library.path=:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib -cp /tmp/sketch_160213a3814927659944376332temp:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/jogl-all-natives-linux-armv6hf.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/jogl-all-natives-windows-amd64.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/jogl-all-natives-linux-amd64.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/gluegen-rt-natives-windows-amd64.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/gluegen-rt-natives-linux-amd64.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/gluegen-rt-natives-macosx-universal.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/jogl-all.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/jogl-all-natives-linux-i586.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/gluegen-rt-natives-linux-i586.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/gluegen-rt.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/jogl-all-natives-macosx-universal.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/gluegen-rt-natives-windows-i586.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/gluegen-rt-natives-linux-armv6hf.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/jogl-all-natives-windows-i586.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/core.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/jogl-all-natives-linux-armv6hf.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/jogl-all-natives-windows-amd64.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/jogl-all-natives-linux-amd64.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/gluegen-rt-natives-windows-amd64.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/gluegen-rt-natives-linux-amd64.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/gluegen-rt-natives-macosx-universal.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/jogl-all.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/jogl-all-natives-linux-i586.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/gluegen-rt-natives-linux-i586.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/gluegen-rt.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/jogl-all-natives-macosx-universal.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/gluegen-rt-natives-windows-i586.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/gluegen-rt-natives-linux-armv6hf.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/jogl-all-natives-windows-i586.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/core.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/lib/ant-launcher.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/lib/ant.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/lib/jna.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/lib/pde.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/core.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/gluegen-rt-natives-linux-amd64.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/gluegen-rt-natives-linux-armv6hf.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/gluegen-rt-natives-linux-i586.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/gluegen-rt-natives-macosx-universal.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/gluegen-rt-natives-windows-amd64.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/gluegen-rt-natives-windows-i586.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/gluegen-rt.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/jogl-all-natives-linux-amd64.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/jogl-all-natives-linux-armv6hf.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/jogl-all-natives-linux-i586.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/jogl-all-natives-macosx-universal.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/jogl-all-natives-windows-amd64.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/jogl-all-natives-windows-i586.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/core/library/jogl-all.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/modes/java/mode/JavaMode.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/modes/java/mode/antlr.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/modes/java/mode/classpath-explorer-1.0.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/modes/java/mode/com.ibm.icu.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/modes/java/mode/jdi.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/modes/java/mode/jdimodel.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/modes/java/mode/jdtCompilerAdapter.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/modes/java/mode/jsoup-1.7.1.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/modes/java/mode/org.eclipse.core.contenttype.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/modes/java/mode/org.eclipse.core.jobs.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/modes/java/mode/org.eclipse.core.resources.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/modes/java/mode/org.eclipse.core.runtime.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/modes/java/mode/org.eclipse.equinox.common.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/modes/java/mode/org.eclipse.equinox.preferences.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/modes/java/mode/org.eclipse.jdt.core.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/modes/java/mode/org.eclipse.osgi.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/modes/java/mode/org.eclipse.text.jar:/home/parag00991/Desktop/processing_project/processing/build/linux/work/modes/java/mode/org.netbeans.swing.outline.jar -ea processing.core.PApplet --editor-location=-1,27 --external --display=1 --sketch-path=/tmp/untitled3777046213028828863sketches/sketch_160213a sketch_160213a
	at processing.core.PApplet.exec(PApplet.java:3481)
	at processing.mode.java.runner.Runner$1.run(Runner.java:421)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by gohai** [comment]
Does it work when you use a (downloaded) release?

**Comment by PARAG00991** [comment]
Yes, @gohai it works when I use a (downloaded) release.

**Comment by benfry** [comment]
Looks like the JRE didn't install properly. You should remove the `work` folder and try `ant run` again. Outside of that, it's not a bug, it's something better discussed on the forum.
