### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by Chuugoku** [processing/processing#4370]
I download the processing successfully but when I use the Python mode it always shows an error:

java.lang.NullPointerException
	at jycessing.Runner.runSketchBlocking(Runner.java:303)
	at jycessing.mode.run.SketchRunner$3.run(SketchRunner.java:114)
	at java.lang.Thread.run(Unknown Source)

or 

java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
	at org.python.core.PyString.<init>(PyString.java:64)
	at org.python.core.PyString.<init>(PyString.java:70)
	at org.python.core.Py.newString(Py.java:641)
	at org.python.core.PySystemState.initRegistry(PySystemState.java:800)
	at org.python.core.PySystemState.doInitialize(PySystemState.java:1045)
	at org.python.core.PySystemState.initialize(PySystemState.java:974)
	at org.python.core.PySystemState.initialize(PySystemState.java:930)
	at org.python.core.PySystemState.initialize(PySystemState.java:925)
	at org.python.util.PythonInterpreter.initialize(PythonInterpreter.java:64)
	at jycessing.Runner.runSketchBlocking(Runner.java:300)
	at jycessing.mode.run.SketchRunner$3.run(SketchRunner.java:114)
	at java.lang.Thread.run(Unknown Source)

I am sure the code is correct because it works in other computer. 
I tried all the version but it always shows the same error.

**Comment by benfry** [comment]
Please report to the Python folks: https://github.com/jdf/processing.py/issues
