### ISSUE TITLE
InvocationTargetException when running processing-java

### ISSUE THREAD

**Issue by gohai** [processing/processing#4452]
```
DISPLAY=:0 processing-java --sketch=`pwd` --run
err is java.lang.reflect.InvocationTargetException
Exception in thread "main" java.lang.NullPointerException
	at processing.mode.java.Commander.<init>(Commander.java:263)
	at processing.mode.java.Commander.main(Commander.java:86)
```

Looking into it.

**Comment by gohai** [comment]
Actual exception is

```
java.lang.NullPointerException
	at processing.app.Mode.rebuildLibraryList(Mode.java:330)
	at processing.app.Mode.<init>(Mode.java:116)
	at processing.mode.java.JavaMode.<init>(JavaMode.java:57)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at processing.app.contrib.ModeContribution.<init>(ModeContribution.java:94)
	at processing.app.contrib.ModeContribution.load(ModeContribution.java:51)
	at processing.mode.java.Commander.<init>(Commander.java:262)
	at processing.mode.java.Commander.main(Commander.java:86)
```

Calling @JakubValtar (49823a0d8f512d68b837ddfdbbbe46bb8b794350?)

**Comment by JakubValtar** [comment]
Hm, looks like base.getEditors() returns null when there are no editors. Let me look at that.

**Comment by gohai** [comment]
`base` is null w/ `processing-java` it seems

```
        ModeContribution.load(null, Platform.getContentFile("modes/java"),
                              "processing.mode.java.JavaMode").getMode();
```

**Comment by JakubValtar** [comment]
Ah, okay. The mode is instantiated through reflection and my scanners didn't catch that.

**Comment by gohai** [comment]
Always adventures with reflection! I am currently re-spinning the arm tar-ball with the same version number..
