### ISSUE TITLE
when exporting the source file does not work in P3D with processing library

### ISSUE THREAD

**Issue by seegold123** [processing/processing#4471]
it gave me these errors

java.lang.NoClassDefFoundError: com/jogamp/opengl/GLException
	at processing.opengl.PGraphicsOpenGL.createPGL(PGraphicsOpenGL.java:653)
	at processing.opengl.PGraphicsOpenGL.<init>(PGraphicsOpenGL.java:525)
	at processing.opengl.PGraphics3D.<init>(PGraphics3D.java:35)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at processing.core.PApplet.makeGraphics(PApplet.java:2216)
	at processing.core.PApplet.createPrimaryGraphics(PApplet.java:2290)
	at processing.core.PApplet.initSurface(PApplet.java:10322)
	at processing.core.PApplet.runSketch(PApplet.java:10261)
	at processing.core.PApplet.main(PApplet.java:9996)
	at Java_applet.main(Java_applet.java:27)
Caused by: java.lang.ClassNotFoundException: com.jogamp.opengl.GLException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
java.lang.NoClassDefFoundError: com/jogamp/opengl/GLException
	at processing.opengl.PGraphicsOpenGL.createPGL(PGraphicsOpenGL.java:653)
	at processing.opengl.PGraphicsOpenGL.<init>(PGraphicsOpenGL.java:525)
	at processing.opengl.PGraphics3D.<init>(PGraphics3D.java:35)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at processing.core.PApplet.makeGraphics(PApplet.java:2216)
	at processing.core.PApplet.createPrimaryGraphics(PApplet.java:2290)
	at processing.core.PApplet.initSurface(PApplet.java:10322)
	at processing.core.PApplet.runSketch(PApplet.java:10261)
	at processing.core.PApplet.main(PApplet.java:9996)
	at Java_applet.main(Java_applet.java:27)
Caused by: java.lang.ClassNotFoundException: com.jogamp.opengl.GLException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
Exception in thread "main" java.lang.RuntimeException: com/jogamp/opengl/GLException
	at processing.core.PApplet.makeGraphics(PApplet.java:2246)
	at processing.core.PApplet.createPrimaryGraphics(PApplet.java:2290)
	at processing.core.PApplet.initSurface(PApplet.java:10322)
	at processing.core.PApplet.runSketch(PApplet.java:10261)
	at processing.core.PApplet.main(PApplet.java:9996)
	at Java_applet.main(Java_applet.java:27)

**Comment by gohai** [comment]
@seegold123 Which operating system are you running? This is Processing 3.1?

**Comment by seegold123** [comment]
i am using the newest and this is not directly in processing i am doing java with importing processing library it works in P2D but not P3D

**Comment by benfry** [comment]
Once you're outside the Processing Development Environment, you're on your own with this sort of thing. The errors you're getting have to do with setting up a Java project properly—things that we hide in the PDE, because, as you've found, they're confusing. You can use the forum to ask questions about how to do this properly.
