### ISSUE TITLE
UnsatisfiedLinkError in JavaNativeFoundation during startup on OS X

### ISSUE THREAD

**Issue by th0114nd** [processing/processing#4492]
I just tried to install Processing for the first time, and when it is opened it disappears immediately.

Console.app reports
`5/19/16 6:12:12.089 PM com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x10000020.Processing[53926]) Service exited with abnormal code: 1
`

And running the script itself is a bit more informative:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError:    /Users/tim/proc/Processing.app/Contents/PlugIns/jdk1.7.0_55.jdk/Contents/Home/jre/lib/libawt.dylib: dlopen(/Users/tim/proc/Processing.app/Contents/PlugIns/jdk1.7.0_55.jdk/Contents/Home/jre/lib/libawt.dylib, 1): Library not loaded: /System/Library/Frameworks/JavaVM.framework/Versions/A/Frameworks/JavaNativeFoundation.framework/Versions/A/JavaNativeFoundation
  Referenced from: /Users/tim/proc/Processing.app/Contents/PlugIns/jdk1.7.0_55.jdk/Contents/Home/jre/lib/libawt.dylib
  Reason: image not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1872)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:67)
	at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:47)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.loadLibraries(Toolkit.java:1646)
	at java.awt.Toolkit.<clinit>(Toolkit.java:1668)
	at java.awt.EventQueue.invokeLater(EventQueue.java:1221)
	at processing.app.Base.main(Base.java:141)
```

This was with Processing 2.2.1, but I had the same problem with 3.1 and 3.1.1. I'm on OSX 10.11.4.

Thanks

**Comment by benfry** [comment]
Should be fixed for Processing 3.2, see #4608
