### ISSUE TITLE
JRE downloader in build process crashes with NullPointerException

### ISSUE THREAD

**Issue by jdf** [processing/processing#4496]
Clean build on travis:

   https://travis-ci.org/jdf/processing.py/builds/131919028

```
jre-download:
BUILD FAILED
/home/travis/build/jdf/processing.py/processing/build/build.xml:296: The following error occurred while executing this line:
/home/travis/build/jdf/processing.py/processing/build/build.xml:242: java.lang.NullPointerException
	at Downloader.download(Downloader.java:161)
	at Downloader.execute(Downloader.java:96)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
```
etc.

**Comment by jdf** [comment]
```java
      List<String> cookies = headers.get("Set-Cookie");
      conn = (HttpURLConnection) new URL(url).openConnection();
      for (String cookie : cookies) {
```
Apparently headers.get can return null.

**Comment by gohai** [comment]
I saw this also when building for the ARM. I believe we didn't get headers because Oracle was redirecting us to a Login page instead..

**Comment by gohai** [comment]
Btw: Some time ago I [came across](https://www.digitalocean.com/community/tutorials/how-to-manually-install-oracle-java-on-a-debian-or-ubuntu-vps) a simple command to download from Oracle:

    wget --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u91-b14/jdk-8u91-linux-arm32-vfp-hflt.tar.gz

Seems to work (well, at this point in time anyway). Perhaps this could simplify the downloader somewhat?

**Comment by jdf** [comment]
I should say, because it's not obvious, that this is a show-stopper bug for Python Mode, because our continuous-build/test system (Travis) is the only QA I've got. :)

**Comment by jdf** [comment]
Thanks very much @gohai for your wget tip! I've worked around the Downloader bug in my travis configuration by downloading the appropriate JRE into build/linux and uncompressing it there. I have a green build again.

https://travis-ci.org/jdf/processing.py/builds/131989379

**Comment by jdf** [comment]
In case anyone else is curious, here's how I did it:

https://github.com/jdf/processing.py/blob/master/.travis.yml#L11

**Comment by pyy** [comment]
Thank you @jdf  @gohai . It works for me.

I met the same error under Windows 8.1 x64.


```
D:\processing\build>ant run
..........
..........
BUILD FAILED
D:\processing\build\build.xml:300: The following error occurred while executing this line:
D:\processing\build\build.xml:242: java.lang.NullPointerException
        at Downloader.download(Downloader.java:161)
        at Downloader.execute(Downloader.java:96)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:854)
        at org.apache.tools.ant.Main.startAnt(Main.java:236)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)

Total time: 2 seconds

```

**There are two ways to fix it:**

1. We can use @gohai  's pull #4511 to modify the Downloader.java file
   code is here: https://github.com/processing/processing/pull/4511/commits/9ef0d4c15ebdcb2f42cb25be246e23fcc25e2db4  

2.  Or we can download the jre file manually as @jdf did.
Go to Oracle website to download windows-x64.tar.gz file (here is jre-8u92-windows-x64.tar.gz for me), put it into./build/windows folder and rename it tgz file (here is jre-8u92.tgz).

Now, run 'ant' again to build it again.

**Comment by benfry** [comment]
Has Oracle changed their download so our script no longer works?

**Comment by benfry** [comment]
Fixed with https://github.com/processing/processing/pull/4511
