### ISSUE TITLE
NullPointerException in SketchCode.getDocumentText()

### ISSUE THREAD

**Issue by JJ-Atkinson** [processing/processing#4555]
When I run tweak mode all is well. But when I try to run normal after running tweak mode, it throws this error:

```
Exception in thread "Thread-58" java.lang.NullPointerException
	at processing.app.SketchCode.getDocumentText(SketchCode.java:228)
	at processing.app.ui.Editor.prepareRun(Editor.java:2716)
	at processing.mode.java.JavaEditor.prepareRun(JavaEditor.java:1781)
	at processing.mode.java.JavaEditor$34.run(JavaEditor.java:1095)
	at java.lang.Thread.run(Thread.java:745)
```
I'm running processing 3.1.1 on windows 10.

Please note this only happens in sketches with multiple files.

**Comment by galsasson** [comment]
Can you please provide an example sketch that produces this error?

**Comment by JJ-Atkinson** [comment]
@galsasson  Sure, here you go:

### Tab 1

```Java
void setup() {
  size(300, 300);
}

void draw() {
  otherFunc();
}
```

**Comment by JJ-Atkinson** [comment]
I went poking around in the source, and found [`JavaEditor.stopTweakMode()`](https://github.com/processing/processing/blob/0cd98fcc0288dbaceb2e949108274472c42e692d/java/src/processing/mode/java/JavaEditor.java#L2703) and [`JavaEditor.setTabContents()`](https://github.com/processing/processing/blob/0cd98fcc0288dbaceb2e949108274472c42e692d/java/src/processing/mode/java/JavaEditor.java#L1681), both of which set the document to null.

```Java
  protected void stopTweakMode(List<List<Handle>> handles) {
    tweakClient.shutdown();
    getJavaTextArea().stopTweakMode();

    // remove space from the code (before and after)
    //removeSpacesFromCode();

    // check which tabs were modified
    boolean[] tweakedTabs = getTweakedTabs(handles);
    boolean modified = anythingTrue(tweakedTabs);

    if (modified) {
      // ask to keep the values
      if (Messages.showYesNoQuestion(this, Language.text("tweak_mode"),
                                     Language.text("tweak_mode.keep_changes.line1"),
                                     Language.text("tweak_mode.keep_changes.line2")) == JOptionPane.YES_OPTION) {
        for (int i = 0; i < sketch.getCodeCount(); i++) {
          if (tweakedTabs[i]) {
            sketch.getCode(i).setModified(true);

          } else {
            // load the saved code of tabs that didn't change
            // (there might be formatting changes that should not be saved)
            sketch.getCode(i).setProgram(sketch.getCode(i).getSavedProgram());
            /* Wild Hack: set document to null so the text editor will refresh
               the program contents when the document tab is being clicked */
sketch.getCode(i).setDocument(null);
          // ...
```

```Java
  protected void setTabContents(String tabFilename, String code) {
    // remove all breakpoints of this tab
    debugger.clearBreakpoints(tabFilename);

    SketchCode currentTab = getCurrentTab();

    // set code of tab
    SketchCode tab = getTab(tabFilename);
    if (tab != null) {
      tab.setProgram(code);
      // this updates document and text area
      // TODO: does this have any negative effects? (setting the doc to null)
      tab.setDocument(null);
      // ...
```
Maybe one of thees is the culprit?

**Comment by benfry** [comment]
@JakubValtar is this a regression from the Editor/Document/Undo changes?

**Comment by JakubValtar** [comment]
@benfry Yes, this is my doing. I'll be fixing it this week.
