### ISSUE TITLE
text() throws NullPointerException when using loadFont instead of createFont and textMode(SHAPE)

### ISSUE THREAD

**Issue by D3add3d** [processing/processing#4680]
When using loadFont("ArialMT-32.vlw") instead of createFont("Arial", 32, true) and calling textMode(SHAPE) before text() it throws NPE

Processing 3.2.1
Windows 7 SP1 Ultimate 64-bit
Java 8 (1.8.0_11-b12)

**Comment by gohai** [comment]
Do you get some information as to where this NullPointerException is happening (in the Processing source code)?

**Comment by D3add3d** [comment]
No, there is no stacktrace, it just writes NullPointerException to the console and highlights the first text() call. (Also tried with text("Hello World", 5, 5); to eliminate NPEs that might have been caused by variables and such)

**Comment by D3add3d** [comment]
When I get home from school I will try wrapping the text() call in a try catch block and see if I can get a stacktrace that way

**Comment by KhaledTo** [comment]
Hi, 

I think it happens when the file for the font is missing, I hope this can help :

```
java.lang.NullPointerException
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at processing.core.PFont.<init>(PFont.java:350)
	at processing.core.PApplet.loadFont(PApplet.java:6124)
	at firstTry.setup(firstTry.java:19)
	at processing.core.PApplet.handleDraw(PApplet.java:2387)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1540)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)
```

**Comment by D3add3d** [comment]
@KhaledTo I did not have time to try the try catch block but I'm 100% sure the file is in the /data folder and as I said: it WORKS without throwing any error when I don't use the textMode(SHAPE)

**Comment by KhaledTo** [comment]
@D3add3d so that's something different, I couldn't reproduce this issue. Maybe you should post your code. 

My OS : Ubuntu 14.04.5 LTS
Processing 3.2.1
Java 8  (1.8.0_101)

**Comment by D3add3d** [comment]
@KhaledTo unfortunatelly I'm not allowed to post the code where this issue occured but I will try to reproduce it using new sketch and post that code.

**Comment by D3add3d** [comment]
Ok I managed to reproduce it using this code:
```
PFont pismo;

void setup() {
  size(1280, 720, P3D);
  pixelDensity(displayDensity());
  pismo = loadFont("ArialMT-32.vlw");
  textFont(pismo, 32);
  textSize(32);
  textAlign(CENTER, CENTER);
}

void draw() {
  textMode(SHAPE);
  try {
    text("test",5,5);
  } catch(Exception e) {
    e.printStackTrace();
  }
  noLoop();
}
```

  
The stack trace is:
```
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:281)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:250)
	at sun.awt.SunToolkit.getFontMetrics(SunToolkit.java:649)
	at sun.awt.windows.WToolkit.getFontMetrics(WToolkit.java:644)
	at processing.opengl.PJOGL.getFontMetrics(PJOGL.java:468)
	at processing.opengl.PJOGL.getFontRenderContext(PJOGL.java:476)
	at processing.opengl.PJOGL.access$2(PJOGL.java:475)
	at processing.opengl.PJOGL$FontOutline.<init>(PJOGL.java:695)
	at processing.opengl.PJOGL.createFontOutline(PJOGL.java:686)
	at processing.opengl.PJOGL.createFontOutline(PJOGL.java:1)
	at processing.opengl.PGraphicsOpenGL.textCharShapeImpl(PGraphicsOpenGL.java:3680)
	at processing.opengl.PGraphicsOpenGL.textCharImpl(PGraphicsOpenGL.java:3626)
	at processing.core.PGraphics.textLineImpl(PGraphics.java:4984)
	at processing.opengl.PGraphicsOpenGL.textLineImpl(PGraphicsOpenGL.java:3597)
	at processing.core.PGraphics.textLineAlignImpl(PGraphics.java:4974)
	at processing.core.PGraphics.text(PGraphics.java:4647)
	at processing.core.PGraphics.text(PGraphics.java:4598)
	at processing.core.PApplet.text(PApplet.java:12595)
	at sketch_161001b.draw(sketch_161001b.java:31)
	at processing.core.PApplet.handleDraw(PApplet.java:2412)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:871)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by KhaledTo** [comment]
Thank you @D3add3d,

Ok so it's my first day with prototype so i might be wrong, but I think that if you move  `textMode(SHAPE);` after `text("test",5,5);` it should work. Looks like the text object needs to be drawn before you call `textMode(SHAPE);`.
But like i said im new to prototype.

**Comment by D3add3d** [comment]
Having it after the text() call beats the purpose or it, the text would be drawn in the "MODEL" mode.

**Comment by KhaledTo** [comment]
Oh, ok thank you for this info @D3add3d.

**Comment by D3add3d** [comment]
@KhaledTo to me it seems that there are some syncing issues in Processing itself, it is using sime hash map from multiple threads and that map somehow does not exist.

**Comment by JakubValtar** [comment]
WLV fonts are bitmap fonts, they don't have shape data in them. You have to use TTF for that.

In this case, I'm not sure if we try to find the font of the same name in the system or not. In any case, we should show some reasonable error message instead of a NPE.

**Comment by benfry** [comment]
Added code to show a warning and switch back to `textMode(MODEL)` when the native font is not available (i.e. when a `.vlw` is used)
