### ISSUE TITLE
java.lang.RuntimeException: Cannot compile vertex shader

### ISSUE THREAD

**Issue by jodok8** [processing/processing#4685]
Processing 3.2.1 on Ubuntu 14.04 64 bit:

When running many of the examples, I get a java runtime exception ('Cannot compile vertex shader).

Below the output when running the 'Vertices' example from the 'Geometry' section.

==========================
libEGL warning: failed to create a pipe screen for i915
java.lang.RuntimeException: Cannot compile vertex shader:
0:1(11): error: syntax error, unexpected EOL, expecting INTCONSTANT

	at processing.core.PGraphics.showException(PGraphics.java:8199)
	at processing.opengl.PShader.compileVertexShader(PShader.java:976)
	at processing.opengl.PShader.compile(PShader.java:912)
	at processing.opengl.PShader.init(PShader.java:889)
	at processing.opengl.PShader.getAttributeLoc(PShader.java:590)
	at processing.opengl.PShader.loadAttributes(PShader.java:1113)
	at processing.opengl.PGraphicsOpenGL.getPolyShader(PGraphicsOpenGL.java:7098)
	at processing.opengl.PGraphicsOpenGL.flushPolys(PGraphicsOpenGL.java:2411)
	at processing.opengl.PGraphicsOpenGL.flush(PGraphicsOpenGL.java:2348)
	at processing.opengl.PGraphicsOpenGL.endDraw(PGraphicsOpenGL.java:1526)
	at processing.core.PApplet.handleDraw(PApplet.java:2430)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:871)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by KhaledTo** [comment]
Hi, 
Did you check that : https://github.com/processing/processing/wiki/OpenGL-Issues ? 
Maybe it's related to your graphic card / integrated graphic chipset driver. Sorry for not being able to help you more on this one.

**Comment by jodok8** [comment]
Hi Khaled

Thanks for your hint.

Perhaps the issue is related to my not fully supported version of Ubuntu (only 32-bit is fully supported) and related to OpenGL. I'm using Processing 2 for now, which works fine.
