### ISSUE TITLE
Contributions Manager connection error

### ISSUE THREAD

**Issue by jeremydouglass** [processing/processing#4718]
Starting today when attempting to install a library (Processing 3.2.1 on OS X 10.10.5):

1. open Processing, new sketch
2. Menu > Tools > Add Tool

Result:

1. a pink error message panel: "Could not connect to the Processing server. Contributions cannot be installed or updated without an Internet connection. Please verify your network connection again, then try connecting again." All my other network traffic is normal.
2. Non-installed tools unexpectedly *all* show "installed" in the panel with greyed-out buttons. They show no checkboxes, however.
3. The sketch console dumps an HTTP 500 connection error log on Contributions Manager launch:

```
    java.io.IOException: Server returned HTTP response code: 500 for URL: http://download.processing.org/contribs
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1890)
    	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1885)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1884)
    	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1457)
    	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
    	at processing.app.contrib.ContributionManager.download(ContributionManager.java:92)
    	at processing.app.contrib.ContributionListing$2.run(ContributionListing.java:424)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://download.processing.org/contribs
    	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
    	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
    	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2943)
    	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
    	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
    	at java.net.URLConnection.getContentLength(URLConnection.java:485)
    	at processing.app.contrib.ContributionManager.download(ContributionManager.java:86)
    	... 2 more
    java.io.IOException: Server returned HTTP response code: 500 for URL: http://download.processing.org/contribs
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1890)
    	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1885)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1884)
    	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1457)
    	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
    	at processing.app.contrib.ContributionManager.download(ContributionManager.java:92)
    	at processing.app.contrib.ContributionListing$2.run(ContributionListing.java:424)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://download.processing.org/contribs
    	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
    	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
    	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2943)
    	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
    	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
    	at java.net.URLConnection.getContentLength(URLConnection.java:485)
    	at processing.app.contrib.ContributionManager.download(ContributionManager.java:86)
    	... 2 more
```
    
...but that URL is web-accessible:

-  http://download.processing.org/contribs

[Linked forum thread with screenshot](https://forum.processing.org/two/discussion/18735/errors-in-pde-contributions-manager)

**Comment by alignedleft** [comment]
Thanks, @jeremydouglass. To clarify, is this repeatable? I wonder if this always happens each time you test, or if this was a one-off (perhaps due to network error or slow processing.org server and timeout).

**Comment by jeremydouglass** [comment]
It is repeatable -- I just re-checked.

Closing and reopening Processing 3.2.1 doesn't affect it -- the behavior resumes on reopening Contributions Manager.

It also doesn't behave like a network timeout -- there is no console error until selecting the Contributions Manager menu item, then the window spawns instantly then the console error and pink alert box pop up also appear instantly.

Nothing showing up in the OS system Console when triggering the error.

**Comment by alignedleft** [comment]
Thanks! @benfry cc'ing you FYI, in case this could be related to the recent website issues (though I doubt it).  I can't reproduce this, but maybe its possible to find 500 errors in the server logs somehow.

**Comment by benfry** [comment]
Can you try now?

**Comment by jeremydouglass** [comment]
Just retried (1. relaunched Processing, 2. new sketch, 3. new Contributions Manager window).

The error is gone -- no warning, no console message, no interface problems.

**Comment by alignedleft** [comment]
O @benfry @benfry what magical incantation hath you wrought?

(Thanks.)

**Comment by benfry** [comment]
Was just a bug in the script that handles the contribs… reverted to an old version and will have to come back to it later.

**Comment by Akarshit** [comment]
@benfry Is that script accessible to me?

**Comment by ashishiyer9** [comment]
@benfry That bug still exists. For Processing v3.2.1, Windows 10.

**Comment by flashmaster77** [comment]
@benfry Hello, i'm learning processing at the university in a coding class and i can't install libraries, like in the described error here. Any help is much appreciated!

**Comment by benfry** [comment]
The issue posted here has long since been resolved. If you're still having trouble: 

1. Make sure you're using the latest version of Processing
2. File a new bug that describes what's happening
