### ISSUE TITLE
proper error handling when downloading contribs listing

### ISSUE THREAD

**Issue by benfry** [processing/processing#4732]
As of 3.2.2, a 500 error (or timeout, or whatever) will just spew errors into the console. If this is running in the background, then we can avoid it or just put something semi-useful in the console. 
If it happens when loading the manager, however, we need to put useful errors out there. 
```
_ crash when the contribs script is down
java.io.IOException: Server returned HTTP response code: 500 for URL: http://download.processing.org/contribs
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at processing.app.contrib.ContributionManager.download(ContributionManager.java:92)
	at processing.app.contrib.ContributionListing$2.run(ContributionListing.java:424)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://download.processing.org/contribs
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2982)
	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
	at java.net.URLConnection.getContentLength(URLConnection.java:485)
	at processing.app.contrib.ContributionManager.download(ContributionManager.java:86)
	... 2 more
```

**Comment by Akarshit** [comment]
@benfry Is following the expected behavior:
If there is any timeout/network errors during the loading of the Contribution Manager, no stack should be printed in the console as we will already be displaying a message saying the "Network error...." and giving the `Retry` button.
If there is any timeout/network errors during the downloading of any Contribution(when it is being installed or updated), print a message to the console about the error.

**Comment by benfry** [comment]
Something like that… In the case of the 500 error (as a server error while trying to download contribs, not as a stack trace), that needs to be reported, but probably only to the console. When it's a connection timeout (because there's no internet available), that's also something to be reported, but just as a message to the console. The stack trace should show up when it's something unexpected so that we can fix it properly (or add a clearer error message explaining what happened). 

The issue is that right now, any problem—expected (no internet connection) or otherwise (500 error from server)—is being reported with a messy stack trace that looks like something serious broke. It doesn't provide useful feedback about what to do, and gives people the wrong impression about scary stuff in the console (that they can/should ignore it).
