### ISSUE TITLE
Problem with exporting an application

### ISSUE THREAD

**Issue by AleksCzech** [processing/processing#4736]
Hi,
wnen I'm trying to export an application it doesn't create an .exe file. It creates only 6 .jar files in the folder 'lib' and that's all.

**Comment by benfry** [comment]
Are there error messages (probably in red) in the console?

**Comment by AleksCzech** [comment]
BUILD FAILED
C:\Users\алекс\Desktop\processing-3.2.2\sketchbook\Life\application.windows32\launch4j-build.xml:5:
net.sf.launch4j.BuilderException: net.sf.launch4j.ExecException: Exec
failed (1):
C:\Users\алекс\Desktop\processing-3.2.3\modes\java\application\launch4j\bin\windres.exe
--preprocessor=type -J rc -O coff -F pe-i386
C:\Users\5B61~1\AppData\Local\Temp\launch4j2712752161330035819rc
C:\Users\5B61~1\AppData\Local\Temp\launch4j8337329230402461045o
at net.sf.launch4j.Builder.build(Builder.java:149)
at net.sf.launch4j.ant.Launch4jTask.execute(Launch4jTask.java:111)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at
org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
at org.apache.tools.ant.Task.perform(Task.java:348)
at org.apache.tools.ant.Target.execute(Target.java:390)
at org.apache.tools.ant.Target.performTasks(Target.java:411)
at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
at processing.mode.java.JavaBuild.buildWindowsLauncher(JavaBuild.java:1215)
at processing.mode.java.JavaBuild.exportApplication(JavaBuild.java:1086)
at processing.mode.java.JavaBuild.exportApplication(JavaBuild.java:703)
at processing.mode.java.JavaMode.handleExportApplication(JavaMode.java:248)
at
processing.mode.java.JavaEditor.exportApplicationPrompt(JavaEditor.java:943)
at
processing.mode.java.JavaEditor.handleExportApplication(JavaEditor.java:573)
at processing.mode.java.JavaEditor$3.actionPerformed(JavaEditor.java:196)
at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
at
javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
at
javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
at
javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
at java.awt.Component.processMouseEvent(Component.java:6533)
at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
at java.awt.Component.processEvent(Component.java:6298)
at java.awt.Container.processEvent(Container.java:2236)
at java.awt.Component.dispatchEventImpl(Component.java:4889)
at java.awt.Container.dispatchEventImpl(Container.java:2294)
at java.awt.Component.dispatchEvent(Component.java:4711)
at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
at java.awt.Container.dispatchEventImpl(Container.java:2280)
at java.awt.Window.dispatchEventImpl(Window.java:2746)
at java.awt.Component.dispatchEvent(Component.java:4711)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
at java.awt.EventQueue$4.run(EventQueue.java:731)
at java.awt.EventQueue$4.run(EventQueue.java:729)
at java.security.AccessController.doPrivileged(Native Method)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
at
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: net.sf.launch4j.ExecException: Exec failed (1):
C:\Users\алекс\Desktop\processing-3.2.3\modes\java\application\launch4j\bin\windres.exe
--preprocessor=type -J rc -O coff -F pe-i386
C:\Users\5B61~1\AppData\Local\Temp\launch4j2712752161330035819rc
C:\Users\5B61~1\AppData\Local\Temp\launch4j8337329230402461045o
at net.sf.launch4j.Util.exec(Util.java:156)
at net.sf.launch4j.Cmd.exec(Builder.java:215)
at net.sf.launch4j.Builder.build(Builder.java:100)
... 57 more

Total time: 1 second

I'm using Windows 10  64-bit

2016-11-08 11:58 GMT+02:00 Ben Fry <notifications@github.com>:

**Comment by benfry** [comment]
Try moving the `processing-3.2.2` directory to `C:\processing-3.2.2`. I suspect the Windows apps that do the compilation may be failing due to your account name having non-ASCII characters.

**Comment by AleksCzech** [comment]
Oh, thank you. You were right and now that works!

2016-11-08 16:27 GMT+02:00 Ben Fry <notifications@github.com>:

**Comment by benfry** [comment]
Ok, thanks for looking into it. It's related to #3543, which is a problem in the launch4j project, but I still need to figure out a way to fix it for our users.

**Comment by AleksCzech** [comment]
1)I moved processing-3.2.2 and sketchbook folders to C:\
2)I removed all non-ASCII characters from names and directories

2016-11-08 20:56 GMT+02:00 Ben Fry <notifications@github.com>:

**Comment by benfry** [comment]
Yeah—I just don't want everyone to have to do that!
