### ISSUE TITLE
Can't export from Processing

### ISSUE THREAD

**Issue by WinnerEX** [processing/processing#4778]
I get an error when choosing 'export application' from the file menu. 

WindowsXP
I have the latest java RE installed and my processing folder is in the C:\ root path.

<code>com.sun.jna.LastErrorException: GetLastError() returned 317
	at com.sun.jna.platform.win32.Kernel32Util.formatMessage(Kernel32Util.java:72)
	at com.sun.jna.platform.win32.Kernel32Util.formatMessageFromHR(Kernel32Util.java:96)
	at com.sun.jna.platform.win32.Kernel32Util.formatMessageFromLastErrorCode(Kernel32Util.java:107)
	at com.sun.jna.platform.win32.W32FileUtils.moveToTrash(W32FileUtils.java:40)
	at processing.app.Platform.deleteFile(Platform.java:373)
	at processing.app.Mode.prepareExportFolder(Mode.java:1012)
	at processing.mode.java.JavaBuild.exportApplication(JavaBuild.java:755)
	at processing.mode.java.JavaBuild.exportApplication(JavaBuild.java:703)
	at processing.mode.java.JavaMode.handleExportApplication(JavaMode.java:248)
	at processing.mode.java.JavaEditor.exportApplicationPrompt(JavaEditor.java:943)
	at processing.mode.java.JavaEditor.handleExportApplication(JavaEditor.java:573)
	at processing.mode.java.JavaEditor$3.actionPerformed(JavaEditor.java:196)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)</code>

**Comment by gohai** [comment]
@WinnerEX Windows XP isn't a [supported platform](https://github.com/processing/processing/wiki/Supported-Platforms) anymore, and will likely see no testing at all. That said, if you're sufficiently motivated you might want to try running [Processing 3.0.2](https://github.com/processing/processing/releases/tag/processing-0248-3.0.2) - this was the last one that used an earlier version of JNA (in case this is the culprit).

**Comment by WinnerEX** [comment]
Processing is buggy enough even as is that I wouldn't consider downgrading. If this error is simply because I'm on XP then that is unfortunate.

**Comment by WinnerEX** [comment]
Also should probably make mention on the Processing.org download that XP isn't actively supported even if it might run. Only had mentions of Windows 32-bit and 64-bit.

**Comment by gohai** [comment]
@WinnerEX Software you pay for is "buggy" - open source software is merely "incomplete" ;) But if you can't help triage this issue, I hope you understand that others are far less likely to take the time to look into the issue, which simply might not pertain to more recent Windows versions.

**Comment by alignedleft** [comment]
Yes, XP is no longer supported by its creator (Microsoft) and also no longer by the Processing project.

**Comment by WinnerEX** [comment]
Be sure to update the Processing.org website with that, and thanks for snarky comments and closing the issue without confirmation. Really can't even begin to imagine how Processing has been in development for only 15 years and still only mildly works when helpful folks such as you are eager to please.

**Comment by michellecabrerac** [comment]
I think that the problem is that you must to add the files in your sketch. 
In processing -> Sketch -> Add File... (And select the external files that you use like images or a TXT). I solve my problem in this way... and export the application again..  :) 

A mi me sucedía lo mismo y era porque si utilizas archivos externo, como, por ejemplos, una imagen o un txt lo tienes que añadir en tu sketch. Cuando lo añadas se crea automáticamente una carpeta que se llama data... vuelves a exportar la aplicacion y listo!

Michelle C. C.

**Comment by WinnerEX** [comment]
The problem simply was because of WinXP. I had to revert to an older version of processing that is no longer supported by the developer but was built with XP in mind. Newer versions of windows aren't useful especially Win10, so I haven't reached a point where upgrading has become necessary.

There really should be some kind of lockout in newer Processing versions to simply not launch on XP if some of the more important features don't even work with XP. Got my hopes up for no reason with submitting an error and getting shitposts in return.

If they aren't developing for XP anymore, the newer versions don't really need to run on XP anyway.

**Comment by benfry** [comment]
I've added a note to the platforms page to make it clearer that XP is not supported.
