### ISSUE TITLE
filter() does not get applied while in HDPI and P2D/P3D

### ISSUE THREAD

**Issue by gwygonik** [processing/processing#4819]
MBP Retina Mid-2015, OSX 10.11.6 (El Capitan)
Processing 3.2.3 (first noticed in earlier, updated to make sure)

Any filter that attempts to be applied to a P2D/P3D app while in HDPI -- pixelDensity(2) -- does not visually appear to work (though processing time is longer, e.g.: with a large blur)

Sample code:
```Processing
void setup() {
  size(300,300); // NOTE: no P2D/P3D here
  pixelDensity(2); // HDPI
  // black background with red stripe
  background(0);
  stroke(255,0,0);
  strokeWeight(15);
  line(0,0,width,height);
  // apply some filters to make:
  // gray blurry stripe on white background
  filter(GRAY);
  filter(INVERT);
  filter(BLUR,5);
  //
  noLoop();
}
```
<img width="300" alt="correcthdpi" src="https://cloud.githubusercontent.com/assets/2564583/21758165/c2790d92-d5ed-11e6-80bb-c5a3b94dd098.png">

When simply adding P2D or P3D to size():
```Processing
void setup() {
  size(300,300, P3D);
  pixelDensity(2);
  // black background with red stripe
  background(0);
  stroke(255,0,0);
  strokeWeight(15);
  line(0,0,width,height);
  // apply some filters to make:
  // gray blurry stripe on white background
  filter(GRAY);
  filter(INVERT);
  filter(BLUR,5);
  //
  noLoop();
}
```
results in no filters applied:
<img width="300" alt="incorrecthdpip3d" src="https://cloud.githubusercontent.com/assets/2564583/21758177/ea5d7f5a-d5ed-11e6-8753-5502f6ec6ec3.png">

However, note that with pixelDensity(1), the filters DO get applied with either P2D or P3D:
```Processing
void setup() {
  size(300,300, P3D);
  pixelDensity(1);
  // black background with red stripe
  background(0);
  stroke(255,0,0);
  strokeWeight(15);
  line(0,0,width,height);
  // apply some filters to make:
  // gray blurry stripe on white background
  filter(GRAY);
  filter(INVERT);
  filter(BLUR,5);
  //
  noLoop();
}
```
<img width="300" alt="correct" src="https://cloud.githubusercontent.com/assets/2564583/21758222/54a81ec4-d5ee-11e6-81cf-d3a56afbb048.png">

No errors get reported in either the IDE or OSX Console. Could find no reference in open issues, forums, or release notes, and no mention of issues in the docs.

**Comment by gwygonik** [comment]
Good news/bad news.

Good news: This issue appears **resolved** in version 3.3.6 (possibly earlier, just now returning to this issue). The app will now apply filters correctly with HDPI and P2D/P3D.

Bad news: the blur is significantly wider/larger in HDPI+P2D/P3D than non-HDPI+P2D/P3D, and closing the window results in a null pointer error with _either_ DPI when in P2D/P3D:

> java.lang.NullPointerException
> 	at processing.core.PApplet.dispose(PApplet.java:3718)
> 	at processing.core.PApplet.exit(PApplet.java:3665)
> 	at processing.opengl.PSurfaceJOGL$NEWTWindowListener.windowDestroyNotify(PSurfaceJOGL.java:921)
> 	at jogamp.newt.WindowImpl.consumeWindowEvent(WindowImpl.java:4389)
> 	at jogamp.newt.WindowImpl.sendWindowEvent(WindowImpl.java:4317)
> 	at jogamp.newt.WindowImpl.windowDestroyNotify(WindowImpl.java:4677)
> 

BUT - since the main issue is resolved, I will close this and search for the null pointer error and if nothing, open a new ticket.
