### ISSUE TITLE
Filenames ending with a "negative" number do not work

### ISSUE THREAD

**Issue by Jebbs** [processing/processing#4861]
I work as a grader for an intro CS class that uses Processing. The software that students use to submit their assignments will append numbers to the filename if a student resubmits their assignment, which gives me something like "assignment-1.pde" when I download it. 

When I try to run this file using the command line compiler, I get a crash with the following output:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
        at processing.app.Sketch.getCode(Sketch.java:1644)
        at processing.app.Sketch.getMainProgram(Sketch.java:1669)
        at processing.mode.java.JavaBuild.preprocess(JavaBuild.java:216)
        at processing.mode.java.JavaBuild.preprocess(JavaBuild.java:155)
        at processing.mode.java.JavaBuild.build(JavaBuild.java:122)
        at processing.mode.java.Commander.<init>(Commander.java:274)
        at processing.mode.java.Commander.main(Commander.java:86)
```

When I try to open the file with the IDE, I get an error there as well:
![processingissue](https://cloud.githubusercontent.com/assets/2173909/22406673/fb39baae-e60b-11e6-8b2f-baf539993f53.png)

I get the same error if I change the ending to "-2", so only it seems that ending in "negative" numbers breaks something. Removing the "-1" causes the error to go away given nothing else is wrong with the filename.

**Comment by benfry** [comment]
Just like the message says, it's not a valid filename. You can't use - in a sketch name. You'll need to do something like make it into an underscore.

**Comment by Jebbs** [comment]
Ok, but why couldn't it be a valid filename? That seems like a strange restriction to place on filenames.

Additionally, is there a list somewhere of what isn't allowed in a filename? The message only says that *something* is wrong, not *what* is wrong. The command line compiler doesn't give any error messages in regards to the filename being wrong, either.

**Comment by benfry** [comment]
The file name (minus its extension) has to be a valid class name in Java, since that's the class name that will be used. When you're using the GUI, it's clearer, because it will fix the sketch name if you try to name it that way.

It's a tradeoff of how long to make the error message: as you can see, it's already so long that it barely makes sense. I've made a note to try to document this better by providing a link for all the gory details. How's that sound?

**Comment by bennyty** [comment]
Hey, I just ran into this problem when using [sophacles/vim-processing](https://github.com/sophacles/vim-processing). Possible reference to #2152.

> Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
        at processing.app.Sketch.getCode(Sketch.java:1669)
        at processing.app.Sketch.getMainProgram(Sketch.java:1694)
        at processing.mode.java.JavaBuild.preprocess(JavaBuild.java:217)
        at processing.mode.java.JavaBuild.preprocess(JavaBuild.java:156)
        at processing.mode.java.JavaBuild.build(JavaBuild.java:123)
        at processing.mode.java.Commander.<init>(Commander.java:274)
        at processing.mode.java.Commander.main(Commander.java:86)
> Press ENTER or type command to continue

Since it's compiled on the command line through processing-java, can the message be propagated there as well?
