### ISSUE TITLE
Framebuffer issues on Mesa VC4 graphics

### ISSUE THREAD

**Issue by gohai** [processing/processing#4919]
Out of the P3D examples, fifteen currently fail with the open source Mesa driver for the Raspberry Pi.

The output (with Mesa debugging enabled) is always similar to this:
````
Framebuffer error (unknown error), rendering will probably not work as expected Read http://wiki.processing.org/w/OpenGL_Issues for help.
Mesa: User error: GL_INVALID_FRAMEBUFFER_OPERATION in glClear(incomplete framebuffer)
Mesa: User error: GL_INVALID_FRAMEBUFFER_OPERATION in glDrawArrays(incomplete framebuffer)
Mesa: User error: GL_INVALID_FRAMEBUFFER_OPERATION in glClear(incomplete framebuffer)
OpenGL error 1286 at bot beginDraw(): invalid framebuffer operation
Mesa: User error: GL_INVALID_FRAMEBUFFER_OPERATION in glBlitFramebuffer(incomplete draw/read buffers)
Mesa: User error: GL_INVALID_FRAMEBUFFER_OPERATION in glDrawArrays(incomplete framebuffer)
Mesa: User error: GL_INVALID_FRAMEBUFFER_OPERATION in glBlitFramebuffer(incomplete draw/read buffers)
````

This is the stack trace of the first error that occurs with the `Basics/Form/Primitives3D` example:
````
Framebuffer error (unknown error), rendering will probably not work as expected Read http://wiki.processing.org/w/OpenGL_Issues for help.
Mesa: User error: GL_INVALID_FRAMEBUFFER_OPERATION in glClear(incomplete framebuffer)
com.jogamp.opengl.GLException: Thread[main-FPSAWTAnimator#00-Timer0,5,main] glGetError() returned the following error codes after a call to glClear(<int> 0x4500): Unknown glGetError() return value: ( 1286 0x506), 
	at com.jogamp.opengl.DebugGL4bc.writeGLError(DebugGL4bc.java:31803)
	at com.jogamp.opengl.DebugGL4bc.glClear(DebugGL4bc.java:1251)
	at processing.opengl.PJOGL.clear(PJOGL.java:1823)
	at processing.opengl.PGL.createFBOLayer(PGL.java:975)
	at processing.opengl.PGL.beginRender(PGL.java:727)
	at processing.opengl.PGraphicsOpenGL.beginOnscreenDraw(PGraphicsOpenGL.java:6567)
	at processing.opengl.PGraphicsOpenGL.beginDraw(PGraphicsOpenGL.java:1452)
	at processing.core.PApplet.handleDraw(PApplet.java:2380)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:907)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
````

@codeanticode @JakubValtar Do you guys perhaps have an idea what's going on, or what I could do to try to narrow this down? (Thanks in advance!)

Here is the [output with TraceGL](https://github.com/processing/processing/files/784854/tracegl-output.txt) that shows all GL calls that happen. If you search for `Mesa: ` you'll get the places in which the user errors, noted above, are supposed to be occurring.

**Comment by JakubValtar** [comment]
@gohai It looks like for some reason FBO failed to initialize. Can you modify PGL.validateFramebuffer() and print the status?
```java
... line ~2070
    } else {
      System.err.println(status); // <- add this
      System.err.println(String.format(FRAMEBUFFER_ERROR,
                                       "unknown error"));
    }
...
```

Maybe there is not enough memory for the multisampled buffer? Can you try to run with `noSmooth()`?

**Comment by gohai** [comment]
@JakubValtar Putting `noSmooth()` in there makes the example work.

**Comment by gohai** [comment]
@JakubValtar Recovering from the error and disabling multisampling also seems to work. Still curious what's really wrong with the multisample setup. Since it's free software: I could go check the GL implementation, or bug the driver author, if you think that's appropriate at this point :)

**Comment by gohai** [comment]
So #4921 made the following examples at least run with the VC4 driver:

* Basics/Form/Primitives3D
* Demos/Tests/RedrawTest
* Topics/Shaders/BlurFilter
* Topics/Shaders/Conway
* Topics/Shaders/CustomBlend
* Topics/Shaders/Deform
* Topics/Shaders/EdgeDetect
* Topics/Shaders/EdgeFilter
* Topics/Shaders/ImageMask
* Topics/Shaders/Monjori
* Topics/Shaders/Nebula

Still I'd be curious about about what's wrong with the multisampling. Since I don't know anything about graphics programming: if I can send someone a Pi 3 in exchange for figuring this out, please let me know!

Notice: we also had to unconditionally [disable multisampling](https://github.com/processing/processing/blob/master/core/src/processing/opengl/PGraphicsOpenGL.java#L1557) on the binary-only driver for the Pi, because of errors. I also have records of some of these examples _working_ (with the Mesa driver) in August 2015, so perhaps it's just a regression that was introduced at some point between then and now.

**Comment by LegendbornersYt** [comment]
Hello I am getting this error to see
[main/INFO]: [CHAT] §eOpenGL Error§f: 1 (GL_INVALID_FRAMEBUFFER_OPERATION in glDrawArrays(incomplete framebuffer))
Mesa: User error: GL_INVALID_FRAMEBUFFER_OPERATION in glClear(incomplete framebuffer)
Mesa: User error: GL_INVALID_FRAMEBUFFER_OPERATION in glDrawArrays(incomplete framebuffer)
Mesa: User error: GL_INVALID_FRAMEBUFFER_OPERATION in glClear(incomplete framebuffer)
Mesa: User error: GL_INVALID_FRAMEBUFFER_OPERATION in glDrawArrays(incomplete framebuffer)
Mesa: User error: GL_INVALID_FRAMEBUFFER_OPERATION in glClear(incomplete framebuffer)
Mesa: User error: GL_INVALID_FRAMEBUFFER_OPERATION in glDrawArrays(incomplete framebuffer)



Someone help me to fix it
