### ISSUE TITLE
Random Framebuffer not supported error when starting sketch

### ISSUE THREAD

**Issue by JakubValtar** [processing/processing#4966]
I got this error twice this evening while launching P2D sketch in PDE, not sure how to reproduce it yet. My card supports Framebuffer objects and my code just draws a bunch of circles, no OpenGL shenanigans.

```
java.lang.RuntimeException: Framebuffer objects are not supported by this hardware (or driver) Read http://wiki.processing.org/w/OpenGL_Issues for help.
	at processing.opengl.PJOGL.init(PJOGL.java:428)
	at processing.opengl.PSurfaceJOGL$DrawListener.init(PSurfaceJOGL.java:930)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:644)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:667)
	at jogamp.opengl.GLAutoDrawableBase$1.run(GLAutoDrawableBase.java:431)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1291)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by vtuttobe** [comment]
I got the same problem on my pc (Sony VAIO with Windows 10).
Any help?

**Comment by tkomforty** [comment]
same, cant find any help

**Comment by Sibelin** [comment]
Hi, I got the same error, did you find a solution?

**Comment by Fauli** [comment]
I have the same issue when I want to start the SpoutReceiver example.
I tried upgrading my graphic drivers, but with no luck. I'm running Windows 10 on a Dell XPS 15 Laptop.
