### ISSUE TITLE
Exception in Contribution Manager

### ISSUE THREAD

**Issue by mtsio** [processing/processing#5062]
This happens with the latest version (3.3.3) in Linux64.

To reproduce:
Go to Contribution Manager
Click on Status to sort based on status
Click Install or Remove

Details of the exception:
Exception in thread "Contribution Uninstaller" java.lang.ArrayIndexOutOfBoundsException: 5 >= 1
	at java.util.Vector.elementAt(Vector.java:474)
	at javax.swing.table.DefaultTableModel.getValueAt(DefaultTableModel.java:648)
	at javax.swing.table.TableRowSorter$TableRowSorterModelWrapper.getValueAt(TableRowSorter.java:269)
	at javax.swing.DefaultRowSorter.compare(DefaultRowSorter.java:955)
	at javax.swing.DefaultRowSorter.access$100(DefaultRowSorter.java:112)
	at javax.swing.DefaultRowSorter$Row.compareTo(DefaultRowSorter.java:1376)
	at javax.swing.DefaultRowSorter$Row.compareTo(DefaultRowSorter.java:1366)
	at java.util.Arrays.binarySearch0(Arrays.java:2439)
	at java.util.Arrays.binarySearch(Arrays.java:2379)
	at javax.swing.DefaultRowSorter.insertInOrder(DefaultRowSorter.java:1000)
	at javax.swing.DefaultRowSorter.rowsInserted0(DefaultRowSorter.java:1058)
	at javax.swing.DefaultRowSorter.rowsInserted(DefaultRowSorter.java:868)
	at javax.swing.JTable.notifySorter(JTable.java:4270)
	at javax.swing.JTable.sortedTableChanged(JTable.java:4118)
	at javax.swing.JTable.tableChanged(JTable.java:4395)
	at javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:296)
	at javax.swing.table.AbstractTableModel.fireTableRowsInserted(AbstractTableModel.java:231)
	at javax.swing.table.DefaultTableModel.insertRow(DefaultTableModel.java:376)
	at javax.swing.table.DefaultTableModel.addRow(DefaultTableModel.java:350)
	at javax.swing.table.DefaultTableModel.addRow(DefaultTableModel.java:361)
	at processing.app.contrib.ListPanel.updatePanelOrdering(ListPanel.java:431)
	at processing.app.contrib.ListPanel.contributionChanged(ListPanel.java:491)
	at processing.app.contrib.ContributionListing.notifyChange(ContributionListing.java:385)
	at processing.app.contrib.ContributionListing.replaceContribution(ContributionListing.java:148)
	at processing.app.contrib.LocalContribution$2.run(LocalContribution.java:473)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by ECasielles** [comment]
This happened to me too. I just installed the latest version of Processing 3 and the Android Mode and then located SDk's path manually. Somehow I messed up and tried to reinstall and the above error occurred: 
    "Exception in thread "Contribution Uninstaller" java.lang.ArrayIndexOutOfBoundsException: 3 >= 1 [...]"
