### ISSUE TITLE
Editor sometimes freezes when overwriting selected text

### ISSUE THREAD

**Issue by JakubValtar** [processing/processing#5147]
Something bad is happening when overwriting selected text. Sometimes it takes a second or two, sometimes minutes for the editor to become responsive again.

Snapshots form jVisualVM. Here are some candidates where to start looking:

![profile](https://user-images.githubusercontent.com/3177098/27461311-ead37afa-57b8-11e7-868c-4f7c29fedb63.png)

```
"AWT-EventQueue-0" - Thread t@15
   java.lang.Thread.State: RUNNABLE
	at javax.swing.TimerQueue.addTimer(TimerQueue.java:125)
	at javax.swing.Timer.start(Timer.java:552)
	at javax.swing.Timer.restart(Timer.java:593)
	at processing.app.syntax.JEditTextArea.select(JEditTextArea.java:1279)
	at processing.app.syntax.JEditTextArea.setCaretPosition(JEditTextArea.java:1193)
	at processing.app.syntax.InputHandler$next_line.actionPerformed(InputHandler.java:783)
	at processing.app.syntax.InputHandler.executeAction(InputHandler.java:308)
	at processing.app.syntax.DefaultInputHandler.keyPressed(DefaultInputHandler.java:219)
	at processing.app.syntax.PdeInputHandler.keyPressed(PdeInputHandler.java:245)
	at processing.app.syntax.JEditTextArea.processKeyEvent(JEditTextArea.java:1889)
	at processing.mode.java.pdex.JavaTextArea.processKeyEvent(JavaTextArea.java:145)
	at java.awt.Component.processEvent(Component.java:6310)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

   Locked ownable synchronizers:
	- locked <333b26ca> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
```

and

```
"AWT-EventQueue-0" - Thread t@15
   java.lang.Thread.State: RUNNABLE
	at javax.swing.text.Utilities.getTabbedTextWidth(Utilities.java:208)
	at processing.app.syntax.JEditTextArea._offsetToX(JEditTextArea.java:668)
	at processing.app.syntax.PdeTextArea._offsetToX(PdeTextArea.java:141)
	at processing.app.syntax.JEditTextArea.scrollTo(JEditTextArea.java:565)
	at processing.app.syntax.JEditTextArea.scrollToCaret(JEditTextArea.java:530)
	at processing.app.syntax.JEditTextArea.select(JEditTextArea.java:1285)
	at processing.app.syntax.JEditTextArea.setCaretPosition(JEditTextArea.java:1193)
	at processing.app.syntax.InputHandler$next_line.actionPerformed(InputHandler.java:783)
	at processing.app.syntax.InputHandler.executeAction(InputHandler.java:308)
	at processing.app.syntax.DefaultInputHandler.keyPressed(DefaultInputHandler.java:219)
	at processing.app.syntax.PdeInputHandler.keyPressed(PdeInputHandler.java:245)
	at processing.app.syntax.JEditTextArea.processKeyEvent(JEditTextArea.java:1889)
	at processing.mode.java.pdex.JavaTextArea.processKeyEvent(JavaTextArea.java:145)
	at java.awt.Component.processEvent(Component.java:6310)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

   Locked ownable synchronizers:
	- None

```

**Comment by JakubValtar** [comment]
Might be related to #2190
