### ISSUE TITLE
Processing launch error; still not fixed after reading the trouble shooting page

### ISSUE THREAD

**Issue by XingxinMorris** [processing/processing#5197]
Processing version:3.35
System: Windows10

Error one: When I double click the processing, there comes a welcome page but the sketch board doesn't show up.

What I have tried: I deleted the 'preference.txt' file. The processing runs well. I can see the sketch on the screen. But!

Error Two: I type few lines code. Like 'size(640,480); line(13,123,231,12);'.  And then click 'RUN'. Nothing happens... When I click the 'RUN' again, the processing is broken.

What I have tried: I deleted the 'preference.txt' again to make sure the processing can run. Then I type '.\processing.exe --l4j-debug' which is said in the troubleshooting. It shows that:

error:
processing.app.SketchException: unexpected char: '\'
	at processing.mode.java.JavaBuild.preprocess(JavaBuild.java:361)
	at processing.mode.java.JavaBuild.preprocess(JavaBuild.java:155)
	at processing.mode.java.JavaBuild.build(JavaBuild.java:122)
	at processing.mode.java.JavaBuild.build(JavaBuild.java:104)
	at processing.mode.java.JavaMode.handleLaunch(JavaMode.java:122)
	at processing.mode.java.JavaEditor.lambda$0(JavaEditor.java:1097)
	at java.lang.Thread.run(Thread.java:748)

I am a novice. But I really want to learn coding especially processing. I appreciate that someone can help me out. 

Sincerely,

Xingxin

**Comment by GKFX** [comment]
That's awkward. It's not saying what the unexpected char is. What language is your computer set to? I'm wondering if it's causing some unusual characters to get into your sketch. Please could you use <kbd>Tools</kbd> → <kbd>Archive Sketch</kbd> with the problematic sketch open and attach the zip to a comment? Thank you!

**Comment by XingxinMorris** [comment]
[sketch_170728a-001.zip](https://github.com/processing/processing/files/1181802/sketch_170728a-001.zip)

The default language of my computer is Chinese.

Thank you for helping me out!

**Comment by whetfire** [comment]
Since the computer is Chinese, maybe it's a non-Ascii whitespace character? The first thing that comes to mind is the monospace space.

**Comment by XingxinMorris** [comment]
Thank you for helping me out!

Anyway... I deleted the processing3 and I installed processing2.

Everything runs well.

Regards,

Xingxin

2017-08-08 12:21 GMT+08:00 David Sun <notifications@github.com>:

**Comment by GKFX** [comment]
@XingxinMorris Unfortunately that zip file contains an empty file, so it's not much use to me.
@JakubValtar In #5152 I suggest [code that would have made this easier for the user to solve](https://github.com/processing/processing/pull/5152/files#diff-e730a18acb289661a13e75c42afeb368). I think it's going to become obsolete with the work you're doing on ANTLR, but could I suggest that you add something equivalent to the unexpected character error message that your code produces? The idea was to give the error message:
`Not expecting symbol 0x3000, which is IDEOGRAPHIC SPACE.` (Using Character.getName(), and I'm not saying that that character is what was causing the OP's issue.)
