### ISSUE TITLE
unable to connect to http://download.processing.org/contrib with Http error 407

### ISSUE THREAD

**Issue by mjayakrishna** [processing/processing#5203]
unable to connect to http://download.processing.org/contrib  as there is no provision for proxy authentication in Preferences.txt. Please add it...

**Comment by benfry** [comment]
Error message when proxy auth required:

```
java.io.IOException: Server returned HTTP response code: 407 for URL: http://download.processing.org/contribs
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at processing.app.contrib.ContributionManager.download(ContributionManager.java:103)
	at processing.app.contrib.ContributionListing$1.run(ContributionListing.java:385)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Server returned HTTP response code: 407 for URL: http://download.processing.org/contribs
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3051)
	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
	at java.net.URLConnection.getContentLength(URLConnection.java:485)
	at processing.app.contrib.ContributionManager.download(ContributionManager.java:87)
	... 2 more
```
