### ISSUE TITLE
processing-3.3.5 on Linux KDE Neon : NoClassDefFoundError processing/core/PApplet

### ISSUE THREAD

**Issue by obook** [processing/processing#5212]
Hello,
I have try to found some help about my problem on forums but unsuccessfully.
I'm very new on processing and for my fist use, processing-3.3.5-linux64.tgz was downloaded from github and extracted on my home folder. Then, when I launch ./processing or ./processing-java the error is 
$ ./processing-java 
Exception in thread "main" java.lang.NoClassDefFoundError: processing/core/PApplet
        at processing.mode.java.Commander.<init>(Commander.java:99)
        at processing.mode.java.Commander.main(Commander.java:86)
Caused by: java.lang.ClassNotFoundException: processing.core.PApplet
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 2 more
Is probably around a java environment problem.. any idea ?
Regards.

**Comment by benfry** [comment]
Best guess would be that you're not using the Oracle JDK as your default. Better handled on the forums, though—this isn't the right place to debug what's happening with your setup.
