### ISSUE TITLE
Problems expanding default memory settings. P3.3.6

### ISSUE THREAD

**Issue by x13420x** [processing/processing#5254]
## Description
Please fix memory settings feature to work for win7 machines running older versions of java....if its not compatible then warn user.

## Expected Behavior
I want to change the memory to 700mb.....but stalls 
when run on P3.3.5 works fine with no stalling.

## Current Behavior
Stalls when memory setting is changed and then program ran.  When I press stop then it says timeout while waiting for packets 55....or something like this.

## Steps to Reproduce
1.run a program using more than 256 mb of memory
2.with old ver of java P3.3.6 on win7 machine
3.

## Your Environment
Win7 32 bit .....also tried on Win7 64bit with same result.
with some older version of java.

## Possible Causes / Solutions
Maybe the new version of java? If P3.3.6 requires updated version of java then warn user about that.

**Comment by x13420x** [comment]
org.eclipse.jdi.TimeoutException: Timeout occurred while waiting for packet 55.
	at org.eclipse.jdi.internal.connect.PacketReceiveManager.getReply(PacketReceiveManager.java:187)
	at org.eclipse.jdi.internal.connect.PacketReceiveManager.getReply(PacketReceiveManager.java:198)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:192)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:227)
	at org.eclipse.jdi.internal.VirtualMachineImpl.exit(VirtualMachineImpl.java:735)
	at processing.mode.java.runner.Runner.close(Runner.java:892)
	at processing.mode.java.JavaEditor.handleStop(JavaEditor.java:1129)
	at processing.mode.java.JavaToolbar.handleStop(JavaToolbar.java:145)
	at processing.mode.java.JavaToolbar$4.actionPerformed(JavaToolbar.java:103)
	at processing.app.ui.EditorButton.mousePressed(EditorButton.java:189)
	at java.awt.Component.processMouseEvent(Component.java:6530)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Win7 recent java version but probably not the latest....this was created after stalling and pressing the stop button.

**Comment by benfry** [comment]
The only supported Java version is what's included in that particular version of Processing. We already have to support five different platforms, and several operating system versions on each, we can't support all versions of Java as well.
