### ISSUE TITLE
Cannot use image() with PGraphicsSVG

### ISSUE THREAD

**Issue by HorizonShadow** [processing/processing#5267]
## Description
Setting the output of the sketch to SVG will cause image() to throw a NullPointerException.

```
java.lang.NullPointerException
	at org.apache.batik.svggen.ImageHandlerBase64Encoder.encodeImage(Unknown Source)
	at org.apache.batik.svggen.ImageHandlerBase64Encoder.handleHREF(Unknown Source)
	at org.apache.batik.svggen.ImageHandlerBase64Encoder.handleHREF(Unknown Source)
	at org.apache.batik.svggen.DefaultImageHandler.handleImage(Unknown Source)
	at org.apache.batik.svggen.SimpleImageHandler.handleImage(Unknown Source)
	at org.apache.batik.svggen.SVGGraphics2D.drawImage(Unknown Source)
	at org.apache.batik.ext.awt.g2d.AbstractGraphics2D.drawImage(Unknown Source)
	at processing.awt.PGraphicsJava2D.imageImpl(PGraphicsJava2D.java:1613)
	at processing.core.PGraphics.image(PGraphics.java:3816)
	at processing.core.PGraphics.image(PGraphics.java:3790)
	at processing.core.PApplet.image(PApplet.java:12630)
	at svg_image.setup(svg_image.java:26)
	at processing.core.PApplet.handleDraw(PApplet.java:2412)
	at processing.core.PSurfaceNone$AnimationThread.callDraw(PSurfaceNone.java:260)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)
```

## Expected Behavior
It should draw the image to the screen.

## Current Behavior
It throws a NullPointerException

## Steps to Reproduce
1. Make a new project
2. Put "img.jpg" in the `data` folder
3. Run this:
```
import processing.svg.*;

void setup() {
  size(300, 300, PGraphicsSVG.SVG, "out.svg");
  PImage img = loadImage("img.jpg");
  image(img, 0, 0, img.width, img.height);
}
```

I think it's important to note this will also occur if you use ` beginRecord(P8gGraphicsSVG.SVG, "out.svg");`, along with `endRecord`. In this case, it also does not draw the image to the screen. 

## Your Environment
* Operating System and OS version: Windows 10 64bit
* Processing version:  Processing v 3.3.6
* Other information:

**Comment by everythingability** [comment]
I think this is the answer, but no idea how to implement it.

https://stackoverflow.com/questions/16138850/batik-svggraphics2d-nullpointerexception-when-drawing-image
