### ISSUE TITLE
error in 3D skatch

### ISSUE THREAD

**Issue by prabhu1122** [processing/processing#5385]
java.lang.RuntimeException: Framebuffer objects are not supported by this hardware (or driver) Read http://wiki.processing.org/w/OpenGL_Issues for help.
	at processing.opengl.PJOGL.init(PJOGL.java:428)
	at processing.opengl.PSurfaceJOGL$DrawListener.init(PSurfaceJOGL.java:882)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:644)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:667)
	at jogamp.opengl.GLAutoDrawableBase$1.run(GLAutoDrawableBase.java:431)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1291)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
  version 3.3.6
window 8.1

 

## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

**Comment by prabhu1122** [comment]
please help
thank you

**Comment by prabhu1122** [comment]
please help anyone

**Comment by benfry** [comment]
Please try forum.processing.org where someone can help figure out what's going on with your code.

**Comment by prabhu1122** [comment]
Thank you very much
