### ISSUE TITLE
Using Java 9 (jre-9.0.4) in Processing (3.3.7)

### ISSUE THREAD

**Issue by mmartze** [processing/processing#5457]
Hello everybody,

we are using a .jar library in our processing (3.3.7) sketch, which is based on java9. Is there a way to direkt the processing sketch to java9?

Thanks in advance, for any kind of suggestions!

This is the error:

java.lang.UnsupportedClassVersionError: #Name of Library# has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at processing.core.PApplet.runSketch(PApplet.java:10691)
	at processing.core.PApplet.main(PApplet.java:10467)
This version of Processing only supports libraries and JAR files compiled for Java 1.6 or earlier.
A library used by this sketch was compiled for Java 1.7 or later, 
and needs to be recompiled to be compatible with Java 1.6.

**Comment by benfry** [comment]
We have no plans to support Java 9, unfortunately. We may support Java 10 when it's available in September. https://github.com/processing/processing/wiki/Supported-Platforms#java-9
