### ISSUE TITLE
Encoding Issues with Strings

### ISSUE THREAD

**Issue by mimelator** [processing/processing#5478]
## Description
When using certain strings in my sketch or when using loadStrings() the encoding of those strings are not always handled properly when drawn to the screen using the text() api.

## Expected Behavior
I'm hoping that when i define a string in code or in a data file, that when displayed with text() it will appear the same on the screen.

## Current Behavior
Currently some unusually encoded strings are "munged" a bit when drawn.

## Steps to Reproduce
1. Use an unusual String: eg: String testMsg = "ಠ_ಠ";
2. Draw to the screen: text(testMsg, 0, 0);
3. You'll see this appear as "☒_☒"

## Your Environment
* Processing version: 3.3.7
* Operating System and OS version: Mac OSX 10.13.4
* Other information:

## Possible Causes / Solutions
I'm wondering if it's just due to using the standard Processing Font.  However, i haven't experimented with other fonts to know for sure.

**Comment by mimelator** [comment]
[EncodingTest.zip](https://github.com/processing/processing/files/1924288/EncodingTest.zip)

**Comment by mimelator** [comment]
Ok, it probably has to do with the current font not having a glyph for certain unicode characters.
However, in trying to use a font that supports those characters with the CreateFont tool in the processing IDE and error is thrown (see below for stack trace)

Repro Steps:
* Open Processing IDE
* Select Tools->CreateFont
* Select ArialUnicodeMS-32
* Press the Characters Button-> and select the All Characters radio button
* Press the Ok button and the exception below is thrown


Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at sun.font.PhysicalStrike.getGlyphPoint(PhysicalStrike.java:138)
	at sun.font.SunLayoutEngine.nativeLayout(Native Method)
	at sun.font.SunLayoutEngine.layout(SunLayoutEngine.java:158)
	at sun.font.GlyphLayout$EngineRecord.layout(GlyphLayout.java:685)
	at sun.font.GlyphLayout.layout(GlyphLayout.java:466)
	at sun.font.ExtendedTextSourceLabel.createGV(ExtendedTextSourceLabel.java:329)
	at sun.font.ExtendedTextSourceLabel.getGV(ExtendedTextSourceLabel.java:315)
	at sun.font.ExtendedTextSourceLabel.createLogicalBounds(ExtendedTextSourceLabel.java:225)
	at sun.font.ExtendedTextSourceLabel.getAdvance(ExtendedTextSourceLabel.java:134)
	at java.awt.font.TextLine.init(TextLine.java:281)
	at java.awt.font.TextLine.<init>(TextLine.java:129)
	at java.awt.font.TextLine.fastCreateTextLine(TextLine.java:983)
	at java.awt.font.TextLayout.fastInit(TextLayout.java:612)
	at java.awt.font.TextLayout.<init>(TextLayout.java:393)
	at sun.java2d.pipe.GlyphListPipe.drawString(GlyphListPipe.java:77)
	at sun.java2d.SunGraphics2D.drawString(SunGraphics2D.java:2928)
	at processing.core.PFont$Glyph.<init>(PFont.java:1038)
	at processing.core.PFont.<init>(PFont.java:268)
	at processing.app.tools.CreateFont.build(CreateFont.java:354)
	at processing.app.tools.CreateFont$6.actionPerformed(CreateFont.java:261)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by benfry** [comment]
Make sure you're using UTF-8 to encode your files. If you're getting gibberish, that's probably why. Once that's solved, hopefully that'll fix the crash that you're seeing, but that's happening inside Java, and is unfortunately out of our control.
