### ISSUE TITLE
java.lang.IllegalAccessException on MacOs HighSierra 10.13.4

### ISSUE THREAD

**Issue by Ehrax** [processing/processing#5497]
## Description
Hey Guys, 

im not really sure if this is the right place to post it but the registration on processing.org is currently closed. 

So i have to set up Processing for a course i do in my university. I thought its a cool Idea to use IntelliJ for it so i added the core library and started to build a small example application. I can't really get it to work because each time when i start it i get following Exception: 

```
/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/bin/java "-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=52807:/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Users/ehrax/Projects/java/processing /playground/out/production/Funky Animation:/Users/ehrax/Desktop/core.jar" UsingProcessing
java.lang.RuntimeException: java.lang.IllegalAccessException: class processing.core.PApplet cannot access a member of class UsingProcessing with modifiers ""
	at processing.core.PApplet.runSketch(PApplet.java:10697)
	at processing.core.PApplet.main(PApplet.java:10504)
	at UsingProcessing.main(UsingProcessing.java:6)
Caused by: java.lang.IllegalAccessException: class processing.core.PApplet cannot access a member of class UsingProcessing with modifiers ""
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:360)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:589)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:479)
	at processing.core.PApplet.runSketch(PApplet.java:10691)
	... 2 more
```

## Code:
```java
import processing.core.*;

class UsingProcessing extends PApplet {

    public static void main(String[] args) {
        PApplet.main("UsingProcessing", args);
    }

    @Override
    public void settings() {
        size(300, 300);
    }

    @Override
    public void setup() {
        fill(120, 50, 240);
    }

    @Override
    public void draw() {
        ellipse(width/2, height/2, second(), second());
    }
}
```

## Your Environment
* Processing version: 3.3.7
* Java version: 1.10
* Operating System and OS version: MacOs HighSierra 10.13.4
* Other information: 
  - using IntelliJ IDEA 2018.1.2

**Comment by gohai** [comment]
@Ehrax You might try getting help for this issue in the [Forum](https://forum.processing.org/].
