### ISSUE TITLE
ArrayIndexOutOfBoundsException while installing libraries

### ISSUE THREAD

**Issue by codesnippy** [processing/processing#5524]
## Description
When trying to install the libraries from within processing contribution manager I get a Error during download and install message.

## Expected Behavior
I was expecting that the libraries of "The Processing Foundation" would install without a problem.

## Current Behavior
After clicking the install button I get the message "Error during download and install of Video". This also happens when I try to install the Hardware IO and or the Sound library from The Processing Foundation

Also in the Console Ill it outputs this message:
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 46 >= 1
	at java.util.Vector.elementAt(Vector.java:474)
	at javax.swing.table.DefaultTableModel.getValueAt(DefaultTableModel.java:648)
	at javax.swing.table.TableRowSorter$TableRowSorterModelWrapper.getValueAt(TableRowSorter.java:269)
	at javax.swing.DefaultRowSorter.compare(DefaultRowSorter.java:955)
	at javax.swing.DefaultRowSorter.access$100(DefaultRowSorter.java:112)
	at javax.swing.DefaultRowSorter$Row.compareTo(DefaultRowSorter.java:1376)
	at javax.swing.DefaultRowSorter$Row.compareTo(DefaultRowSorter.java:1366)
	at java.util.Arrays.binarySearch0(Arrays.java:2439)
	at java.util.Arrays.binarySearch(Arrays.java:2379)
	at javax.swing.DefaultRowSorter.insertInOrder(DefaultRowSorter.java:1000)
	at javax.swing.DefaultRowSorter.rowsInserted0(DefaultRowSorter.java:1058)
	at javax.swing.DefaultRowSorter.rowsInserted(DefaultRowSorter.java:868)
	at javax.swing.JTable.notifySorter(JTable.java:4270)
	at javax.swing.JTable.sortedTableChanged(JTable.java:4118)
	at javax.swing.JTable.tableChanged(JTable.java:4395)
	at javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:296)
	at javax.swing.table.AbstractTableModel.fireTableRowsInserted(AbstractTableModel.java:231)
	at javax.swing.table.DefaultTableModel.insertRow(DefaultTableModel.java:376)
	at javax.swing.table.DefaultTableModel.addRow(DefaultTableModel.java:350)
	at javax.swing.table.DefaultTableModel.addRow(DefaultTableModel.java:361)
	at processing.app.contrib.ListPanel.updatePanelOrdering(ListPanel.java:431)
	at processing.app.contrib.ListPanel.contributionChanged(ListPanel.java:491)
	at processing.app.contrib.ContributionListing.notifyChange(ContributionListing.java:385)
	at processing.app.contrib.ContributionListing.replaceContribution(ContributionListing.java:148)
	at processing.app.contrib.DetailPanel.install(DetailPanel.java:751)
	at processing.app.contrib.StatusPanel$2.actionPerformed(StatusPanel.java:117)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

## Steps to Reproduce
1. Install a fresh install of Debian OS with default options (64Bit and or i386)
2. Download and install and run Processing
3. In the "Tools" Menu goto "Add Tools..." Select the "Libraries" tab and try installing the 3 libraries from The Processing Foundation.

## Your Environment
Debian 9.4 Fresh install. Tryed it with both the 64Bit and the i386 version of Debian (Default install)

* Processing version: 3.3.7
* Operating System and OS version: Debian 9.4

**Comment by codesnippy** [comment]
@gohai  Most of them work fine. Some others also seem to have the same issue.

**Comment by jeremydouglass** [comment]
@codesnippy can you be more specific, giving some examples of bohh others libraries that do work and other libraries that don't work? For others that don't, could you provide the exact error message for at least one of them? This could help narrow down possible sources of the problem.

**Comment by codesnippy** [comment]
@gohai When I installed libraries they seem to work oke when I install them from A to Z.
However. When I sort on the column "Author" Then this error seems to happen.

for example I tryed installing OCT after sorting on "Author" 
it gives the folowing error message:

Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 46 >= 1
	at java.util.Vector.elementAt(Vector.java:474)
	at javax.swing.table.DefaultTableModel.getValueAt(DefaultTableModel.java:648)
	at javax.swing.table.TableRowSorter$TableRowSorterModelWrapper.getValueAt(TableRowSorter.java:269)
	at javax.swing.DefaultRowSorter.compare(DefaultRowSorter.java:955)
	at javax.swing.DefaultRowSorter.access$100(DefaultRowSorter.java:112)
	at javax.swing.DefaultRowSorter$Row.compareTo(DefaultRowSorter.java:1376)
	at javax.swing.DefaultRowSorter$Row.compareTo(DefaultRowSorter.java:1366)
	at java.util.Arrays.binarySearch0(Arrays.java:2439)
	at java.util.Arrays.binarySearch(Arrays.java:2379)
	at javax.swing.DefaultRowSorter.insertInOrder(DefaultRowSorter.java:1000)
	at javax.swing.DefaultRowSorter.rowsInserted0(DefaultRowSorter.java:1058)
	at javax.swing.DefaultRowSorter.rowsInserted(DefaultRowSorter.java:868)
	at javax.swing.JTable.notifySorter(JTable.java:4270)
	at javax.swing.JTable.sortedTableChanged(JTable.java:4118)
	at javax.swing.JTable.tableChanged(JTable.java:4395)
	at javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:296)
	at javax.swing.table.AbstractTableModel.fireTableRowsInserted(AbstractTableModel.java:231)
	at javax.swing.table.DefaultTableModel.insertRow(DefaultTableModel.java:376)
	at javax.swing.table.DefaultTableModel.addRow(DefaultTableModel.java:350)
	at javax.swing.table.DefaultTableModel.addRow(DefaultTableModel.java:361)
	at processing.app.contrib.ListPanel.updatePanelOrdering(ListPanel.java:431)
	at processing.app.contrib.ListPanel.contributionChanged(ListPanel.java:491)
	at processing.app.contrib.ContributionListing.notifyChange(ContributionListing.java:385)
	at processing.app.contrib.ContributionListing.replaceContribution(ContributionListing.java:148)
	at processing.app.contrib.DetailPanel.install(DetailPanel.java:751)
	at processing.app.contrib.StatusPanel$2.actionPerformed(StatusPanel.java:117)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by gohai** [comment]
Here's the relevant code:

```
  // Thread: EDT
  void updatePanelOrdering(Set<Contribution> contributionsSet) {
    model.getDataVector().removeAllElements();
    int rowCount = 0;
    for (Contribution entry : contributionsSet) {
      model.addRow(new Object[]{entry, entry, entry});
      if (selectedPanel != null &&
          entry.getName().equals(selectedPanel.getContrib().getName())) {
        table.setRowSelectionInterval(rowCount, rowCount);
      }
      rowCount++;
    }
    model.fireTableDataChanged();
  }
```

Wouldn't be surprised if this turned out to be a threading issue - e.g. the contributions set gets invalidated by a download finishing while this code is running, or similar.

**Comment by benfry** [comment]
Yeah, almost certainly a threading issue.

**Comment by Sardtok** [comment]
Perhaps using a RowFilter for handling filtering, and then having the ContribTableModel be bound to the set of contributions would help. I.e. removing the need to call updatePanelOrdering, and getting rid of the visibleContributions set. This would remove the data vector removal of all items during updates. That should ensure the table model access works as intended, even with the multi-threading, which should be done very carefully with Swing.

**Comment by Sardtok** [comment]
Ok, I had a bit of a hard time testing this. As apparently there are issues with the filtering when the sorting is changed in the production version.

But installation, and filtering both work very well using a RowFilter. I have some more work to do before sending in a PR. Among other things I have not fixed the UpdateListPanel. And there are some issues with the sorting right now when the list updates after installing/uninstalling libraries.

Maybe I can spend a bit of time on this next week, and I should be able to have something done. It's quite a large change, but it always is when switching to the slightly more modern RowFilter from homemade filters.

**Comment by Sardtok** [comment]
I finally got around to fixing the update panel. It required quite a bit of work, and I had some issues with the Processing project and IntelliJ updates, so I had to work without a debugger (especially hard to handle runtime exceptions during startup). The PR is quite large, though.

**Comment by benfry** [comment]
Incorporated the PR from @Sardtok for 3.5.
