### ISSUE TITLE
can not run PApplet in DialogFragment

### ISSUE THREAD

**Issue by GENTEK05** [processing/processing#5535]
public class DialogSetTime extends DialogFragment {

    private MyPApplet myPApplet;
    private FrameLayout frameLayout;

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
          }

    @Nullable
    @Override
    public View onCreateView(@NonNull final LayoutInflater inflater, @Nullable final ViewGroup 
         container, @Nullable final Bundle savedInstanceState) {
        final View v = inflater.inflate(R.layout.diaolog, null);

                frameLayout = v.findViewById(R.id.adwafawd);
                myPApplet = new MyPApplet();

                PFragment fragment = new PFragment(myPApplet);
                fragment.setView(frameLayout, (FragmentActivity) context);

        return v;
    }

06-11 18:32:08.980 26181-26181/com.myalarm E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myalarm, PID: 26181
    java.lang.IllegalArgumentException: No view found for id 0x7f0a001b (com.myalarm:id/adwafawd) for fragment PFragment{170919fd #2 id=0x7f0a001b}
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1422)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:211)
        at android.app.ActivityThread.main(ActivityThread.java:5389)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

**Comment by gohai** [comment]
Please report Android issues here: https://github.com/processing/processing-android.git
