### ISSUE TITLE
Raspberry Pi 3b+ Processing 3.3.7.1 Raspbian (up to date) ---- P2D/P3D Error

### ISSUE THREAD

**Issue by DangusTaargus** [processing/processing#5582]
I'm configuring a series of Raspberry Pi 3 B+ units to run a bunch of works for an exhibition and the first few units got 3.3.7... the last couple I must have updated after 3.3.7.1 came out and they are behaving differently with the exact same code that relies on P2D for better performance.

Here is the error code on any sketch where I call P2D to either size or fullscreen.

> java.lang.RuntimeException: Cannot link shader program:
ERROR:PREPROCESSOR-1 (vertex shader, line 1) Preprocessor syntax error : garbage at end of preprocessor directive�
	at processing.core.PGraphics.showException(PGraphics.java:8206)
	at processing.opengl.PShader.validate(PShader.java:937)
	at processing.opengl.PShader.init(PShader.java:902)
	at processing.opengl.PShader.getAttributeLoc(PShader.java:595)
	at processing.opengl.PShader.loadAttributes(PShader.java:1123)
	at processing.opengl.PGraphicsOpenGL.getPolyShader(PGraphicsOpenGL.java:7081)
	at processing.opengl.PGraphicsOpenGL.flushPolys(PGraphicsOpenGL.java:2378)
	at processing.opengl.PGraphicsOpenGL.flush(PGraphicsOpenGL.java:2315)
	at processing.opengl.PGraphicsOpenGL.endDraw(PGraphicsOpenGL.java:1480)
	at processing.core.PApplet.handleDraw(PApplet.java:2444)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:866)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

Here's a quick sample of test code... same error as the code I intend to use.

```
void` setup(){
  size(300,300,P2D);
}

void draw(){
  background(0);
  noCursor();
  rect(mouseX,mouseY,10,10);
}
```

This seems specific to 3.3.7.1, as nothing on the internet gives me hits for this error. I can revert to 3.3.7 in the meantime, but I thought I'd report. Thanks

**Comment by gohai** [comment]
@DangusTaargus Thanks for the report. 3.3.7.1 included some band-aids for ARM Mali graphics - possible that this broke something on the Pi :( I'll look into it.

**Comment by gohai** [comment]
@DangusTaargus This should be fixed now - if you want to use 3.3.7.1, I've uploaded a build of `core.jar` that contains the fix for you: https://sukzessiv.net/~gohai/p5-arm/mali/core.jar

Thanks again for reporting.

**Comment by DangusTaargus** [comment]
Thanks, I'll test this right away.

**Comment by DangusTaargus** [comment]
Worked like a charm. Thanks so much @gohai 

I can get by patching the installation going forward until the next hotfix. Thanks! How long will it likely take to see this pulled into the main download?

**Comment by gohai** [comment]
Since a couple of bugs creeped into 3.3.7.1 I am considering releasing an updated version this Sunday - could also be that Ben is doing a "real" release soon.

**Comment by DangusTaargus** [comment]
@gohai awesome. Good to know. Thanks again, and glad I could be of some help.
