### ISSUE TITLE
NullPointerException at java.awt.Window.init(Window.java:497) when using Airplay

### ISSUE THREAD

**Issue by benfry** [processing/processing#5620]
When launching a sketch on macOS using Airplay, there's sometimes a `NullPointerException` thrown from inside Java. The cause seems to be that no windows are recognized:

```
Exception in thread "main" java.lang.NullPointerException
	at java.awt.Window.init(Window.java:497)
	at java.awt.Window.<init>(Window.java:537)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at processing.core.PApplet$6.<init>(PApplet.java:10339)
	at processing.core.PApplet.initSurface(PApplet.java:10339)
	at processing.core.PApplet.runSketch(PApplet.java:10273)
	at processing.core.PApplet.main(PApplet.java:10008)
	at Main.main(Main.java:1054)
```

Unfortunately, because it's happening inside Java, it doesn't appear to be something that we can fix. 

Though perhaps we can catch the NPE and print a message about it, since it looks like it may happen when odd display devices are plugged in as well.

**Comment by rjenkin** [comment]
I too have this issue (Processing will not start) on version 3.3.7 and 3.4 when my Mac High Sierra (10.13.3) is connected to an external display through DisplayLink (may not be relevant).

The error message/backtrace is below.

The only solution is to disconnect the external monitor. Note, reconnecting the external monitor after start up does not fix the issue and it occurs again when the program is run. This means that I cannot use Processing for live demo presentations.

```
java.lang.NullPointerException
	at java.awt.Window.init(Window.java:497)
	at java.awt.Window.<init>(Window.java:537)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at processing.app.ui.SplashWindow.splash(SplashWindow.java:167)
	at processing.app.ui.SplashWindow.splash(SplashWindow.java:197)
	at processing.app.BaseSplash.main(BaseSplash.java:15)
```

Without digging too far into the backtrace it looks like the error occurs when trying to display an image on the splash page, i.e SplashWindow.java line 167 `Frame f = new Frame();` which could be caused by the monitor configuration not being handled properly.

**Comment by benfry** [comment]
Yeah, as mentioned in the original report, it's happening outside Processing, so it's unlikely that we can fix it. But it's certainly a problem.

**Comment by benfry** [comment]
Can no longer reproduce this one on a fully up to date Mojave, Catalina, or Monterey machine. So it may have been a macOS bug that was resolved.
