### ISSUE TITLE
processing.opengl.PSurfaceJOGL with VideoExport

### ISSUE THREAD

**Issue by Aerine** [processing/processing#5675]
Hi,
I just get my new laptop with Windows, I reinstalled everything as it was before and I get this error only when using this library: [https://github.com/hamoid/video_export_processing](https://github.com/hamoid/video_export_processing)

On the instruction startMovie(); I get this error:
`java.lang.RuntimeException: Waited 5000ms for: <26dad5cb, 281d2f60>[count 2, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-FPSAWTAnimator#00-Timer0-FPSAWTAnimator#00-Timer1> at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:410) at java.lang.Thread.run(Thread.java:748)`

Do you know what could be the cause of this? Is it an opengl error? And what should I do?
Thank you for reading me.

**Comment by hamoid** [comment]
Hi, you also posted this issue on the linked repository, and I asked something, but didn't get a reply yet. I think you should probably close this issue as this probably does not belong to the Processing repository :) I'll try to help there.
