### ISSUE TITLE
Error using processing as a library in netbeans: ExceptionInInitializerError, StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Angular-Angel** [processing/processing#5687]
## Description

I’m trying to use processing in netbeans, and am getting an error. I can set processing as a library just fine, but after making my main class extend PApplet, regardless of whether I change anything else or not, I get: “Exception in thread “main” java.lang.ExceptionInInitializerError
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 2
at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
at java.base/java.lang.String.substring(String.java:1874)
at processing.core.PApplet.(PApplet.java:123)”

I think this is caused by a static variable somewhere? I’m running on Xubuntu, with java-11-openjdk-amd64. I looked up PApplet.java:123, and that's just the class declaration for PApplet, so I'm guessing the trouble is further up the class chain. Unless it's actually the block from PApplet.java:129 to PApplet.java:138? It has calls to substring(), so that would fit. I tried copy pasting that into my main function though, and it ran fine. But I guess it might be failing when run in it's normal context, for some reason?

## Expected Behavior

I should be able to run my code and not get an exception.

## Current Behavior

Instead, I get: “Exception in thread “main” java.lang.ExceptionInInitializerError
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 2
at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
at java.base/java.lang.String.substring(String.java:1874)
at processing.core.PApplet.(PApplet.java:123)”

## Steps to Reproduce
Literally just follow this tutorial: https://processing.org/tutorials/eclipse/

All you need to do is add processing as a library, import PApplet, and make your main class extend PApplet. Or at least, that's all I need to do. It may be related to my specific software, specified below.

## Environment
* Processing version: 3.4
* Operating System and OS version: Xubuntu 18.10 
* Other information: Java Version: java-11-openjdk-amd64

**Comment by Angular-Angel** [comment]
Alright, I got a response on the forums - apparently this is issue #5602 , Processing cannot run under OpenJDK 11. That issue is closed, though, so maybe this has been fixed? Do I need a new version? I thought I downloaded the latest, do I need a nightly or something? Or is this a "Will Not Fix" issue, and I just need to install java 8 and work with that? :/

https://github.com/processing/processing/issues/5602

**Comment by Angular-Angel** [comment]
If this is Will Not Fix, it should at least have it's own dedicated error message so people know what's going on and what to do about it.
