### ISSUE TITLE
Contributions Manager Connection Error

### ISSUE THREAD

**Issue by flashmaster77** [processing/processing#5720]
## Description

I start Processing, want to add Contributions (Libraries, Tools...) but Contributions Manager shows error message. 
Console is as follows after clicking the "Try Again" Button:

java.net.SocketException: Address family not supported by protocol family: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:83)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
	at processing.app.contrib.ContributionManager.download(ContributionManager.java:82)
	at processing.app.contrib.ContributionListing$2.run(ContributionListing.java:426)
	at java.lang.Thread.run(Thread.java:748)
java.net.SocketException: Address family not supported by protocol family: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:83)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
	at processing.app.contrib.ContributionManager.download(ContributionManager.java:82)
	at processing.app.contrib.ContributionListing$2.run(ContributionListing.java:426)
	at java.lang.Thread.run(Thread.java:748)

## Steps to Reproduce

1. Open Processing App
2. Sketch -> Add Library
3. Contributions Manager shows error

## Your Environment

 

* Processing version: 3.4
* Operating System and OS version: Windows 10

**Comment by flashmaster77** [comment]
Hello Community, 

isn't there anyone with a similar issue or someone who could help me get a workaround? I've tried several different networks with and without firewall, installed Processing a few times over again from scratch but i always get the same error. 
My Laptop is a near to brand new Lenovo Thinkpad T480s.
I really need the Contributions Manager to work properly as i can't use Processing properly and thus can't learn Processing fully which is really frustrating.

Happy New Year anyways, i'm hoping that someone can help me.

Greetings, flashmaster77

**Comment by benfry** [comment]
Possible spyware on your machine? https://stackoverflow.com/a/21383865
