### ISSUE TITLE
Processing 3.4-3 openjdk8

### ISSUE THREAD

**Issue by narzul** [processing/processing#5754]
Upgrading processing to version 3.4-3 gives this error when using OpenJDK8, there is no problem with version 3.4-2

Processing error:
`
Exception in thread "Thread-10" java.lang.RuntimeException: Exception while attempting /usr/lib/jvm/java-8-openjdk/bin/java -agentlib:jdwp=transport=dt_socket,address=8433,server=y,suspend=y,quiet=y -Djna.nosys=true -Djava.ext.dirs=/usr/lib/jvm/java-8-openjdk/lib/ext -Djava.library.path=:/usr/share/processing/core/library:/usr/share/processing/modes/java/libraries/serial/library/linux64:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib -cp /tmp/BraidOMatic2018v22321127144340720970temp:/usr/share/processing/core/library/jogl-all-natives-linux-amd64.jar:/usr/share/processing/core/library/jogl-all-natives-linux-i586.jar:/usr/share/processing/core/library/jogl-all-natives-macosx-universal.jar:/usr/share/processing/core/library/gluegen-rt-natives-windows-i586.jar:/usr/share/processing/core/library/gluegen-rt-natives-linux-armv6hf.jar:/usr/share/processing/core/library/jogl-all-natives-windows-amd64.jar:/usr/share/processing/core/library/jogl-all-natives-linux-aarch64.jar:/usr/share/processing/core/library/gluegen-rt-natives-linux-amd64.jar:/usr/share/processing/core/library/gluegen-rt-natives-macosx-universal.jar:/usr/share/processing/core/library/core.jar:/usr/share/processing/core/library/gluegen-rt-natives-linux-i586.jar:/usr/share/processing/core/library/jogl-all-natives-windows-i586.jar:/usr/share/processing/core/library/jogl-all.jar:/usr/share/processing/core/library/gluegen-rt.jar:/usr/share/processing/core/library/gluegen-rt-natives-windows-amd64.jar:/usr/share/processing/core/library/gluegen-rt-natives-linux-aarch64.jar:/usr/share/processing/core/library/jogl-all-natives-linux-armv6hf.jar:/usr/share/processing/modes/java/libraries/serial/library/jssc.jar:/usr/share/processing/modes/java/libraries/serial/library/serial.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/rt.jar:/usr/share/processing/lib/ant.jar:/usr/share/processing/lib/ant-launcher.jar:/usr/share/processing/lib/jna.jar:/usr/share/processing/lib/jna-platform.jar:/usr/share/processing/lib/pde.jar:/usr/share/processing/core/library/core.jar:/usr/share/processing/core/library/gluegen-rt.jar:/usr/share/processing/core/library/gluegen-rt-natives-linux-aarch64.jar:/usr/share/processing/core/library/gluegen-rt-natives-linux-amd64.jar:/usr/share/processing/core/library/gluegen-rt-natives-linux-armv6hf.jar:/usr/share/processing/core/library/gluegen-rt-natives-linux-i586.jar:/usr/share/processing/core/library/gluegen-rt-natives-macosx-universal.jar:/usr/share/processing/core/library/gluegen-rt-natives-windows-amd64.jar:/usr/share/processing/core/library/gluegen-rt-natives-windows-i586.jar:/usr/share/processing/core/library/jogl-all.jar:/usr/share/processing/core/library/jogl-all-natives-linux-aarch64.jar:/usr/share/processing/core/library/jogl-all-natives-linux-amd64.jar:/usr/share/processing/core/library/jogl-all-natives-linux-armv6hf.jar:/usr/share/processing/core/library/jogl-all-natives-linux-i586.jar:/usr/share/processing/core/library/jogl-all-natives-macosx-universal.jar:/usr/share/processing/core/library/jogl-all-natives-windows-amd64.jar:/usr/share/processing/core/library/jogl-all-natives-windows-i586.jar:/usr/share/processing/modes/java/mode/antlr.jar:/usr/share/processing/modes/java/mode/classpath-explorer-1.0.jar:/usr/share/processing/modes/java/mode/com.ibm.icu.jar:/usr/share/processing/modes/java/mode/JavaMode.jar:/usr/share/processing/modes/java/mode/jdi.jar:/usr/share/processing/modes/java/mode/jdimodel.jar:/usr/share/processing/modes/java/mode/jdtCompilerAdapter.jar:/usr/share/processing/modes/java/mode/jsoup-1.7.1.jar:/usr/share/processing/modes/java/mode/org.eclipse.core.contenttype.jar:/usr/share/processing/modes/java/mode/org.eclipse.core.jobs.jar:/usr/share/processing/modes/java/mode/org.eclipse.core.resources.jar:/usr/share/processing/modes/java/mode/org.eclipse.core.runtime.jar:/usr/share/processing/modes/java/mode/org.eclipse.equinox.common.jar:/usr/share/processing/modes/java/mode/org.eclipse.equinox.preferences.jar:/usr/share/processing/modes/java/mode/org.eclipse.jdt.core.jar:/usr/share/processing/modes/java/mode/org.eclipse.osgi.jar:/usr/share/processing/modes/java/mode/org.eclipse.text.jar:/usr/share/processing/modes/java/mode/org.netbeans.swing.outline.jar -ea processing.core.PApplet --editor-location=610,660 --external --display=1 --sketch-path=/home/narzul/Documents/Braiderbot/BraidOMatic2018v2 BraidOMatic2018v2
	at processing.core.PApplet.exec(PApplet.java:3498)
	at processing.mode.java.runner.Runner$1.run(Runner.java:498)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk/bin/java": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at processing.core.PApplet.exec(PApplet.java:3496)
	... 2 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 5 more
`

OpenJDK version:
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (build 1.8.0_192-b26)
OpenJDK 64-Bit Server VM (build 25.192-b26, mixed mode)

Environment:
Linux 4.20.1-arch1-1-ARCH #1 SMP PREEMPT Wed Jan 9 20:25:43 UTC 2019 x86_64 GNU/Linux

**Comment by sampottinger** [comment]
Hey there! Just linking these two together...

We are starting to address this in #5750 which is moving to OpenJDK (which is not currently supported). There may be a fork from the effort in #5750 which tackles OpenJDK8 before OpenJDK11. 
See also

**Comment by benfry** [comment]
Closing for now, since for the time being, OpenJDK [is not supported](https://github.com/processing/processing/wiki/Supported-Platforms#linux).
