### ISSUE TITLE
HELP //Contribution Manager Connection Problem. 

### ISSUE THREAD

**Issue by nice-one-chris** [processing/processing#5756]
When opening Contribution Manager I am faced with a red error message reading:

_Could not connect to the Processing server. Contributions cannot be installed or updated without an Internet connection. Please verify your network connection again, then try connecting again._

**attempted fixs:**
Checked the internet connection
Checked firewalls
Checked server is not down
Re-installed Processing
Restated Mac

I am reasonably new to processing so I apologise in advance if this is a simple fix.

The error message from the console reads:
_java.net.SocketException: Can't connect to SOCKS proxy:Connection refused (Connection refused)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:428)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1227)
	at_

**Processing version: 3.4
MacOS Sierra 10.12.6**

Thanks for any help!

**Comment by benfry** [comment]
That's having a problem with the proxy setup on your network. I'd recommend using [the forum](https://discourse.processing.org/) to get help with proxy settings.
