### ISSUE TITLE
incorrect classpath: $CLASSPATH 

### ISSUE THREAD

**Issue by Justas177** [processing/processing#5812]
I am trying to run Processing-3.5.3 on my "Nvidia JetsonTX2" development board (ARMv8 processor) using Ubuntu 16.04.  If i configure Linux to use oracle 8 it gives an error and doesn't even start up. Terminal output below:
**Exception in thread "AWT-EventQueue-0" java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at processing.app.Messages.showTrace(Messages.java:177)
	at processing.app.Base$1.run(Base.java:142)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)**

  $ java --version outputs :
 **java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)**

If i configure java to run on OpenJDK :
**openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)**

The program starts with an error of "Not fond of this java VM" which basically states that processing needs to use java oracle 8, after pressing "OK" it goes to GUI. But whenever you try to compile/run a project, it gives the following output: 
**incorrect classpath: $CLASSPATH
incorrect classpath: $JAVA_HOME/lib
incorrect classpath: $JAVA_HOME/jre/lib 
incorrect classpath: /home/username/Java/jdk1.8/lib
incorrect classpath: /home/username/Java/jdk1.8/jre/lib
Cannot parse error text: incorrect classpath: $CLASSPATH**

I have spent quite some time looking for solution,  trying all different kinds of methods to fix it. but none of the solutions fixed the error. Any help would be highly appreciated!

**Comment by jeremydouglass** [comment]
> 1.8.0_201

This might be related to needing 202 specifically. See:

https://github.com/processing/processing/issues/5868#issuecomment-500949067

**Comment by benfry** [comment]
The main error happening there is that you don't seem to have a usable window system installed, which is required for Processing to run, even if you're just compiling things on the command line.
