### ISSUE TITLE
Contribution Manager unable to open Updates tab

### ISSUE THREAD

**Issue by michthom** [processing/processing#5845]
## Description
Contribution Manager unable to open Updates tab

## Expected Behavior
From menu Sketch > Import Library... > Add Library and click on Updates or from Updates flag in bottom right corner of IDE, I should be able to list the available updates.

## Current Behavior
Contributions Manager will open but the Updates tab remains blank.

## Steps to Reproduce

1. Sketch > Import Library... > Add Library and click on Updates, or:
2. Click on updates flag in bottom right corner of IDE

## Your Environment
* Processing version: 3.5.3
* Operating System and OS version: macOS Mojave 10.14.4
* Other information:

## Possible Causes / Solutions
Unknown.

```
Traceback:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at processing.app.contrib.ListPanel$ContribStatusRenderer.configureStatusColumnLabel(ListPanel.java:330)
	at processing.app.contrib.ListPanel$ContribStatusRenderer.getTableCellRendererComponent(ListPanel.java:305)
	at javax.swing.JTable.prepareRenderer(JTable.java:5729)
	at processing.app.contrib.ListPanel$1.prepareRenderer(ListPanel.java:102)
	at javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2114)
	at javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2016)
	at javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1812)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JViewport.paint(JViewport.java:728)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by benja0x40** [comment]
# Description

Same issue as reported by @michthom using a very similar configuration (minor OS update). 

# Your environment

- Processing version: 3.5.3
- Operating System and OS version: macOS Mojave 10.14.6

# Traceback

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at processing.app.contrib.ListPanel$ContribStatusRenderer.configureStatusColumnLabel(ListPanel.java:330)
	at processing.app.contrib.ListPanel$ContribStatusRenderer.getTableCellRendererComponent(ListPanel.java:305)
	at javax.swing.JTable.prepareRenderer(JTable.java:5729)
	at processing.app.contrib.ListPanel$1.prepareRenderer(ListPanel.java:102)
	at javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2114)
	at javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2016)
	at javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1812)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JViewport.paint(JViewport.java:728)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at processing.app.contrib.ListPanel$ContribStatusRenderer.configureStatusColumnLabel(ListPanel.java:330)
	at processing.app.contrib.ListPanel$ContribStatusRenderer.getTableCellRendererComponent(ListPanel.java:305)
	at javax.swing.JTable.prepareRenderer(JTable.java:5729)
	at processing.app.contrib.ListPanel$1.prepareRenderer(ListPanel.java:102)
	at javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2114)
	at javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2016)
	at javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1812)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

# Preferences
```
android.sdk.ar=1.12.0
android.sdk.gvr=1.180.0
android.sdk.path=/Users/benjamin/OneDrive/_Activities_/Programming/Processing/android/sdk
android.sdk.play_services=16.0.1
android.sdk.support=28.0.0
android.sdk.target=28
android.sdk.wear=2.4.0
chooser.files.native=true
console.auto_clear=true
console.font.size=12
console.lines=4
console.scrollback.chars=40000
console.scrollback.lines=500
contribution.backup.on_install=true
contribution.backup.on_remove=true
editor.caret.blink=true
editor.caret.block=false
editor.completion.auto_close=false
editor.font.family=Source Code Pro
editor.font.size=14
editor.indent=true
editor.input_method_support=false
editor.keys.alternative_cut_copy_paste=false
editor.keys.home_and_end_travel_far=true
editor.keys.home_and_end_travel_smart=true
editor.keys.shift_backspace_is_delete=false
editor.smooth=true
editor.tabs.expand=true
editor.tabs.size=2
editor.token.comment1.style=#666666,plain
editor.token.comment2.style=#666666,plain
editor.token.function1.style=#006699,plain
editor.token.function2.style=#006699,plain
editor.token.function3.style=#669900,plain
editor.token.function4.style=#006699,bold
editor.token.invalid.style=#666666,bold
editor.token.keyword1.style=#33997e,plain
editor.token.keyword2.style=#33997e,plain
editor.token.keyword3.style=#669900,plain
editor.token.keyword4.style=#d94a7a,plain
editor.token.keyword5.style=#e2661a,plain
editor.token.keyword6.style=#33997e,plain
editor.token.label.style=#666666,bold
editor.token.literal1.style=#7D4793,plain
editor.token.literal2.style=#718a62,plain
editor.token.operator.style=#006699,plain
editor.untitled.prefix=sketch_
editor.untitled.suffix=yyMMdd
editor.watcher=true
editor.watcher.debug=false
editor.watcher.window=1500
editor.window.height.default=600
editor.window.height.min=450
editor.window.width.default=700
editor.window.width.min=400
editor.zoom=100%
editor.zoom.auto=true
examples.processing.app.ui.ExamplesFrame.visible=null:null/Topics:null/Contributed Libraries/The MidiBus:null/Libraries:null/Basics:null/Basics/Shape:null/Demos:null/Contributed Libraries:null/Topics/GUI
export.application.embed_java=true
export.application.fullscreen=false
export.application.platform_macosx=true
export.application.stop=true
export.delete_target_folder=true
gohai.uploadtopi.autostart=true
gohai.uploadtopi.hostname=raspberrypi.local
gohai.uploadtopi.logging=true
gohai.uploadtopi.password=raspberry
gohai.uploadtopi.persistent=true
gohai.uploadtopi.username=pi
instance_server.key=0.7910422242884374
instance_server.port=50780
last.sketch.count=0
last.sketch.restore=true
mode.last=processing.mode.java.JavaMode
pdex.autoSave.autoSaveByDefault=true
pdex.autoSave.autoSaveEnabled=false
pdex.autoSave.promptDisplay=true
pdex.autoSaveInterval=5
pdex.completion=true
pdex.completion.trigger=false
pdex.dbgOutput=false
pdex.errorCheckEnabled=true
pdex.inspectMode.hotkey=true
pdex.suggest.imports=true
pdex.warningsEnabled=true
pdex.writeErrorLogs=false
platform.auto_file_type_associations=true
preproc.color_datatype=true
preproc.enhanced_casting=true
preproc.output_parse_tree=false
preproc.save_build_files=false
preproc.substitute_floats=true
preproc.web_colors=true
proxy.http.host=
proxy.http.port=
proxy.https.host=
proxy.https.port=
proxy.socks.host=
proxy.socks.port=
proxy.system=true
recent.count=10
run.display=1
run.options=
run.options.bits=32
run.options.memory=true
run.options.memory.initial=64
run.options.memory.maximum=256
run.present.bgcolor=#666666
run.present.stop.color=#cccccc
run.window.bgcolor=#FFFFFF
search.format=https://google.com/search?q=%s
sketchbook.path.three=/Users/benjamin/OneDrive/_Activities_/Programming/Processing
update.check=true
update.id=2759371917973990401
update.last=1578925742401
welcome.seen=false
welcome.show=false
```

**Comment by benja0x40** [comment]
# Possible Causes / Solutions

I found the following 4 temporary items in my Processing/library folder, all corresponding to the tactu5 library which - as far as I remember - was not installed successfully:

![Screenshot 2020-01-16 at 12 11 07](https://user-images.githubusercontent.com/12811695/72520265-5951cf80-3859-11ea-81e8-190338e7dd04.png)

It turns out that deleting these temporary folders has eliminated the `Exception in thread "AWT-EventQueue-0"` error and restored access to the Update panel in the Contribution Manager.

**Comment by benfry** [comment]
Found a couple things that may have been causing this and fixed them for the next release (anything later than 3.5.3)

That tactu5 library also needs to be fixed: the author needs to add a  `library.properties` file so that it will install properly.
