### ISSUE TITLE
Processing not starting when display using DisplayLink connected

### ISSUE THREAD

**Issue by thefelixno** [processing/processing#5874]
## Description

A fresh download of Processing 3.5.3 is not starting on Mac OS 10.14.5 when a display is connected using DisplayLink 5.1.1

## Steps to Reproduce

Here's what I did
1. download latest Processing for Mac
2. tried starting when external Monitor was connected to MacBook using a DELL docking station with DisplayLink -> the program exits even without opening the terminal or anything
3. when disconnecting the DELL docking station or the external monitor Processing starts just fine
4. with Processing started, the docking station with DisplayLink can be reconnected and Processing will keep running as expected, CPU load of the DisplayLinkManager however remains high

## Your Environment

 

Processing version: 3.5.3
Operating System and OS version: Mac OS 10.14.5
Display Link: DisplayLink 5.1.1

## Possible Causes / Solutions

This is probably a bug in the DisplayLink Software, however I do think it is worth checking out if this is JRE related, since I've seen other bugs for Processing describing the same problem when external monitors connected

**Comment by thefelixno** [comment]
a little update: Processing starts correctly when the primary monitor is set to the integrated display of my MacBook.

**Comment by Conmy** [comment]
This has happened to me also.

When I launch Processing, the P3 logo would appear in the dock for a moment and then disappear.

I could see the following when I checked `/Applications/Processing.app/Contents/MacOS/Processing` from a terminal

```
java.lang.NullPointerException
	at java.awt.Window.init(Window.java:497)
	at java.awt.Window.<init>(Window.java:537)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at processing.app.ui.SplashWindow.splash(SplashWindow.java:167)
	at processing.app.ui.SplashWindow.splash(SplashWindow.java:197)
	at processing.app.BaseSplash.main(BaseSplash.java:15)
```

Setting the main display to the built-in monitor allowed me to continue working on sketches.

**Comment by benfry** [comment]
This may be fixed with the 4.x (alpha) releases, since they use JDK 11. Please give it a try and let me know: https://github.com/processing/processing4/releases
