### ISSUE TITLE
valid svg not working in P2D

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#5898]
I know supporting everything from SVG is beyond the scope of processing.
However, this seems like something that can not be to hard to fix.
I checked with https://validator.w3.org and the SVG is valid.

I probably look into it myself if my plan for a simple SVG converter fails.
I wish I had the time to make a proper ast based svg parser.

```svg
<svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
<path d="m13 9h5.5l-5.5-5.5v5.5m-7-7h8l6 6v12a2 2 0 0 1 -2 2h-12c-1.11 0-2-.9-2-2v-16c0-1.11.89-2 2-2m5 2h-5v16h5 7v-9h-7v-7z" fill="#42a5f5"/>
</svg>
```

**Comment by clankill3r** [comment]
(I can't quote, preview or edit last post in my browser atm cause the web is broken pile of shit, so sorry if the formatting is horrible)

The error:

>>>
java.lang.ArrayIndexOutOfBoundsException: 115
	at jogamp.opengl.glu.tessellator.PriorityQSort.pqInit(PriorityQSort.java:151)
	at jogamp.opengl.glu.tessellator.Sweep.InitPriorityQ(Sweep.java:1246)
	at jogamp.opengl.glu.tessellator.Sweep.__gl_computeInterior(Sweep.java:1313)
	at jogamp.opengl.glu.tessellator.GLUtessellatorImpl.gluTessEndPolygon(GLUtessellatorImpl.java:526)
	at com.jogamp.opengl.glu.GLU.gluTessEndPolygon(GLU.java:896)
	at processing.opengl.PJOGL$Tessellator.endPolygon(PJOGL.java:629)
	at processing.opengl.PGraphicsOpenGL$Tessellator.tessellatePolygon(PGraphicsOpenGL.java:12591)
	at processing.opengl.PShapeOpenGL.tessellatePath(PShapeOpenGL.java:3475)
	at processing.opengl.PShapeOpenGL.tessellateImpl(PShapeOpenGL.java:2984)
	at processing.opengl.PShapeOpenGL.tessellateImpl(PShapeOpenGL.java:2891)
	at processing.opengl.PShapeOpenGL.tessellate(PShapeOpenGL.java:2839)
	at processing.opengl.PShapeOpenGL.updateTessellation(PShapeOpenGL.java:2756)
	at processing.opengl.PShapeOpenGL.draw(PShapeOpenGL.java:4662)
	at processing.core.PGraphics.shape(PGraphics.java:4003)
	at processing.opengl.PGraphics2D.shape(PGraphics2D.java:201)
	at processing.core.PApplet.shape(PApplet.java:12707)
	at doeke.p5ui_examples.demos.FileViewerDemo.setup(FileViewerDemo.java:141)
	at processing.core.PApplet.handleDraw(PApplet.java:2401)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:866)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Tessellation Error: out of memory

**Comment by benfry** [comment]
That's a bug in the tessellation code for OpenGL, not the SVG code.

**Comment by clankill3r** [comment]
Yeah I thought of that while laying in bed :)
