### ISSUE TITLE
Unable to run sketch in G4P

### ISSUE THREAD

**Issue by biran4454** [processing/processing#5905]
## Description

Get an error message after running sketch with a GUI created in G4P.
This is the only place I have to post the error. Sorry if it's the wrong place.

## Expected Behavior

The sketch should run with every type of element (slider, checkbox, image, etc.)

## Current Behavior

Output window opens, but processing gives an error in the console before anything appears on it.

## Steps to Reproduce

1. Added one of each type of GUI element (checkbox, image, etc.)
2. Set them to the 'Gold theme'
3. Didn't add any code; I just wanted to test the GUI to check it worked.
4. Ran the sketch, but error came up.

## Error
`The file "list_674559" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.
java.lang.NullPointerException
	at g4p_controls.GDropList.updateBuffer(Unknown Source)
	at g4p_controls.GDropList.draw(Unknown Source)
	at g4p_controls.GWindowImpl.draw(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1432)
	at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1425)
	at processing.core.PApplet.handleMethods(PApplet.java:1624)
	at processing.core.PApplet.handleDraw(PApplet.java:2488)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1547)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:313)
NullPointerException
`

## Your Environment

 

* Processing version: 3.5.3
* Operating System and OS version: Win 10
* Other information: G4P version 4.3. Processing is not installed in Program Files. Stored on different drive. However, G4P is installed in the processing folder in documents on C drive. Also got another error on a completely different tool, but it was an unrelated error. Probably just coincidence.

## Possible Causes / Solutions

Not a clue.
Thanks, and sorry again if this was the wrong place!

**Comment by whykatherine** [comment]
The error suggests that a file you reference in the code isn't supplied to the sketch, but could you post your whole code so others can see if that's the case?

**Comment by biran4454** [comment]
> The error suggests that a file you reference in the code isn't supplied to the sketch, but could you post your whole code so others can see if that's the case?

I have added no extra code except the code generated by G4P.

**Comment by jeremydouglass** [comment]
Please ask coding questions on the forum.

G4P is a contributed library -- it is not developed by the Processing Foundation, and the code isn't in this repo. I suggest you ask this question on the forum -- the G4P author sometimes answers questions there:

http://discourse.processing.org

**Comment by benfry** [comment]
Closing since G4P issues are out of our control…
