### ISSUE TITLE
Running Code prompts error

### ISSUE THREAD

**Issue by GaurabRock** [processing/processing#5908]
When i run a simple code should prints a rectange it gives me the following error.

Exception in thread "Thread-9" java.lang.RuntimeException: Exception while attempting /usr/lib/jvm/java-8-jre/bin/java -agentlib:jdwp=transport=dt_socket,address=8693,server=y,suspend=y,quiet=y -Djna.nosys=true -Djava.ext.dirs=/usr/lib/jvm/java-8-jre/lib/ext -Djava.library.path=:/opt/processing/core/library:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib -cp /tmp/sketch_190815a5622159750171950781temp:/opt/processing/core/library/gluegen-rt-natives-linux-aarch64.jar:/opt/processing/core/library/jogl-all-natives-macosx-universal.jar:/opt/processing/core/library/gluegen-rt.jar:/opt/processing/core/library/jogl-all-natives-windows-amd64.jar:/opt/processing/core/library/jogl-all-natives-windows-i586.jar:/opt/processing/core/library/jogl-all-natives-linux-i586.jar:/opt/processing/core/library/gluegen-rt-natives-linux-amd64.jar:/opt/processing/core/library/gluegen-rt-natives-linux-i586.jar:/opt/processing/core/library/jogl-all-natives-linux-armv6hf.jar:/opt/processing/core/library/jogl-all.jar:/opt/processing/core/library/gluegen-rt-natives-macosx-universal.jar:/opt/processing/core/library/gluegen-rt-natives-windows-i586.jar:/opt/processing/core/library/gluegen-rt-natives-linux-armv6hf.jar:/opt/processing/core/library/core.jar:/opt/processing/core/library/jogl-all-natives-linux-aarch64.jar:/opt/processing/core/library/jogl-all-natives-linux-amd64.jar:/opt/processing/core/library/gluegen-rt-natives-windows-amd64.jar:/usr/lib/jvm/java-8-jre/jre/lib/rt.jar:/opt/processing/lib/ant.jar:/opt/processing/lib/ant-launcher.jar:/opt/processing/lib/jna.jar:/opt/processing/lib/jna-platform.jar:/opt/processing/lib/pde.jar:/opt/processing/core/library/core.jar:/opt/processing/core/library/gluegen-rt.jar:/opt/processing/core/library/gluegen-rt-natives-linux-aarch64.jar:/opt/processing/core/library/gluegen-rt-natives-linux-amd64.jar:/opt/processing/core/library/gluegen-rt-natives-linux-armv6hf.jar:/opt/processing/core/library/gluegen-rt-natives-linux-i586.jar:/opt/processing/core/library/gluegen-rt-natives-macosx-universal.jar:/opt/processing/core/library/gluegen-rt-natives-windows-amd64.jar:/opt/processing/core/library/gluegen-rt-natives-windows-i586.jar:/opt/processing/core/library/jogl-all.jar:/opt/processing/core/library/jogl-all-natives-linux-aarch64.jar:/opt/processing/core/library/jogl-all-natives-linux-amd64.jar:/opt/processing/core/library/jogl-all-natives-linux-armv6hf.jar:/opt/processing/core/library/jogl-all-natives-linux-i586.jar:/opt/processing/core/library/jogl-all-natives-macosx-universal.jar:/opt/processing/core/library/jogl-all-natives-windows-amd64.jar:/opt/processing/core/library/jogl-all-natives-windows-i586.jar:/opt/processing/modes/java/mode/antlr.jar:/opt/processing/modes/java/mode/classpath-explorer-1.0.jar:/opt/processing/modes/java/mode/com.ibm.icu.jar:/opt/processing/modes/java/mode/JavaMode.jar:/opt/processing/modes/java/mode/jdi.jar:/opt/processing/modes/java/mode/jdimodel.jar:/opt/processing/modes/java/mode/jdtCompilerAdapter.jar:/opt/processing/modes/java/mode/jsoup-1.7.1.jar:/opt/processing/modes/java/mode/org.eclipse.core.contenttype.jar:/opt/processing/modes/java/mode/org.eclipse.core.jobs.jar:/opt/processing/modes/java/mode/org.eclipse.core.resources.jar:/opt/processing/modes/java/mode/org.eclipse.core.runtime.jar:/opt/processing/modes/java/mode/org.eclipse.equinox.common.jar:/opt/processing/modes/java/mode/org.eclipse.equinox.preferences.jar:/opt/processing/modes/java/mode/org.eclipse.jdt.core.jar:/opt/processing/modes/java/mode/org.eclipse.osgi.jar:/opt/processing/modes/java/mode/org.eclipse.text.jar:/opt/processing/modes/java/mode/org.netbeans.swing.outline.jar -ea processing.core.PApplet --display=1 --sketch-path=/tmp/untitled4764461744053707996sketches/sketch_190815a sketch_190815a
	at processing.core.PApplet.exec(PApplet.java:3563)
	at processing.mode.java.runner.Runner$1.run(Runner.java:498)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-jre/bin/java": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at processing.core.PApplet.exec(PApplet.java:3561)
	... 2 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 5 more

**Comment by whykatherine** [comment]
Could you post your whole code please?

**Comment by GaurabRock** [comment]
void setup()
{
size(200,200);
}
void draw()
{
background(170);
}

**Comment by GaurabRock** [comment]
void setup()
{
size(600,400);
}
void draw()
{
background(200);
}

**Comment by whykatherine** [comment]
I'm not sure, but I think your computer is missing Java, or the path is wrong and Processing can't find it? Could you try uninstalling and reinstalling Processing to see if it'll fix that?

**Comment by GaurabRock** [comment]
tried it doesnt work

**Comment by GaurabRock** [comment]
Btw i am using arch linux and java-8-jre/jre

**Comment by jeremydouglass** [comment]
Your log says:

"Caused by: java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-jre/bin/java": error=2, No such file or directory"

That seems fairly straightforward.

Start out with `which /usr/lib/jvm/java-8-jre/`

Not sure if you are using PDE, and I don't run Processing on Linux, but on macOS PDE comes with its own java-8 -- it doesn't use the system one, so you don't need to install one -- because it needs a very specific Java 8 version.

**Comment by GaurabRock** [comment]
So, should I replace the java folder by the default one that processing provides?

**Comment by jeremydouglass** [comment]
Yes -- I am not on arch linux. but that would be my guess. Are you getting this error in PDE, or using Processing from the command line, or using it from Eclipse?

I'm curious where that path `/usr/lib/jvm/java-8-jre/` came from. Did you check if that path even exists?

**Comment by GaurabRock** [comment]
That path doesnt exist and i got this error from pde

**Comment by benfry** [comment]
Have you modified the Processing download to remove the `java` folder? The download includes its own version of Java to avoid exactly this type of problem.

**Comment by benfry** [comment]
No response; closing.
