### ISSUE TITLE
Error when attempting to apply updates

### ISSUE THREAD

**Issue by meltingSnowdrift** [processing/processing#5960]
## Description

This issue appears extremely similar to, and probably has the same cause as, #5845 . The actions and behaviour described here, however, are not identical to those in that issue.

Processing started with an indication in the lower right corner that one update is available. When that indication is clicked, the Contribution Manager window opens and then immediately freezes, while displaying an error message in the console in the main window.

## Expected Behavior

I expected that the Contribution Manager would open on the updates tab and permit me to install the available update.

## Current Behavior

The contribution manager opened on the updates tab. The updates tab then immediately froze and the following appeared in the console:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at processing.app.contrib.ListPanel$ContribStatusRenderer.configureStatusColumnLabel(ListPanel.java:330)
	at processing.app.contrib.ListPanel$ContribStatusRenderer.getTableCellRendererComponent(ListPanel.java:305)
	at javax.swing.JTable.prepareRenderer(JTable.java:5729)
	at processing.app.contrib.ListPanel$1.prepareRenderer(ListPanel.java:102)
	at javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2114)
	at javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2016)
	at javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1812)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JViewport.paint(JViewport.java:728)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
Clicking on other tabs in the Contribution Manager after this happens appears to open them correctly, and normal interaction with them appears possible. 

However, if the Contribution manager is closed after the bug occurs (with or without navigating to another tab first) and the available update indication is clicked again, the Contribution Manager window opens entirely white but still capable of interaction. Clicking inside this window appears to update portions of the window affected by the click. An example is below:
![image](https://user-images.githubusercontent.com/45924338/70012960-0be8ff80-1544-11ea-9fea-2405337e6072.png)

Some such clicks results in further error messages in the console identical to the one quoted above.

If another tab is clicked,the entire Contribution Manager window updates and that tab becomes selected and usable.

In any tested case, all attempts to navigate to the Updates tab from another tab results in no immediate effect on the graphics of the Contribution Manager and an error message in the console identical to the one quoted above. Further clicks in the Contribution Manager window interact with an invisible updates tab in a way similar to what happens when the update indication is clicked a second time, only updating regions of the window affected by the click.

## Steps to Reproduce

To reproduce all the main elements of this issue,
1. Open Processing while an update is available for installation through the Contribution Manager.
2. Click the update indication at the lower right corner of the main window.
3. Close the Contribution Manager.
4. Click the update indication again.

If this succeeds in reproducing the issue, other combinations of related behaviour should be easily reproducible from the descriptions in the "Current Behavior" section of this issue.

## Your Environment

 

* Processing version: Processing 3.5.3
* Operating System and OS version: Windows 10
* Other information: Preferences file for the installation on which this occurred: [preferences.txt](https://github.com/processing/processing/files/3914062/preferences.txt)

**Comment by benja0x40** [comment]
I found a workaround for a similar issue regarding Processing updates on macOS. In case it would also be relevant for this issue on Windows, here is the link to my comment: https://github.com/processing/processing/issues/5845#issuecomment-575106341

**Comment by meltingSnowdrift** [comment]
Upon attempting to test this workaround, I found that the bug was not happening anymore, that a search for "tactu5" in the Documents/Processing folder produced no results, and that I did not have the tactu5 library installed at all.

I did not install the available update although I now can do so in order to make it easier to reproduce this problem.

**Comment by benfry** [comment]
Thanks for tracking it down to the tactu5 library, since that gave me something to test against. That library isn't set up properly (it has no `library.properties` file), but it was half-installing. 

For 3.5.4, I've added some additional checks to prevent this from happening.
