### ISSUE TITLE
(MAC) (Processing.py) Exported sketch looks for the data folder in the user (~) folder.

### ISSUE THREAD

**Issue by Mrpyfisher199** [processing/processing#5972]
Make exported sketches look for data files in "APP_DIRECTORY/App.app/Contents/Processing/data/".

This is a bug. Once executed, the exported sketch should look for the files in "APP_DIRECTORY/App.app/Contents/Processing/data/", not in "~/" ("/Users/User").

Currently, once "App.app/Contents/MacOS/sketch" (The Unix Executable File) is executed, the "App.app/Contents/Processing/source/sketch.pyde" looks for the files from commands such as loadImage(FILE) or loadFont(FILE) in  "~/", and not in "App.app/Contents/Processing/data/".

To Reproduce:
1) Get Processing 3.5.3 on macOS Sierra 10.12.6.
2) Get the Python mode and select it.
3) Create a functioning sketch with any Processing-based (such as loadImage(), loadFont(), etc...) function which requires an external file from "data/".
Such as: 

`def setup(): size(200,200);`
`def draw(): background(0);test_image = loadImage("test_image.png");image(test_image,0,0)`

In the given example, "test.png" is located in "SKETCH_DIRECTORY/data/".
4) Export the sketch, selecting "MAC OS X" as operating system to export to, "FULLSCREEN mode", and "Embed Java for Mac OS X".
5) Launch the newly created application.
As in our given example, the exported sketch will look for the "test_image.png" under "~/", wont find it, and will give the following warning about the missing file and finally an error because we try to render a non-existing file:
`The file "test_image.png" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.`
`java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jycessing.PAppletJythonDriver.macosxFullScreenToggle(PAppletJythonDriver.java:969)
	at jycessing.PAppletJythonDriver.runAndBlock(PAppletJythonDriver.java:919)
	at jycessing.Runner.runSketchBlocking(Runner.java:408)
	at jycessing.Runner.runSketchBlocking(Runner.java:280)
	at jycessing.Runner.main(Runner.java:185)
Caused by: java.lang.NullPointerException
	at com.apple.eawt.Application.requestToggleFullScreen(Application.java:397)
	... 9 more
java.lang.NullPointerException
	at processing.core.PGraphics.image(PGraphics.java:3814)
	at processing.core.PApplet.image(PApplet.java:12806)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:188)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:534)
	at org.python.core.PyObject.__call__(PyObject.java:540)
	at org.python.core.PyMethod.__call__(PyMethod.java:171)
	at org.python.pycode._pyx5.render$15(sketch.pyde:352)
	at org.python.pycode._pyx5.call_function(sketch.pyde)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:139)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx5.draw$33(sketch.pyde:881)
	at org.python.pycode._pyx5.call_function(sketch.pyde)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:125)
	at org.python.core.PyFunction.__call__(PyFunction.java:403)
	at org.python.core.PyFunction.__call__(PyFunction.java:398)
	at jycessing.PAppletJythonDriver.draw(PAppletJythonDriver.java:1370)
	at processing.core.PApplet.handleDraw(PApplet.java:2475)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1547)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:313)
`

Operating System: MacOS Sierra 10.12.6
Processing version: 3.5.3
Processing mode: Python (through Jython).

A solution to this would be changing the internal sketch path system, which **_I THINK_** is located in "core.jar/processing/core/PApplet.class". As I am not familiar with the code itself I am unable to pinpoint the exact spot where the sketch path is defined.

Thanks!

**Comment by kfrajer** [comment]
This issue belongs to the Processing.py repo. You can open one [here](https://github.com/jdf/Processing.py-Bugs/issues)

The easiest way to access Processing.py is by visiting py.processing.org and you can find the link above. 

Kf
