### ISSUE TITLE
arduino ide broke after installing processing

### ISSUE THREAD

**Issue by arthurbenjaminsmit** [processing/processing#6031]
i installed processing today and started working on something, i don't know java so i experiment. then when i try to make an arduino sketch that uses what i made i noticed that the arduino ide didn't work so i try it from the terminal nothing happens for two minutes and then i got this 

> Exception in thread "main" java.lang.AbstractMethodError
	at processing.app.Editor.addTools(Editor.java:794)
	at processing.app.Editor.buildToolsMenu(Editor.java:672)
	at processing.app.Editor.buildMenuBar(Editor.java:476)
	at processing.app.Editor.<init>(Editor.java:205)
	at processing.app.Base.handleOpen(Base.java:705)
	at processing.app.Base.handleOpen(Base.java:670)
	at processing.app.Base.handleNew(Base.java:566)
	at processing.app.Base.<init>(Base.java:306)
	at processing.app.Base.main(Base.java:195)
.
i don't know exatly what it is but i cant fix it and uninstalling and reinstalling doesn't work.
can someone help with this issue

**Comment by arthurbenjaminsmit** [comment]
oops didnt end the quote/code segment

**Comment by benfry** [comment]
That looks like you set them both to use the same “sketchbook” location, and so Processing-specific tools are being used by Arduino or something like that. 

But this is a better question for https://discourse.processing.org/
