### ISSUE TITLE
Undo/redo corrupts file lines. Bad Location: -[xxx] for start [xxx] and length -[xxx]javax.swing.text.BadLocationException: Length must be positive

### ISSUE THREAD

**Issue by ElnuDev** [processing/processing#6087]
## Description
![Screenshot](https://media.discordapp.net/attachments/216616539221262336/746858470300450977/Screenshot_from_2020-08-22_15-26-59.png?width=1176&height=662)
I was normally going about working on my code when suddenly undo/redo (Ctrl+Z/Ctrl+Shift+Z) started corrupting all of the lines in my file and spewing Bad Location errors into the console, as you can see in the screenshot.

The following error was being repeatedly sent to the console. The numbers in "Bad Location" would always vary, but the location would be always negative, the start always positive, and the length always negative:

```
Bad Location: -110 for start 447 and length -110javax.swing.text.BadLocationException: Length must be positive
	at javax.swing.text.AbstractDocument.getText(AbstractDocument.java:808)
	at processing.app.syntax.JEditTextArea.getText(JEditTextArea.java:1033)
	at processing.app.syntax.JEditTextArea.getLineText(JEditTextArea.java:1062)
	at processing.app.syntax.TextAreaPainter.paintSyntaxLine(TextAreaPainter.java:663)
	at processing.app.syntax.TextAreaPainter.paintLine(TextAreaPainter.java:617)
	at processing.app.syntax.PdeTextAreaPainter.paintLine(PdeTextAreaPainter.java:120)
	at processing.app.syntax.TextAreaPainter.paint(TextAreaPainter.java:495)
	at processing.mode.java.pdex.JavaTextAreaPainter.paint(JavaTextAreaPainter.java:91)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JSplitPane.paintChildren(JSplitPane.java:1047)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:290)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

## Your Environment

 

* Processing version: 3.5.4
* Operating System and OS version: Ubuntu 20.04 LTS
* Other information: I'm using [jeffThompson/DarkProcessingTheme_3.0](https://github.com/jeffThompson/DarkProcessingTheme_3.0) for dark theme.

**Comment by ElnuDev** [comment]
Hopefully this gets solved soon. It's a pretty bad issue.

**Comment by benfry** [comment]
Marking as duplicate of #4775.
