### ISSUE TITLE
Questions about java.lang.RuntimeException

### ISSUE THREAD

**Issue by jamesbull1** [processing/processing#6100]
1.processing3.5.4
2.win10
3.As long as it runs, it will go wrong
4.Error prompt：
java.lang.RuntimeException: java.lang.ClassNotFoundException: sketch_200926a
	at processing.core.PApplet.runSketch(PApplet.java:10852)
	at processing.core.PApplet.main(PApplet.java:10620)
Caused by: java.lang.ClassNotFoundException: sketch_200926a
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
RuntimeException: java.lang.ClassNotFoundException: sketch_200926a
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at processing.core.PApplet.runSketch(PApplet.java:10845)
	... 1 more

**Comment by benfry** [comment]
Please use https://discourse.processing.org/ for questions.
