### ISSUE TITLE
java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by ahmedawais** [processing/processing#6120]
I am trying to import STL CAD file in processing but getting an error java.lang.outofmemoryerror java heap space.

how to solve this issue ? i have increased my memory in Preferences tab to 10GB but issue still persist. My CAD file size is big its 20MB. I have also used the loadshape() function to import .obj file of the same model but not satisfied with the result. As STL is the required format on which i am working. Can any body help ?

operating system windows 10, processing version 3.0

Thanks

following the example code i am using.

import toxi.geom.*;

import toxi.geom.mesh.*;

import toxi.processing.*;

TriangleMesh mesh;

ToxiclibsSupport gfx;

void setup() {

size(600,600,P3D);

mesh=(TriangleMesh)new STLReader().loadBinary(sketchPath(“part1.stl”),STLReader.TRIANGLEMESH);

//mesh=(TriangleMesh)new STLReader().loadBinary(sketchPath(“part1.stl”),STLReader.TRIANGLEMESH).flipYAxis();

gfx=new ToxiclibsSupport(this);

}

void draw() {

background(51);

lights();

translate(width/2,height/2,0);

rotateX(mouseY*0.01);

rotateY(mouseX*0.01);

gfx.origin(new Vec3D(),200);

noStroke();

gfx.mesh(mesh,false,10);

}

Error:

java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
	at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:412)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.ArrayList.<init>(ArrayList.java:153)
	at toxi.geom.mesh.TriangleMesh.init(Unknown Source)
RuntimeException: java.lang.OutOfMemoryError: Java heap space
	at toxi.geom.mesh.TriangleMesh.init(Unknown Source)
	at toxi.geom.mesh.STLReader.loadBinary(Unknown Source)
	at toxi.geom.mesh.STLReader.loadBinary(Unknown Source)
	at toxi.geom.mesh.STLReader.loadBinary(Unknown Source)
	at STLImportTest.setup(STLImportTest.java:59)
	at processing.core.PApplet.handleDraw(PApplet.java:2432)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:866)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by benfry** [comment]
Please use https://discourse.processing.org/ for coding questions.
