### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by christostr** [processing/processing#6127]
How can I fix this?

Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: Unable to load library 'CoreServices':
dlopen(libCoreServices.dylib, 9): image not found
dlopen(libCoreServices.dylib, 9): image not found
Native library (darwin/libCoreServices.dylib) not found in resource path (/private/var/folders/c5/sg5zywm15v1_2t_ns3_cflm80000gn/T/AppTranslocation/EB95B1CB-5097-488D-B073-59E5321B0765/d/Processing.app/Contents/Java/Classes:/private/var/folders/c5/sg5zywm15v1_2t_ns3_cflm80000gn/T/AppTranslocation/EB95B1CB-5097-488D-B073-59E5321B0765/d/Processing.app/Contents/Java/ant.jar:/private/var/folders/c5/sg5zywm15v1_2t_ns3_cflm80000gn/T/AppTranslocation/EB95B1CB-5097-488D-B073-59E5321B0765/d/Processing.app/Contents/Java/VAqua7.jar:/private/var/folders/c5/sg5zywm15v1_2t_ns3_cflm80000gn/T/AppTranslocation/EB95B1CB-5097-488D-B073-59E5321B0765/d/Processing.app/Contents/Java/ant-launcher.jar:/private/var/folders/c5/sg5zywm15v1_2t_ns3_cflm80000gn/T/AppTranslocation/EB95B1CB-5097-488D-B073-59E5321B0765/d/Processing.app/Contents/Java/core.jar:/private/var/folders/c5/sg5zywm15v1_2t_ns3_cflm80000gn/T/AppTranslocation/EB95B1CB-5097-488D-B073-59E5321B0765/d/Processing.app/Contents/Java/jna.jar:/private/var/folders/c5/sg5zywm15v1_2t_ns3_cflm80000gn/T/AppTranslocation/EB95B1CB-5097-488D-B073-59E5321B0765/d/Processing.app/Contents/Java/pde.jar:/private/var/folders/c5/sg5zywm15v1_2t_ns3_cflm80000gn/T/AppTranslocation/EB95B1CB-5097-488D-B073-59E5321B0765/d/Processing.app/Contents/Java/jna-platform.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
	at com.sun.jna.Library$Handler.<init>(Library.java:179)
	at com.sun.jna.Native.load(Native.java:596)
	at com.sun.jna.Native.load(Native.java:570)
	at com.sun.jna.platform.mac.MacFileUtils$FileManager.<clinit>(MacFileUtils.java:45)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186)
	at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1105)
	at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1086)
	at java.base/java.lang.reflect.Field.get(Field.java:418)
	at com.sun.jna.Native.loadLibraryInstance(Native.java:667)
	at com.sun.jna.Native.getLibraryOptions(Native.java:737)
	at com.sun.jna.Native.getStructureAlignment(Native.java:829)
	at com.sun.jna.Structure.setAlignType(Structure.java:280)
	at com.sun.jna.Structure.<init>(Structure.java:197)
	at com.sun.jna.Structure.<init>(Structure.java:193)
	at com.sun.jna.Structure.<init>(Structure.java:180)
	at com.sun.jna.Structure.<init>(Structure.java:172)
	at com.sun.jna.platform.mac.MacFileUtils$FileManager$FSRef.<init>(MacFileUtils.java:57)
	at com.sun.jna.platform.mac.MacFileUtils.moveToTrash(MacFileUtils.java:74)
	at processing.app.Platform.deleteFile(Platform.java:382)
	at processing.mode.p5js.p5jsBuild.cleanTempFiles(p5jsBuild.java:246)
	at processing.mode.p5js.p5jsEditor.handleStop(p5jsEditor.java:372)
	at processing.mode.p5js.p5jsEditor.internalCloseRunner(p5jsEditor.java:306)
	at processing.app.ui.Editor.prepareRun(Editor.java:2829)
	at processing.mode.p5js.p5jsEditor.handleRun(p5jsEditor.java:337)
	at processing.mode.p5js.p5jsToolbar.handleRun(p5jsToolbar.java:32)
	at processing.app.ui.EditorToolbar$1.actionPerformed(EditorToolbar.java:157)
	at processing.app.ui.EditorButton.mousePressed(EditorButton.java:151)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libCoreServices.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 61 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libCoreServices.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 61 more
	Suppressed: java.io.IOException: Native library (darwin/libCoreServices.dylib) not found in resource path (/private/var/folders/c5/sg5zywm15v1_2t_ns3_cflm80000gn/T/AppTranslocation/EB95B1CB-5097-488D-B073-59E5321B0765/d/Processing.app/Contents/Java/Classes:/private/var/folders/c5/sg5zywm15v1_2t_ns3_cflm80000gn/T/AppTranslocation/EB95B1CB-5097-488D-B073-59E5321B0765/d/Processing.app/Contents/Java/ant.jar:/private/var/folders/c5/sg5zywm15v1_2t_ns3_cflm80000gn/T/AppTranslocation/EB95B1CB-5097-488D-B073-59E5321B0765/d/Processing.app/Contents/Java/VAqua7.jar:/private/var/folders/c5/sg5zywm15v1_2t_ns3_cflm80000gn/T/AppTranslocation/EB95B1CB-5097-488D-B073-59E5321B0765/d/Processing.app/Contents/Java/ant-launcher.jar:/private/var/folders/c5/sg5zywm15v1_2t_ns3_cflm80000gn/T/AppTranslocation/EB95B1CB-5097-488D-B073-59E5321B0765/d/Processing.app/Contents/Java/core.jar:/private/var/folders/c5/sg5zywm15v1_2t_ns3_cflm80000gn/T/AppTranslocation/EB95B1CB-5097-488D-B073-59E5321B0765/d/Processing.app/Contents/Java/jna.jar:/private/var/folders/c5/sg5zywm15v1_2t_ns3_cflm80000gn/T/AppTranslocation/EB95B1CB-5097-488D-B073-59E5321B0765/d/Processing.app/Contents/Java/pde.jar:/private/var/folders/c5/sg5zywm15v1_2t_ns3_cflm80000gn/T/AppTranslocation/EB95B1CB-5097-488D-B073-59E5321B0765/d/Processing.app/Contents/Java/jna-platform.jar)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1089)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:276)
		... 61 more
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.platform.mac.MacFileUtils$FileManager
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186)
	at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1105)
	at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1086)
	at java.base/java.lang.reflect.Field.get(Field.java:418)
	at com.sun.jna.Native.loadLibraryInstance(Native.java:667)
	at com.sun.jna.Native.getLibraryOptions(Native.java:737)
	at com.sun.jna.Native.getStructureAlignment(Native.java:829)
	at com.sun.jna.Structure.setAlignType(Structure.java:280)
	at com.sun.jna.Structure.<init>(Structure.java:197)
	at com.sun.jna.Structure.<init>(Structure.java:193)
	at com.sun.jna.Structure.<init>(Structure.java:180)
	at com.sun.jna.Structure.<init>(Structure.java:172)
	at com.sun.jna.platform.mac.MacFileUtils$FileManager$FSRef.<init>(MacFileUtils.java:57)
	at com.sun.jna.platform.mac.MacFileUtils.moveToTrash(MacFileUtils.java:74)
	at processing.app.Platform.deleteFile(Platform.java:382)
	at processing.mode.p5js.p5jsBuild.cleanTempFiles(p5jsBuild.java:246)
	at processing.mode.p5js.p5jsEditor.handleStop(p5jsEditor.java:372)
	at processing.mode.p5js.p5jsEditor.internalCloseRunner(p5jsEditor.java:306)
	at processing.app.ui.Editor.prepareRun(Editor.java:2829)
	at processing.mode.p5js.p5jsEditor.handleRun(p5jsEditor.java:337)
	at processing.mode.p5js.p5jsToolbar.handleRun(p5jsToolbar.java:32)
	at processing.app.ui.EditorToolbar$1.actionPerformed(EditorToolbar.java:157)
	at processing.app.ui.EditorButton.mousePressed(EditorButton.java:151)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.platform.mac.MacFileUtils$FileManager
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186)
	at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1105)
	at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1086)
	at java.base/java.lang.reflect.Field.get(Field.java:418)
	at com.sun.jna.Native.loadLibraryInstance(Native.java:667)
	at com.sun.jna.Native.getLibraryOptions(Native.java:737)
	at com.sun.jna.Native.getStructureAlignment(Native.java:829)
	at com.sun.jna.Structure.setAlignType(Structure.java:280)
	at com.sun.jna.Structure.<init>(Structure.java:197)
	at com.sun.jna.Structure.<init>(Structure.java:193)
	at com.sun.jna.Structure.<init>(Structure.java:180)
	at com.sun.jna.Structure.<init>(Structure.java:172)
	at com.sun.jna.platform.mac.MacFileUtils$FileManager$FSRef.<init>(MacFileUtils.java:57)
	at com.sun.jna.platform.mac.MacFileUtils.moveToTrash(MacFileUtils.java:74)
	at processing.app.Platform.deleteFile(Platform.java:382)
	at processing.mode.p5js.p5jsBuild.cleanTempFiles(p5jsBuild.java:246)
	at processing.mode.p5js.p5jsEditor.handleStop(p5jsEditor.java:372)
	at processing.mode.p5js.p5jsEditor.internalCloseRunner(p5jsEditor.java:306)
	at processing.app.ui.Editor.prepareRun(Editor.java:2829)
	at processing.mode.p5js.p5jsEditor.handleRun(p5jsEditor.java:337)
	at processing.mode.p5js.p5jsToolbar.handleRun(p5jsToolbar.java:32)
	at processing.app.ui.EditorToolbar$1.actionPerformed(EditorToolbar.java:157)
	at processing.app.ui.EditorButton.mousePressed(EditorButton.java:151)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by andriybohdan** [comment]
Hello!

I'm also having this problem when trying to make an executable file for Mac OS using the "Export application" tool.

OS version Mac OS Big Sur 11.0.1 (20B29)
Processing versions: 3.5.3, 3.5.4

**Comment by benfry** [comment]
Please use https://discourse.processing.org/ for general troubleshooting questions.
