### ISSUE TITLE
Unrecoverable empty stack exception upon opening new editor window after Beads crash

### ISSUE THREAD

**Issue by dranorter** [processing/processing#6188]
## Description

I have a Processing sketch which makes use of the Beads library, version 1.02. I'm just learning the Beads library and my program for some reason (no doubt my own fault) crashes if I leave it running for a few minutes. This issue is to report an unrecoverable error which occurs if, after my own program crashes, I try to open a new Processing window without shutting down all existing windows first.

## Expected Behavior

My own code should crash without crashing the Processing editor.

## Current Behavior

My program crashes with a stack trace so long the console window can't contain the entire error. Then the "play" button for the sketch becomes unresponsive. I can close the Processing window, but other windows which I have open are affected; none of them can run their sketch. If I try to reopen my project from the file menu on any window, Processing entirely crashes.

Here's what stack trace I could obtain from the initial Beads crash:
[stack trace.txt](https://github.com/processing/processing/files/6745527/stack.trace.txt)

The unrecoverable error is reported in a dialogue box labeled "Serious Problem" and reading "An unexpected, unknown, and unrecoverable error occurred while opening a new editor window. Please report this."

There is a stack trace in that dialogue, although the text isn't copyable. The first line reports a "java.util.EmptyStackException".

![image](https://user-images.githubusercontent.com/14154658/124066629-0812ad00-da07-11eb-8b4a-70012e264b09.png)

## Steps to Reproduce

1. Open the QuasiRhythm sketch.
2. Press "run" or ctrl+r.
3. Let the program run for several minutes. The time varies, but I've removed some of the randomization in the code, and sped up the musical timing, so it should be about two to five minutes.
4. The program stops making noise and a huge stack trace appears.
5. Press the "stop" button. For me, getting the program to actually stop takes two tries.
6. Try to press "run". It no longer runs the program.
7. Try to open up the example project "Beads Lesson 07: Music". (Not all library examples seem to cause the crash.)
8. A dialogue labeled "Serious Problem" appears, reporting an "Empty Stack Exception".

If I omit steps 5 and 6, I still get the error, but I get the following odd behavior: the QuasiRhythm program stays open, and begins omitting sound again as soon as all Processing windows are closed.

```// QuasyRhythm by Daniel Demski
// Adapted from example code which came with the Beads library. 
import beads.*;
import java.util.Arrays; 

AudioContext ac;
// "arc" tracks our position on the straight line. "traj" points along the straight line. The melody uses nearby straight lines.
PVector arc = new PVector(random(0,1),random(0,1),random(0,1));
PVector melody_arc = new PVector(arc.x+random(0,0.5/sqrt(3)),arc.y+random(0,0.5/sqrt(3)),arc.z+random(0,0.5/sqrt(3)));
PVector melody2_arc = new PVector(arc.x+random(0,1.0/sqrt(3)),arc.y+random(0,1.0/sqrt(3)),arc.z+random(0,1.0/sqrt(3)));
//PVector traj = new PVector(1.0/floor(random(1,2.3)),random(0.16,0.9),random(0.16,0.9));
// Random a,b,c
int temp = floor(random(3,9));//3,9
double b = ((double)temp)/(temp+ceil(random(0,2))*Math.pow(-1,floor(random(0,2))));
int temp2 = floor(random(3,9));
double c = ((double)temp2)/(temp2+ceil(random(0,2))*Math.pow(-1,floor(random(0,2))));

// New system: We choose thee ratios for a, b and c, then choose a trajectory which matches.
// New system commented out for version I'm sending to Santiago Beis. I like the sound of the old system better.
/*int temp3 = floor(random(3,9));//3,9
double a = ((double)temp3)/(temp3+ceil(random(0,2))*Math.pow(-1,floor(random(0,2))));
float traj_x = 1.0;
float traj_y = random(0,1);
PVector traj = new PVector(traj_x, traj_y, (float)(Math.log(Math.pow(a,-traj_x)*Math.pow(b,-traj_y))/Math.log(c)));*/

// Going to try and create a more Bead-centric version

//Glide arc_x = new Glide();

// Various lines below can be uncommented to use different rhythms I enjoyed. Sorry it's not organized.

PVector traj = new PVector(1.61803398874989484820458683,1.0,0.61803398874989484820458683);
//PVector traj = new PVector(0.87331694,0.5367354,0.13195878);
//PVector traj = new PVector(2,3,1);

// Choose three intervals a, b, c such that traj.x*a+traj.y*b+traj.z*c = 0
// Equivalently, 3 frequency ratios a, b, c such that a = b^(-y/x)*c^(-z/x)
// And we want all 3 intervals to be close to nice rational intervals

// Solving by hand for traj = (0.87331694,0.5367354,0.13195878)

// Let's start with b = perfect fifth
//float b = 3.0/2;
// Just choosing c to be some otonal interval
//double c = 9.0/7;

//float a = 0.28043742307;//b^(-0.61459405562)*c^(-4.06744742563)
// That's a decent fit for 7/2. We can get it almost exact by
// tempering b just 2%.

//double b = 0.98*3.0/2;
//double a = 1.0/(Math.pow(b,traj.y/traj.x)*Math.pow(c,traj.z/traj.x));//0.5002948;//0.45002876386;

// Hand-calculating for (0.91652966,0.49367833,0.28992528)
//PVector traj = new PVector(2*0.91652966,2*0.49367833,2*0.28992528);
//PVector traj = new PVector(1.0,0.53863868409,0.3163294028);

//double b = 5.0/3;

//double c = 7.0/3;
// double a = 7/12*0.99582955//b^(-0.53863868409)*c^(-0.3163294028)
// We can temper 5/3 by 0.997287 and get a balanced compromise between the 5/3 and 7/12.
//double b = 0.997287*5.0/3;

double a = 1.0/(Math.pow(b,traj.y/traj.x)*Math.pow(c,traj.z/traj.x));



// Start at 440. Start the nearby line's freq2 at a different spot. 
float freq = 440;
float freq2 = 440*(float)c;
float skip_prob = 1;// initially just drums
float extra_exponent = 1;

int intervalscale = 70;//round(random(100,1200));

int notelength = 1000;

void setup() {
  size(300,300);
  ac = new AudioContext();

  Noise wp = new Noise(ac);
  
  intervalscale = round(intervalscale / max(new float[]{traj.x,traj.y,traj.z}));
  // Changed this line to remove some unfortunate clicking
  //notelength = round(intervalscale*1.25);
  notelength = round(intervalscale*min(new float[]{traj.x,traj.y,traj.z})/max(new float[]{traj.x,traj.y,traj.z}));
  
  /*if ((a >= 1 && b >= 1 && c >= 1) || (a <= 1 && b <= 1 && c <= 1) || traj.z <= 0) {
    a = 1.0/a;
    traj = new PVector(traj_x, traj_y, (float)(Math.log(Math.pow(a,-traj_x)*Math.pow(b,-traj_y))/Math.log(c)));
  }
  if (traj.z <= 0) {
    b = 1.0/b;
    traj = new PVector(traj_x, traj_y, (float)(Math.log(Math.pow(a,-traj_x)*Math.pow(b,-traj_y))/Math.log(c)));
  }*/

  final Gain g = new Gain(ac, 1, new Envelope(ac, 0.05));
  final Gain m = new Gain(ac, 1, new Envelope(ac, 0.05));
  final Gain m2 = new Gain(ac, 1, new Envelope(ac, 0.05));
  
  final Bead nextInterval = new Bead() {
    public void messageReceived(Bead message) {
      float distx = (ceil(arc.x) - arc.x)/traj.x;
      if (distx == 0) distx = 1.0/traj.x;
      float disty = (ceil(arc.y) - arc.y)/traj.y;
      if (disty == 0) disty = 1.0/traj.y;
      float distz = (ceil(arc.z) - arc.z)/traj.z;
      if (distz == 0) distz = 1.0/traj.z;
      
      float intervalLength = 1.0;
      
      // Step arc up to the next transition,
      // and add interval which corresponds to
      // projected unit of that dimension
      if (distx <= disty && distx <= distz) {
        arc.add(traj.copy().mult(distx));
        intervalLength = traj.x;
        // x is our main beat
        WavePlayer freqModulator = new WavePlayer(ac, 35, Buffer.SINE);
        Function function = new Function(freqModulator) {
          public float calculate() {
            return x[0] * 12.0 + 20.0;
          }
        };
        WavePlayer bass = new WavePlayer(ac, function, Buffer.SINE);
        Gain env = new Gain(ac, 1, new Envelope(ac, 0));
        //Gain env = new Gain(1, new Envelope(0));
        env.addInput(bass);
        ac.out.addInput(env);
        ((Envelope)env.getGainEnvelope()).addSegment(0.5,10);
        ((Envelope)env.getGainEnvelope()).addSegment(0,intervalscale*intervalLength-10, new KillTrigger(env));
        
        // Occasionally change some parameters
        
        if (random(0,1) > 0.8) {
          if (skip_prob == 1) {
            skip_prob = 0;
          }
        }
        if (random(0,1) > 0.9) {
          skip_prob = 1-skip_prob;
        }
      } else if (disty <= distx && disty <= distz) {
        arc.add(traj.copy().mult(disty));
        intervalLength = traj.y;
      } else {
        arc.add(traj.copy().mult(distz));
        intervalLength = traj.z;
      }
      
      // Only need arc's value mod integers
      while (arc.x > 1) arc.x -= 1;
      while (arc.y > 1) arc.y -= 1;
      while (arc.z > 1) arc.z -= 1;
      
      println(intervalLength);
      ((Envelope)g.getGainEnvelope()).addSegment(0.05, 1);
      ((Envelope)g.getGainEnvelope()).addSegment(0, intervalscale*(intervalLength)-1, this);
      
    }
  };
  
  final Bead melody_nextInterval = new Bead() {
    public void messageReceived(Bead message) {
        float melody_distx = (ceil(melody_arc.x) - melody_arc.x)/traj.x;
      if (melody_distx == 0) melody_distx = 1.0/traj.x;
      float melody_disty = (ceil(melody_arc.y) - melody_arc.y)/traj.y;
      if (melody_disty == 0) melody_disty = 1.0/traj.y;
      float melody_distz = (ceil(melody_arc.z) - melody_arc.z)/traj.z;
      if (melody_distz == 0) melody_distz = 1.0/traj.z;
      
      float melody_intervalLength = 1.0;
      //int pitch = Pitch.forceToScale((int)random(12), Pitch.minor);
      //float freq = Pitch.mtof(pitch + (int)random(5) * 12 + 32);
      float skip_probability = skip_prob;
          
                // Step arc up to the next transition,
      // and add interval which corresponds to
      // projected unit of that dimension
      if (melody_distx <= melody_disty && melody_distx <= melody_distz) {
        melody_arc.add(traj.copy().mult(melody_distx));
        melody_intervalLength = traj.x;
        freq *= a;
        skip_probability = 1-(1-skip_prob)*2;
      } else if (melody_disty <= melody_distx && melody_disty <= melody_distz) {
        melody_arc.add(traj.copy().mult(melody_disty));
        melody_intervalLength = traj.y;
        freq *= b;
      } else {
        melody_arc.add(traj.copy().mult(melody_distz));
        melody_intervalLength = traj.z;
        freq *= c;
      }
      
      // We get more complex intervals between successive notes by not
      // playing every freq we generate.
      if (random(0,1) > 0) {//skip_probability) {
        WavePlayer wp = new WavePlayer(ac, freq, Buffer.TRIANGLE);//Buffer.SINE);
        Gain h = new Gain(ac, 1, new Envelope(ac, 0));
        h.addInput(wp);
        ac.out.addInput(h);
        ((Envelope)h.getGainUGen()).addSegment(0.08, 10);
        ((Envelope)h.getGainUGen()).addSegment(0, notelength, new KillTrigger(h));
      }
      
      // Only need arc's value mod integers
      while (melody_arc.x > 1) melody_arc.x -= 1;
      while (melody_arc.y > 1) melody_arc.y -= 1;
      while (melody_arc.z > 1) melody_arc.z -= 1;
      
      //println(intervalLength);
      ((Envelope)m.getGainUGen()).addSegment(0.05, 1);
      ((Envelope)m.getGainUGen()).addSegment(0, intervalscale*(melody_intervalLength)-1, this);
      
    }
  };
  
  final Bead melody2_nextInterval = new Bead() {
    public void messageReceived(Bead message) {
        float melody2_distx = (ceil(melody2_arc.x) - melody2_arc.x)/traj.x;
      if (melody2_distx == 0) melody2_distx = 1.0/traj.x;
      float melody2_disty = (ceil(melody2_arc.y) - melody2_arc.y)/traj.y;
      if (melody2_disty == 0) melody2_disty = 1.0/traj.y;
      float melody2_distz = (ceil(melody2_arc.z) - melody2_arc.z)/traj.z;
      if (melody2_distz == 0) melody2_distz = 1.0/traj.z;
      
      float melody2_intervalLength = 1.0;
      //int pitch = Pitch.forceToScale((int)random(12), Pitch.minor);
      //float freq = Pitch.mtof(pitch + (int)random(5) * 12 + 32);
      float skip_probability = skip_prob;
          
                // Step arc up to the next transition,
      // and add interval which corresponds to
      // projected unit of that dimension
      if (melody2_distx <= melody2_disty && melody2_distx <= melody2_distz) {
        melody2_arc.add(traj.copy().mult(melody2_distx));
        melody2_intervalLength = traj.x;
        freq2 *= a;
        skip_probability = 1-(1-skip_prob)*2;
      } else if (melody2_disty <= melody2_distx && melody2_disty <= melody2_distz) {
        melody2_arc.add(traj.copy().mult(melody2_disty));
        melody2_intervalLength = traj.y;
        freq2 *= b;
      } else {
        melody2_arc.add(traj.copy().mult(melody2_distz));
        melody2_intervalLength = traj.z;
        freq2 *= c;
      }
      
      // We get more complex intervals between successive notes by not
      // playing every freq we generate.
      if (random(0,1) > skip_probability) {
        WavePlayer wp = new WavePlayer(ac, freq2, Buffer.TRIANGLE);//Buffer.SINE);
        Gain h = new Gain(ac, 1, new Envelope(ac, 0));
        h.addInput(wp);
        ac.out.addInput(h);
        ((Envelope)h.getGainEnvelope()).addSegment(0.08, 10);
        ((Envelope)h.getGainEnvelope()).addSegment(0, notelength, new KillTrigger(h));
      }
      
      // Only need arc's value mod integers
      while (melody2_arc.x > 1) melody2_arc.x -= 1;
      while (melody2_arc.y > 1) melody2_arc.y -= 1;
      while (melody2_arc.z > 1) melody2_arc.z -= 1;
      
      //println(intervalLength);
      ((Envelope)m2.getGainEnvelope()).addSegment(0.05, 1);
      ((Envelope)m2.getGainEnvelope()).addSegment(0, intervalscale*(melody2_intervalLength)-1, this);
      
    }
  };
  
  ((Envelope)g.getGainEnvelope()).addSegment(0,100,nextInterval);
  ((Envelope)m.getGainEnvelope()).addSegment(0.05,100,melody_nextInterval);
  ((Envelope)m2.getGainEnvelope()).addSegment(0.05,100,melody2_nextInterval);
  g.addInput(wp);
  ac.out.addInput(m);
  ac.out.addInput(m2);
  //ac.out.addInput(g);
  ac.start();
}

/*
 * Here's the code to draw a scatterplot waveform.
 * The code draws the current buffer of audio across the
 * width of the window. 
 * 
 * Start with some spunky colors.
 */
color fore = color(255, 102, 204);
color back = color(0,0,0);

/*
 * Just do the work straight into Processing's draw() method.
 */
void draw() {
  loadPixels();
  //set the background
  Arrays.fill(pixels, back);
  //scan across the pixels
  for(int i = 0; i < width; i++) {
    //for each pixel work out where in the current audio buffer we are
    int buffIndex = i * ac.getBufferSize() / width;
    //then work out the pixel height of the audio data at that point
    int vOffset = (int)((1 + ac.out.getValue(0, buffIndex)) * height / 2);
    //draw into Processing's convenient 1-D array of pixels
    vOffset = min(vOffset, height-10);
    //pixels[vOffset * height + i] = fore;
  }
  updatePixels();
}
```

## Your Environment

 

* Processing version: 3.5.4
* Operating System and OS version: Windows 10 Home, version 20H2
* Other information: Beads library version 1.02

## Possible Causes / Solutions
This probably has something to do with the thread-related errors which occur as my program runs. Actually I think my program slowly fills up the stack, accruing a new recursive call with each note played.

I can consistently open a *new* project when in the error state. The fact that the crash depends on what project I try to open is very strange to me.

It's also very odd that the sketch can stay open beyond the crash, and begins emitting sounds again. This suggests the whole problem lies in the way Beads is interacting with the Processing editor during execution.

**Comment by dranorter** [comment]
I think I've found what's special about the specific example code which causes the crash. On my install, opening the file under normal conditions gives the following error in the console.

```
removing C:\Users\drano\Documents\Processing\libraries\beads\examples\Lesson07_Music\Lesson07_Music.pde
java.lang.Exception
	at processing.app.ui.Recent.remove(Recent.java:246)
	at processing.app.ui.Recent.append(Recent.java:294)
	at processing.app.Base.handleOpen(Base.java:1367)
	at processing.app.Base.handleOpen(Base.java:1314)
	at processing.app.Base.handleOpen(Base.java:1303)
	at processing.app.ui.ExamplesFrame$3.mouseClicked(ExamplesFrame.java:143)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.Component.processMouseEvent(Component.java:6542)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by benfry** [comment]
The `Recent.remove()` Exception has already been fixed in the alpha releases for Processing 4. Since it seems to be causing a problem, I'd recommend using one of those instead: https://github.com/processing/processing4/releases

However, that was just a bit of debugging text. If I were to guess, I'd say there's a problem in your sketch or a library that it's using, which is consuming a lot of resources (printing to the Console, in particular) that then causes this bigger issue when the debugging message about `Recent.remove()` shows up. (The exact problem may be revealed if you use 4.0a5, or the problem may go away.)

**Comment by dranorter** [comment]
There's definitely a problem of some sort in my sketch :) I was actually able to repair my sketch last night, I just reported the crash because it asked me to.

Testing my problem code in 4.0a5, I find that no crash occurs; the program doesn't run out of resources in the first place, the "play" button doesn't become unresponsive, and there's no `Recent.remove()` exception upon opening recent files.

Does that mean I should close the issue, or should Processing3 bugs stay open here?

**Comment by benfry** [comment]
Great, thanks for reporting back. I'll just close it here.
