### ISSUE TITLE
P2D and P3D causes "A fatal error has been detected" on all versions of Processing 3+

### ISSUE THREAD

**Issue by Garrettlynch** [processing/processing#6195]
## Description

Java is crashing  with any sketch I run that uses P3D or P2D e.g. `size(2000, 2000, P3D);`. This is the error I'm getting:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007fff3f20ab1b, pid=639, tid=0x0000000000001803
#
# JRE version: Java(TM) SE Runtime Environment (8.0_202-b08) (build 1.8.0_202-b08)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.202-b08 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [CoreFoundation+0xab1b]  CFEqual+0x293
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
```

I thought the issue might be the one described here https://github.com/processing/processing/issues/4104, however, I've tried Processing 3.0b5 (and many other 3 and 4 versions) and the crash still occurs. Processing 2.2.1 does not crash.

## Steps to Reproduce

1. This is the code I'm using to test:

```
void setup() {
  size(500,500,P3D);
  background(0);
}

void draw() {
  translate(width/2, height/2);
  rotateY(0.5);
  rotateX(-0.5);
  box(80,80,80);
}
```

2. Run in any Processing 3+ or 4 on a mac with the configuration below.

## Your Environment

* Processing version: All versions of 3 and 4
* Hardware: MacBook Pro (15-inch, 2019)
* Processor: 2.6 GHz Intel Core i7
* Operating System and OS version: OSX 10.14.6
* Other information: Radeon Pro 555X 4 GB Intel UHD Graphics 630 1536 MB

**Comment by benfry** [comment]
Try using the alpha release of Processing 4: https://github.com/processing/processing4/releases 

It has an update to the OpenGL library that we use, which may fix the problem here.

**Comment by Garrettlynch** [comment]
Hi, I did try Processing 4.0a6 yesterday (with size moved to `settings()`). Same issue but the error is slightly different:

```
processing.mode.java.runner.Runner attempting to attach to VM
processing.mode.java.runner.Runner socket for VM not ready
processing.mode.java.runner.Runner attempting to attach to VM
processing.mode.java.runner.Runner attached to the VM
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007fff480b4b1b, pid=816, tid=9475
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (11.0.11+9) (build 11.0.11+9)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (11.0.11+9, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [CoreFoundation+0xab1b]  CFEqual+0x293
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/garrettlynch/hs_err_pid816.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
```

**Comment by benfry** [comment]
Wow, that's a weird one… So that's a hard crash that's happening inside Java (as in, underneath Processing), but it's especially weird that it happens with drastically different versions of Java (v8 with 3.x, v11 with 4.x)

Are you plugged into an external display? Anything else that might be non-standard about your system? Other graphics hardware or system/kernel extensions installed? Maybe try making a second user account with nothing in it and running there? Start up holding down shift and try from that account?

**Comment by Garrettlynch** [comment]
>Are you plugged into an external display?

ah yes I am. I have a Eizo EV2436W display connected (MacBook Thunderbolt 3 > HDMI adaptor > HDMI to DVI adaptor > Monitor DVI). Tried some tests this morning (I used 3.5.4 and then 4.0a6 - results were the same) based on your hints:

- MacBook display only: works without issue.
- MacBook with external display (using 1920 x 1200 or less): works without issue.
- Macbook with external display (using 1920 x 1200 or more): crash.

So I guess an OpenGL / resolution issue. As is I can workaround now that I know what causes the issue (so thanks for that!) but I would be interested to know if anyone else has this issue on any external display at high resolution.

**Comment by benfry** [comment]
Got it; thanks for the update, and glad you were able to at least track down the nature of what's breaking. Sounds likely to be a bug either inside JOGL (the OpenGL library we're using) or Java not returning the correct size information. (It could also be video RAM, but if your Mac has TB3 you should have plenty to drive an external screen larger than 1920x1200.) 

If you want to dig further into JOGL as an issue, you could try their demos to see if you hit similar issues: https://jogamp.org/jogl-demos/www/

**Comment by Garrettlynch** [comment]
Since this might be very specific to my setup I've tried the JOGL demos to see if it is that. After installing JRE 8 and restarting none of the demos run in the browser for me. They download and then crash with the error below. It seems to be unrelated and there is some chatter about those demos not working but it's ten years old. So not sure and since I don't know how to get beyond the error...

```
com.sun.deploy.net.FailedDownloadException: Unable to load resource: http://jogamp.org/deployment/archive/rc/v2.3.2/jogl-demos/TextFlow.jnlp
	at com.sun.deploy.net.DownloadEngine.actionDownload(Unknown Source)
	at com.sun.deploy.net.DownloadEngine.downloadResource(Unknown Source)
	at com.sun.deploy.cache.ResourceProviderImpl.getResource(Unknown Source)
	at com.sun.deploy.cache.ResourceProviderImpl.getResource(Unknown Source)
	at com.sun.javaws.Launcher.updateFinalLaunchDesc(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.launch(Unknown Source)
	at com.sun.javaws.Main.launchApp(Unknown Source)
	at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
	at com.sun.javaws.Main.access$000(Unknown Source)
	at com.sun.javaws.Main$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
```

Thanks for you help - I have a good workaround now.
