### ISSUE TITLE
4.0b1 java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by jSdCool** [processing/processing#6209]
## Description
when my sketch is open I receive the following error about every 10 seconds regardless of weather the sketch is running

`java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at processing.app.WebServer$Worker.handleClient(WebServer.java:148)
	at processing.app.WebServer$Worker.run(WebServer.java:111)
	at java.base/java.lang.Thread.run(Thread.java:829)
`

## Expected Behavior
this error should not appear especially when the sketch is not running

## Current Behavior
currently this error appears in the console about every 10 seconds if the sketch is running or not

## Steps to Reproduce

1. download the source code from this repository https://github.com/jSdCool/skinny-mann
2. open the sketch in processing 4.0b1
3. run the sketch wait a little while then stop the sketch
the console is now being constantly populated with that error message 

## Your Environment

 

* Processing version:4.0b1
* Operating System and OS version: windows 10 20H2
* Other information:

**Comment by jSdCool** [comment]
eddit: now I cant reproduce this error my self

**Comment by benfry** [comment]
That's the built-in web server that shows the Reference. You may have a firewall turned on that's blocking it.
