### ISSUE TITLE
P3D not working in Win10

### ISSUE THREAD

**Issue by loboere** [processing/processing#6264]
ram 4gb
os: windows 10

java.lang.RuntimeException: Framebuffer objects are not supported by this hardware (or driver) Read http://wiki.processing.org/w/OpenGL_Issues for help.
	at processing.opengl.PJOGL.init(PJOGL.java:428)
	at processing.opengl.PSurfaceJOGL$DrawListener.init(PSurfaceJOGL.java:889)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:644)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:667)
	at jogamp.opengl.GLAutoDrawableBase$1.run(GLAutoDrawableBase.java:431)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1291)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by harshsharma-11** [comment]
I am new to open source and i like processing organisation so i want to contribute to it so @filip @andrewn @fjenett @kjhollen @sansumbrella @prisonerjohn @toolness @Manindra29 @karandudeja @akshay-99 @adilrabbani is there any community channel to communicate about problems facing in project something like slack
