### ISSUE TITLE
libmawt.so: libXext.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#993]
_Original author: xi...@email.de (January 02, 2012 21:55:36)_

<b>What steps will reproduce the problem?</b>
1. I've just unzipped processing-1.5.1-linux.tgz into ~/prog/processing/
1. The I've cd'ed into processing-1.5.1 and typed ./processing
   That not worked. I'm getting (LOGGING=1) :

./processing 
APPDIR=/home/ci/prog/processing/processing-1.5.1
DIR=/home/ci/prog/processing/processing-1.5.1/java
L=rt.jar
LIB=/home/ci/prog/processing/processing-1.5.1/java/lib/rt.jar
L=tools.jar
LIB=/home/ci/prog/processing/processing-1.5.1/java/lib/tools.jar
JDKCP=/home/ci/prog/processing/processing-1.5.1/java/lib/rt.jar:/home/ci/prog/processing/processing-1.5.1/java/lib/tools.jar
SUCCESS=1
CLASSPATH=/home/ci/prog/processing/processing-1.5.1/java/lib/rt.jar:/home/ci/prog/processing/processing-1.5.1/java/lib/tools.jar:/home/ci/prog/processing/processing-1.5.1/lib/ant-launcher.jar:/home/ci/prog/processing/processing-1.5.1/lib/ant.jar:/home/ci/prog/processing/processing-1.5.1/lib/antlr.jar:/home/ci/prog/processing/processing-1.5.1/lib/core.jar:/home/ci/prog/processing/processing-1.5.1/lib/ecj.jar:/home/ci/prog/processing/processing-1.5.1/lib/jna.jar:/home/ci/prog/processing/processing-1.5.1/lib/pde.jar
PATH=/home/ci/prog/processing/processing-1.5.1/java/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/ci/bin
ci@random:~/prog/processing/processing-1.5.1$ Exception in thread &quot;main&quot; java.lang.UnsatisfiedLinkError: /home/ci/prog/processing/processing-1.5.1/java/lib/i386/xawt/libmawt.so: libXext.so.6: cannot open shared object file: No such file or directory
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1803)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1699)
    at java.lang.Runtime.load0(Runtime.java:770)
    at java.lang.System.load(System.java:1003)
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1803)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1720)
    at java.lang.Runtime.loadLibrary0(Runtime.java:823)
    at java.lang.System.loadLibrary(System.java:1028)
    at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:50)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.awt.Toolkit.loadLibraries(Toolkit.java:1605)
    at java.awt.Toolkit.&lt;clinit&gt;(Toolkit.java:1627)
    at processing.app.Base.&lt;clinit&gt;(Base.java:445)
Could not find the main class: processing.app.Base.  Program will exit.

<b>What is the expected output? What do you see instead?</b>
I expect the IDE

<b>What version of the product are you using? On what operating system?</b>
I'm using Linux 3.1.0-1-amd64 x86_64 GNU/Linux (Debian wheezy)

Thanks in advance !

xiscu

_Original issue: http://code.google.com/p/processing/issues/detail?id=955_

**Comment by csingh1981** [comment]
I have the similar issue: Anyone know the answer please help me: Not getting proper answer from anywhere.
Exception in thread "main" java.lang.UnsatisfiedLinkError: /jvm/jdk1.8.0_72/jre/lib/amd64/libawt_xawt.so: libXtst.so.6: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1842)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at java.awt.Toolkit$3.run(Toolkit.java:1636)
	at java.awt.Toolkit$3.run(Toolkit.java:1634)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.loadLibraries(Toolkit.java:1633)
	at java.awt.Toolkit.<clinit>(Toolkit.java:1668)
	at java.awt.Component.<clinit>(Component.java:593)
	at Test.main(Test.java:8)
